1000 user feedback system
Samfundet/Samfundet4 pull request #1004
Opened 2024-02-21 17:33 UTC by tiniuspre

Added feedback

![](https://4.bp.blogspot.com/-8sq_x5f90QE/XJ1EtCYFC6I/AAAAAAAAR5c/TSF_5QFTZq8DaxnBVRrUo2opuemKEeMfgCLcBGAs/s320/shredder.gif)

2024-02-21 18:58 UTC, robines commented
Syns vi kan fjerne feedback type, det er noe vi får vite gjennom å lese tilbakemeldingen uansett. Så blir det en mindre ting en bruker må klikke seg gjennom, som øker sjansen for at de i det hele tatt orker å sende inn noe.

2024-02-21 19:05 UTC, tiniuspre commented
@robines Fjernet feedback type

2024-02-21 19:09 UTC, robines requested changes

2024-02-21 19:09 UTC, robines commented on backend/samfundet/models/general.py
> +        return f'{self.text[0:10] + "..." if len(self.text) > 10 else self.text}... - {self.feedback_type}'
Syns vi kan legge til en util-funksjon i backend for dette. Kall den `ellipsize` eller noe. Gjerne gjør den fleksibel og la den ta inn max length og ellipsis string (default `...`)

2024-02-21 19:09 UTC, robines commented on backend/samfundet/views.py
> +class UserFeedBackView(CreateAPIView):
Bare for å pirke: Feedback er ett ord, så bør endres fra `FeedBack` til `Feedback`

2024-02-21 19:09 UTC, robines commented on backend/samfundet/views.py
> +class UserFeedBackView(CreateAPIView):
Samt oppdateres andre steder det er relevant

2024-02-21 19:09 UTC, robines commented on backend/samfundet/migrations/0010_userfeedbackmodel.py
> +                ("screen_resolution", models.CharField(blank=True, max_length=255)),
max_length kan begrenses her. 12 eller 16 er sikkert good, gitt av vi lagrer i dette formatet `10000x10000`

2024-02-21 19:09 UTC, robines commented on backend/samfundet/migrations/0010_userfeedbackmodel.py
> +                ("device_headers", models.CharField(blank=True, max_length=255)),
Rename til `user_agent`, og gjerne øk max_length litt, finnes mange user-agents som er lange

2024-02-21 19:11 UTC, robines commented on backend/samfundet/migrations/0010_userfeedbackmodel.py
> +                ("screen_resolution", models.CharField(blank=True, max_length=255)),
(Bare å resolve denne selv når gjort)

2024-02-21 19:12 UTC, robines commented on backend/samfundet/views.py
> +class UserFeedBackView(CreateAPIView):
(Bare å resolve denne selv når gjort)

2024-02-21 19:12 UTC, robines commented on backend/samfundet/migrations/0010_userfeedbackmodel.py
> +                ("device_headers", models.CharField(blank=True, max_length=255)),
(Bare å resolve denne selv når gjort)

2024-02-21 19:12 UTC, robines commented
@tiniuspre Kunne du ha lagt til screenshots for hvordan dette ser ut på mobil?

2024-02-21 20:41 UTC, tiniuspre commented on backend/samfundet/models/general.py
> +        return f'{self.text[0:10] + "..." if len(self.text) > 10 else self.text}... - {self.feedback_type}'
Done lagde fil som heter string_utils.py

2024-02-21 20:41 UTC, tiniuspre commented
@robines Screenshots for mobil er oppe

2024-02-22 22:21 UTC, Snorre98 commented on frontend/src/Components/UserFeedback/UserFeedback.module.scss
> +}
```suggestion
.feedback_button {
  position: sticky;
  height: 50px;
  width: 50px;
  margin: 2rem;
}
```

2024-02-22 22:26 UTC, Snorre98 commented on frontend/src/Components/UserFeedback/UserFeedback.tsx
> +        <text>{t(KEY.feedback_helper_text)}</text>
Bruk p-tag?

2024-02-22 22:30 UTC, Snorre98 commented on frontend/src/i18n/translations.ts
> +  // Feedback
Bruk heller text-item for setninger: https://github.com/Samfundet/Samfundet4/blob/master/frontend/src/constants/TextItems.ts

De implementasjon på f.eks. Lyche

Vi adminsitrere disse fra Django admin panelet for nå

2024-02-22 22:31 UTC, Snorre98 commented on frontend/src/i18n/constants.ts
> +  // Feedback
Bruk heller text-item for setninger: https://github.com/Samfundet/Samfundet4/blob/master/frontend/src/constants/TextItems.ts

De implementasjon på f.eks. Lyche

Vi adminsitrere disse fra Django admin panelet for nå

2024-02-22 22:32 UTC, Snorre98 commented on frontend/src/Components/UserFeedback/UserFeedback.module.scss
> +  }
Ser dette ble litt rart, men du skjønner kanskje poenget

2024-02-22 22:33 UTC, Snorre98 commented on backend/samfundet/models/general.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
Vil dette kreve at man er logget inn? Spør fordu jeg er nysgjerrig. Bare resolve

2024-02-22 22:34 UTC, Snorre98 commented on frontend/src/Components/UserFeedback/UserFeedback.module.scss
> +}
Dette ble også litt rart

2024-02-22 22:36 UTC, tiniuspre commented on backend/samfundet/models/general.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
Nei, siden null er true så må den ikke være fylt ut. Om du ser på view'en som hører til så er det AllowAny permission.

Om en som er logget inn legger en tilbakemelding så får vi brukeren, ellers så vil den være null

2024-02-22 23:08 UTC, robines commented on backend/samfundet/models/general.py
> +        return f'{self.text[0:10] + "..." if len(self.text) > 10 else self.text}... - {self.feedback_type}'
Gucci

2024-02-22 23:10 UTC, tiniuspre commented on frontend/src/Components/UserFeedback/UserFeedback.module.scss
> +}
Hvordan da

2024-02-22 23:20 UTC, robines commented on frontend/src/i18n/translations.ts
> +  // Feedback
Syns personlig at for akkurat dette er det helt greit om det ligger i translations. Det er bare noe vi skal være borti, og dette er sannsynligvis ikke en komponent som kommer til å alltid være synlig, så det er ikke stress å endre formuleringer og slikt i koden. Pluss, fint å unngå DB-kall der vi kan

2024-02-22 23:27 UTC, tiniuspre commented on frontend/src/Components/UserFeedback/UserFeedback.tsx
> +        <text>{t(KEY.feedback_helper_text)}</text>
Done

2024-02-22 23:28 UTC, tiniuspre commented on frontend/src/Components/UserFeedback/UserFeedback.tsx
> +        <text>{t(KEY.feedback_want_contact_text)}</text>
Done

2024-02-22 23:29 UTC, tiniuspre commented on frontend/src/i18n/translations.ts
> +  // Feedback
Ble en mellomting, textitem på de litt lengere. Kan muligens være lurt å teste ut litt forskjellige tekster om hva brukeren burde skrive om

2024-02-22 23:29 UTC, tiniuspre commented on frontend/src/i18n/constants.ts
> +  // Feedback
Done

2024-02-22 23:35 UTC, tiniuspre commented on frontend/src/Components/UserFeedback/UserFeedback.module.scss
> +  }
Endret

2024-02-27 17:50 UTC, tiniuspre commented on frontend/src/Components/UserFeedback/UserFeedback.module.scss
> +}
Ser bedre ut uten margin

2024-02-27 18:59 UTC, Snorre98 approved these changes

2024-02-27 19:14 UTC, robines approved these changes

2024-02-27 19:16 UTC, merged

2024-02-27 22:56 UTC, emilte commented on backend/samfundet/models/general.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
Ønsker vi cascade?
Jeg ville kanskje tatt vare på dem (DO_NOTHING) ellerno

2024-02-27 22:57 UTC, emilte commented on backend/samfundet/serializers.py
> +class UserFeedbackSerializer(serializers.ModelSerializer):
Bør nok bruke CustomBaseSerializer

2024-02-27 22:58 UTC, emilte commented on backend/samfundet/serializers.py
> +        }
Er disse nødvendig når blank=True?

2024-02-27 23:00 UTC, emilte commented on backend/samfundet/views.py
> +class UserFeedbackView(CreateAPIView):
Hvorfor ikke ModelViewSet?

2024-02-27 23:02 UTC, emilte commented on backend/samfundet/views.py
> +    model = UserFeedbackModel
Har denne effekt?

2024-02-27 23:03 UTC, emilte commented on frontend/src/Components/UserFeedback/UserFeedback.tsx
> +  const handleFormSubmit = (formData: Record<string, string>) => {
Foretrekker function

2024-02-27 23:05 UTC, emilte commented on frontend/src/Components/UserFeedback/UserFeedback.tsx
> +  }
Denne tror jeg ikke vil respondere på endring i enabled.
Trenger du det i det hele tatt når den alltid er true?

2024-02-27 23:05 UTC, emilte commented on frontend/src/Components/UserFeedback/UserFeedback.tsx
> +      });
Toast?

2024-02-27 23:05 UTC, emilte commented on frontend/src/Components/UserFeedback/UserFeedback.tsx
> +  const ModalContent = () => {
Har vi ikke en Modal comp?

2024-02-27 23:06 UTC, tiniuspre commented on backend/samfundet/serializers.py
> +class UserFeedbackSerializer(serializers.ModelSerializer):
Den krever at en bruker sender inn. Her kan man være anonym

2024-02-27 23:06 UTC, emilte commented on frontend/src/Components/UserFeedback/UserFeedback.tsx
> +  const ModalContent = () => {
Hvorfor ikke bare vanlig const?

2024-02-28 00:03 UTC, emilte commented on backend/samfundet/serializers.py
> +class UserFeedbackSerializer(serializers.ModelSerializer):
Håndterer den ikke manglende bruker?

2024-02-28 00:09 UTC, tiniuspre commented on backend/samfundet/serializers.py
> +class UserFeedbackSerializer(serializers.ModelSerializer):
Nope får `ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x110ddbf90>": "UserFeedbackModel.updated_by" must be a "User" instance.
`
Er for user er null når jeg tar det anonymt

2024-02-28 00:10 UTC, emilte commented on backend/samfundet/serializers.py
> +class UserFeedbackSerializer(serializers.ModelSerializer):
Aha, det bør skrives om.

2024-02-28 00:10 UTC, emilte commented on backend/samfundet/serializers.py
> +class UserFeedbackSerializer(serializers.ModelSerializer):
Den burde være best effort og aldri stå til hinder

2024-02-28 00:28 UTC, tiniuspre commented on backend/samfundet/models/general.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
DO_NOTHING fungerer generelt dårlig etter min erfaring, vil som oftest forårsake en crash.

Kan lage et issu på det at vi burde oppdatere CustomBaseSerializer og tillhørende modell, med et felt user_was_deleted elns så lage egen on delete greie.

2024-02-28 00:32 UTC, tiniuspre commented on backend/samfundet/views.py
> +class UserFeedbackView(CreateAPIView):
Litt personlig prefferanse, kan sikkert endre det. Er mest glad i bruke APIView og tilsvarende enklere kontroll over flyt i dataen

2024-02-28 10:02 UTC, emilte commented on backend/samfundet/views.py
> +class UserFeedbackView(CreateAPIView):
Har et anstrengt forhold til DRF sjæl

2024-02-28 10:03 UTC, emilte commented on backend/samfundet/views.py
> +class UserFeedbackView(CreateAPIView):
Mister grensesnittet på denne måten da

2024-02-29 22:23 UTC, emilte commented on backend/samfundet/models/general.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
SET_NULL