1002 add to samfform validation between fields
Samfundet/Samfundet4 pull request #1006
Opened 2024-02-22 20:34 UTC by aTrueYety

2024-02-27 18:21 UTC, tiniuspre requested changes

2024-02-27 18:21 UTC, tiniuspre commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +              values['start_dt'] != undefined && values['end_dt'] != undefined && values['start_dt'] < values['end_dt']
Kan dette være en egen funksjon, ser den er duplikat under

2024-02-27 18:24 UTC, snorrekr approved these changes

2024-02-27 18:28 UTC, tiniuspre commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +              values['start_dt'] != undefined && values['end_dt'] != undefined && values['start_dt'] < values['end_dt']
Altså validator

2024-02-27 18:41 UTC, aTrueYety commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +              values['start_dt'] != undefined && values['end_dt'] != undefined && values['start_dt'] < values['end_dt']
Done

2024-02-27 18:41 UTC, tiniuspre approved these changes
![](https://media1.giphy.com/media/yJFeycRK2DB4c/200w.gif?cid=6c09b952vl6bohphupghcjn5ryak7hcyjdfkkl2e2r0ycyek&ep=v1_gifs_search&rid=200w.gif&ct=g)

2024-02-27 23:13 UTC, emilte commented on frontend/src/Forms/SamfFormField.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Bør nok ha alle deps

2024-02-27 23:14 UTC, emilte commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +  values['start_dt'] != undefined && values['end_dt'] != undefined && values['start_dt'] < values['end_dt'];
function, og kan flyttes til ./utils

2024-02-27 23:15 UTC, emilte commented on frontend/src/Forms/SamfForm.stories.tsx
>    return 'Tallet må være 69';
Hvorfor skal validatorene få alle values?

2024-02-29 14:39 UTC, aTrueYety commented on frontend/src/Forms/SamfFormField.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Hva er deps?

2024-02-29 14:41 UTC, aTrueYety commented on frontend/src/Forms/SamfForm.stories.tsx
>    return 'Tallet må være 69';
Dette gjøres så felt kan valideres basert på mer kontekst en kun sin egen verdi. For eksempel hvis man har to dato felt og du vill validere slik at den ene datoen er før den andre trengs verdien til begge feltene i valideringen.

2024-02-29 15:04 UTC, aTrueYety commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +  values['start_dt'] != undefined && values['end_dt'] != undefined && values['start_dt'] < values['end_dt'];
Endringen blir vel typ:

I util
```
export function isValidDateRange(start_dt: Date, end_dt: Date): boolean {
  return start_dt != undefined && end_dt != undefined && start_dt < end_dt;
}
```
```
validator={(values: SamfFormModel) => {
  return isValidDateRange(values['start_dt'] as Date, values['end_dt'] as Date);
}}
```

2024-02-29 17:41 UTC, aTrueYety commented on frontend/src/Forms/SamfFormField.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Fikset det nå

2024-02-29 17:41 UTC, aTrueYety commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +  values['start_dt'] != undefined && values['end_dt'] != undefined && values['start_dt'] < values['end_dt'];
Jeg gjør det sånn jeg :)

2024-03-01 12:37 UTC, emilte commented on frontend/src/Forms/SamfForm.stories.tsx
>    return 'Tallet må være 69';
Skjønner, git mening

2024-03-01 12:39 UTC, emilte commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +              return isValidDateRange(values['start_dt'] as Date, values['end_dt'] as Date);
casting bekymrer meg litt. Er det ikke noe annet sted det kan types?

2024-03-06 15:50 UTC, aTrueYety commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +              return isValidDateRange(values['start_dt'] as Date, values['end_dt'] as Date);
Hva tenker du @emilte

2024-03-06 21:31 UTC, emilte commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +              return isValidDateRange(values['start_dt'] as Date, values['end_dt'] as Date);
SamfForm kan ta inn type no?

2024-03-06 21:39 UTC, aTrueYety commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +              return isValidDateRange(values['start_dt'] as Date, values['end_dt'] as Date);
njaaa den er type generic men den er ikke kodet iht det. Verdiene lagres i en state med denne typen:
![image](https://github.com/Samfundet/Samfundet4/assets/142814286/3caf1718-03d1-445a-92a2-f86f7d2b8576)

Tror dette er en lat måte å ikke lage et eget Error og Validity object på ved å stappa alt mulig i en Record. Verdiene lagres under typen 'unknown' så vi mister type informasjon og må det da castes tilbake på et eller annet sted. Hvis ikke her så blir det et annet set. Har planer om å skrive mye av SamfForm på nytt fordi det er stadig feil og prolbemer ved bruk. Se #1025. Dette er typ noe som burde fikses i den issuen tenker jeg og passer egt ikke her.

2024-03-06 23:30 UTC, emilte commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +              return isValidDateRange(values['start_dt'] as Date, values['end_dt'] as Date);
Prøv å få tak i @evgiz

2024-03-14 17:26 UTC, aTrueYety commented
Solved in #1031

2024-03-14 17:26 UTC, closed without merging