Div bug fix
Samfundet/Samfundet4 pull request #1015
Opened 2024-02-27 21:07 UTC by tiniuspre

2024-02-27 22:20 UTC, robines requested changes

2024-02-27 22:20 UTC, robines commented on frontend/src/Components/UserFeedback/UserFeedback.module.scss
> +
```suggestion
```

2024-02-27 22:53 UTC, robines approved these changes

2024-02-29 17:22 UTC, Snorre98 approved these changes

2024-02-29 17:22 UTC, merged