Endpoint for missing infopages
Samfundet/Samfundet4 pull request #1047
Opened 2024-03-27 21:48 UTC by magsyg

counts all venues, gangs and organizations
aswell as all misc infopages found in samf3

added rest of the gangs mentioned in samf3

closes #290

2024-04-01 12:45 UTC, tiniuspre requested changes

2024-04-01 12:45 UTC, tiniuspre commented on backend/root/management/commands/seed_scripts/gangs.py
> +        ('Studentersamfundets Orkester', 'Låfte'),  # TODO Remove this?
Fjerne TODO? Syntes vi burde ha minimalt med #TODO i kode

2024-04-01 12:45 UTC, tiniuspre commented on backend/root/management/commands/seed_scripts/gangs.py
> +        ('Studentersamfundets Orkester', 'Låfte'),  # TODO Remove this?
```suggestion
        ('Studentersamfundets Orkester', 'Låfte')
```

2024-04-01 12:45 UTC, tiniuspre commented on backend/root/management/commands/seed_scripts/gangs.py
> +        ('Studentersamfundets Orkester', 'Låfte'),  # TODO Remove this?
```suggestion
```

2024-04-01 12:45 UTC, tiniuspre commented on backend/samfundet/views.py
> +            if not gang.info_page or gang.info_page.slug_field != slug:
Det her kan være en funksjon, kan løse C901 som du har noqa

2024-04-02 17:14 UTC, magsyg commented on backend/root/management/commands/seed_scripts/gangs.py
> +        ('Studentersamfundets Orkester', 'Låfte'),  # TODO Remove this?
Done

2024-04-02 17:15 UTC, magsyg commented on backend/samfundet/views.py
> +            if not gang.info_page or gang.info_page.slug_field != slug:
C901 kommer av at request vell børe være med uansett i requests?

2024-04-02 17:17 UTC, magsyg commented on backend/samfundet/views.py
> +            if not gang.info_page or gang.info_page.slug_field != slug:
Hmmm bør vell det, misc bør vell kanskje være i en egen fil av placeholdres ogsånt, bør nok settes i infopage som metode

Men hvor foreslår du misc bør plaseres?

2024-04-06 14:28 UTC, robines commented on backend/root/management/commands/seed_scripts/gangs.py
> +        ('Studentersamfundets Orkester', 'Låfte'),  # TODO Remove this?
@tiniuspre resolve?

2024-04-06 14:30 UTC, robines commented on backend/samfundet/views.py
> +            if not gang.info_page or gang.info_page.slug_field != slug:
@tiniuspre

2024-04-09 23:32 UTC, tiniuspre commented on backend/samfundet/views.py
> +            if not gang.info_page or gang.info_page.slug_field != slug:
C901 er complex structures. Den er nå satt til 5 i kompleksitet.

https://docs.astral.sh/ruff/rules/complex-structure/

2024-05-08 09:57 UTC, magsyg commented on backend/samfundet/views.py
> +            if not gang.info_page or gang.info_page.slug_field != slug:
Fuck off complex structures er dritt @tiniuspre, pusher ikke før den fjernes

2025-03-01 10:51 UTC, closed without merging