989 Create MembershipPage
Samfundet/Samfundet4 pull request #1071
Opened 2024-04-16 19:45 UTC by amaliejvik

- Create MembershipPage that can be reached from Navbar > Information > Membership. 
- Set up correct routing.
- The information on MembershipPage is displayed using TextItems, providing dark-mode- and translation-functionality (added in seed script, so one should seed in the branch before opening localhost)

NB: The url link to Luka is not working, because the page has not been set up yet. 

Closes #989 #990 #991

2024-04-18 16:35 UTC, snorrekr approved these changes

2024-04-18 22:09 UTC, Snorre98 approved these changes

2024-04-22 11:35 UTC, amaliejvik commented
vet ikke hvorfor junior sin review ikke teller som code owner review?
tror jeg trenger en av deres approve for å få merget hehe 😇  @robines @tiniusp

2024-04-25 17:01 UTC, tiniuspre approved these changes

2024-04-25 17:11 UTC, robines requested changes

2024-04-25 17:11 UTC, robines commented on frontend/src/Pages/MembershipPage/MembershipPage.module.scss
> +  font-family: sans-serif;
Skal ikke trenge å spesifisere font-family her, det skal arve font automatisk.

```suggestion
```

2024-04-25 17:11 UTC, robines commented on frontend/src/Pages/MembershipPage/MembershipPage.module.scss
> +  font-family: sans-serif;
Se andre kommentar om `font-family`

```suggestion
```

2024-04-25 17:11 UTC, robines commented on frontend/src/Pages/MembershipPage/MembershipPage.module.scss
> +  font-family: sans-serif;
Se andre kommentar om `font-family`

```suggestion
```

2024-04-25 17:11 UTC, robines commented on frontend/src/Pages/MembershipPage/MembershipPage.module.scss
> +  font-family: sans-serif;
Se andre kommentar om `font-family`

```suggestion
```

2024-04-25 17:11 UTC, robines commented on frontend/src/Pages/MembershipPage/MembershipPage.tsx
> +            <a className={styles.link} href={ROUTES.other.lover_og_statutter}>
```suggestion
            <a className={styles.link} href={ROUTES.other.laws_and_statutes}>
```

2024-04-25 17:11 UTC, robines commented on frontend/src/routes/other.ts
> +  lover_og_statutter: 'http://raadet.samfundet.no/lover.html',
```suggestion
  laws_and_statutes: 'http://raadet.samfundet.no/lover.html',
```

2024-04-25 18:38 UTC, amaliejvik commented on frontend/src/Pages/MembershipPage/MembershipPage.module.scss
> +  font-family: sans-serif;
fikset:)

2024-04-25 18:38 UTC, amaliejvik commented on frontend/src/Pages/MembershipPage/MembershipPage.module.scss
> +  font-family: sans-serif;
fikset:)

2024-04-25 18:38 UTC, amaliejvik commented on frontend/src/Pages/MembershipPage/MembershipPage.tsx
> +            <a className={styles.link} href={ROUTES.other.lover_og_statutter}>
fikset:)

2024-04-25 18:38 UTC, amaliejvik commented on frontend/src/Pages/MembershipPage/MembershipPage.module.scss
> +  font-family: sans-serif;
fikset:)

2024-04-25 18:39 UTC, amaliejvik commented on frontend/src/Pages/MembershipPage/MembershipPage.module.scss
> +  font-family: sans-serif;
fikset:)

2024-04-25 18:39 UTC, amaliejvik commented on frontend/src/Pages/MembershipPage/MembershipPage.module.scss
> +  font-family: sans-serif;
fikset:)

2024-05-07 16:11 UTC, robines approved these changes

2024-05-09 06:34 UTC, merged