1021 create usetitle hook
Samfundet/Samfundet4 pull request #1073
Opened 2024-04-18 17:43 UTC by johannegg

Added a title to the tab on every page.

2024-04-18 21:01 UTC, Snorre98 approved these changes
Se bra ut!

2024-04-25 15:10 UTC, robines requested changes

2024-04-25 15:10 UTC, robines commented on frontend/src/Components/UseTitle/UseTitle.tsx
> +export function UseTitle(title: string) {
Gjerne bruk camelCase for funksjoner

```suggestion
export function useTitle(title: string) {
```

2024-04-25 15:10 UTC, robines commented on frontend/src/Components/UseTitle/UseTitle.tsx
> +import { useEffect } from 'react';
useTitle er en hook og ikke komponent, så passer bedre inn i `hooks.ts`, så gjerne flytt definisjonen dit

2024-04-26 10:34 UTC, robines commented on frontend/src/hooks.ts
> +}
Ser bra ut! Men jeg tror det trengs en måte å sette tittel uten ` | `. For eksempel om man navigerer til Informasjon > Generelt, så blir tittelen `Samfundet | Om Samfundet`, og hvis man går tilbake til hjemmesiden vil man forvente at den blir kun `Samfundet`, men det blir den ikke, og det er ingen måte nå å gjøre det. 

Tror også det kan være greit å ha støtte for å ha andre navn enn Samfundet, for eksempel Lyche-sider trenger ikke å ha Samfundet i tittelen i det hele tatt.

Flere måter man kan løse det på, men under er et forslag. Jeg foretrekker også å ha "Samfundet" bak navnet på siden. Om man har mange tabs åpne vil det være enklere å se hva som er hva.

```suggestion
export function useTitle(title: string, suffix: string = 'Samfundet'): void {
  useEffect(() => {
    document.title = title ? `${title} | ${suffix}` : suffix;
  }, [title, suffix]);
}
```

Om du går for denne løsningen vil `useTitle('')` gi `Samfundet` som tittel, og `useTitle('Reservasjon', 'Lyche')` gi `Reservasjon | Lyche`

2024-05-07 16:06 UTC, Snorre98 commented on frontend/src/hooks.ts
> +}
@robines bare gjøre disse endringene, så få den inn?

2024-06-29 02:27 UTC, robines approved these changes

2024-06-29 02:27 UTC, merged