[Bugfix] Change datetime fields into date fields on ClosedPeriod form
Samfundet/Samfundet4 pull request #1094
Opened 2024-05-07 19:14 UTC by Frenje123

2024-05-07 19:17 UTC, tiniuspre requested changes

2024-05-07 19:17 UTC, tiniuspre commented on frontend/src/PagesAdmin/ClosedPeriodFormAdminPage/ClosedPeriodFormAdminPage.tsx
> +          <SamfFormField field="end_dt" type="date" label={`${t(KEY.end_time)}`}></SamfFormField>
litt missvisende "_dt" er jo kort for datetime. burde heller bare være "_date" da

2024-05-07 19:27 UTC, tiniuspre approved these changes

2024-06-11 16:28 UTC, hei98 approved these changes
Ser bra ut!

2024-06-19 21:54 UTC, Snorre98 approved these changes

2024-06-19 21:54 UTC, merged