1096 skeleton for recruitment homepage
Samfundet/Samfundet4 pull request #1119
Opened 2024-05-10 15:25 UTC by Snorre98

This PR aims to rework the recruitment homepage. Because Samf4 will host admissions for external organizations (e.i. UKA and ISFiT) it should be a clear difference between the admissions. Therefor I created this UI which is set up to take data from the DB, but as of now uses mock data.

Further work ( #1117) is needed to create a page where applicants can find open positions for the different organizations. It makes sense to keep these on separate pages.
- ❗❕ Right now the old UI for viewing open positions is still on the page. This will be removed/replaces by the page and overview solved in 

- A page which displays the authenticated users applications. [Has been started here](http://localhost:3000/recruitment/1/my-applications/), but this is just a skeleton.

Unrelated to this issue (#1096) I created logo components for Samf,  UKA and ISFiT. It is possible to logo size and color, which is nice for responsive design (darkmode./ mobile)

# Desktop UI (the UI looks decent-ish in dark-mode and on mobile)
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/f81ef008-385b-48a7-bfa0-61b622d716b2)

# Mobile UI
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/bd7d30a3-55cb-4362-87b2-4caed2a74e70)

# Darkmode
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/38be33f6-c2ae-428c-b4a8-6b09baf7ed75)

2024-05-14 06:24 UTC, Snorre98 commented
Working on a better solution for theme "switching" based on organization in #1117, which I will move to branch 689 (#689)

2024-05-14 17:05 UTC, snorrekr commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
> +  };
This too?

2024-05-14 17:08 UTC, snorrekr approved these changes

2024-05-15 19:41 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
> +  const UKA = 'UKA';
In constants?

2024-05-15 19:42 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
> +  };
Will create another PR for styling page based on organization.

2024-05-17 17:07 UTC, amaliejvik reviewed
wooow så kult!! blir inspirert😎 La inn et par kommentarer!

2024-05-17 17:07 UTC, amaliejvik commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
> +        </Button>
Oversettelse på disse knappene er ikke lagt til ser jeg, men det kan jo gjøres senere også:)

2024-05-17 17:07 UTC, amaliejvik commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
> +  const applicationCardButtons = (
Knappene på det første RecruitmentCardet (for Samf)  er av en eller annen grunn bredere enn på de to andre

<img width="1152" alt="Skjermbilde 2024-05-17 kl  18 58 14" src="https://github.com/Samfundet/Samfundet4/assets/125203980/f8ee1f94-2179-47b0-b534-ec68f09fa31f">

2024-07-28 18:24 UTC, Snorre98 commented on frontend/src/Components/RecruitmentApplicantsStatus/RecruitmentApplicantsStatus.tsx
Is not related to the core of this issue

2024-07-28 18:25 UTC, Snorre98 commented on frontend/src/Components/TabBar/TabBar.module.scss
modifies TabBar styling

2024-07-28 18:25 UTC, Snorre98 commented on frontend/src/Components/TabBar/TabBar.tsx
Modifies TabBar styling

2024-07-28 19:03 UTC, Snorre98 commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/GangPositionDropdown/GangPositionDropdown.tsx
This is the original component which displays positions. I think the filtering of positions should be in the backend. Issue #1121 will solve this.

2024-07-28 19:04 UTC, Snorre98 commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/GangTypeContainer/GangTypeContainer.tsx
This is also part of the original recruitment positions display (the dropdown). It has just been moved here.

2024-07-28 19:16 UTC, Snorre98 commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/GangsTabs/GangsTabs.tsx
Different display of positions. An overview of positions categorized by "gang types" -> "gangs"

2024-07-28 19:22 UTC, Snorre98 commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/PositionsTable/PositionsTable.tsx
Table which displays positions for a single gang.
In the tab system loading-state is "bubbled" up to parent, to disable parent tabs when child TABLE is loading.

2024-07-28 19:27 UTC, Snorre98 commented on frontend/src/Pages/OrganizationRecruitmentPage/OrganizationRecruitmentPage.tsx
> +  const embededId = '-nYQb8_TvQ4'; // TODO: DO IN ISSUE #1114. Make this dynamic
1121

2024-07-28 19:28 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/NoPositions/NoPositions.module.scss
> +@import '../../../../constants';
fix import

2024-07-28 19:30 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/NoPositions/NoPositions.tsx
> +import styles from './NoPositions.module.scss';
This was on the RecruitmentPage, but as a TSX element in the page fil. I made a component. It only pertains to instances when there are no active recruitments for Samfundet.

2024-07-28 19:30 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
> +  isAuthenticated?: boolean;
should probably just use context provider

2024-07-30 15:15 UTC, Snorre98 commented on frontend/src/Pages/OrganizationRecruitmentPage/OrganizationRecruitmentPage.tsx
The page which displays positions the organization is recruiting. Some of the styling is dependent on organization. UKA is blue, Samf is red and so on. This is done by a global organization theme context. The organization is set by fetching the recruitment object and getting the organization which is contained in the recruitment object. Recruitment id is defined in the url param.

Some of the styling of the components used here has to be modified to depend on the organization which is recruiting. This will be solved in a issue I created which solved a broader styling for organizations, like the navbar and components used on this page.

2024-07-30 15:17 UTC, Snorre98 commented on frontend/src/Pages/OrganizationRecruitmentPage/OrganizationRecruitmentPage.tsx
> +  const embededId = '-nYQb8_TvQ4'; // TODO: DO IN ISSUE #1121. Make this dynamic
Need a "promo" media field in the recruitment model, or maybe  promo video field and promo image field.

2024-07-30 15:21 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/NoPositions/NoPositions.tsx
This is what was displayed on the page at ":3000/recruitment" when there are no positions. It was defined in the page. I moved it to a separate component.

It displays information about Samf only, so this has to be updated to depend on organization. I will create a issue for this.

2024-07-30 15:25 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/PersonalRow/PersonalRow.tsx
This is also something that existed on the original recruitment page. I moved it to its own component. Migth move it to the main components folder, as this is used on multiple pages.

2024-07-30 15:28 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.module.scss
> +  "text buttons";
grid for smoothbrains :)

2024-07-30 15:31 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
This is used to display different active recruitments. It is styled dependent on organization. Found on ":3000/recruitment".

2024-07-30 15:33 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.module.scss
This is more or less the same as the original RecruitmentPage styling at ":3000/recruitment". Will clean up some of the css

2024-07-30 15:34 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
Changed to only get active recruitments and render recruitment cards based on this

2024-07-30 15:37 UTC, Snorre98 commented on frontend/src/context/OrgContextProvider.tsx
Changed key to be the same as OrgNameTypeValue, which is the same as in the database now.

2024-07-30 15:38 UTC, Snorre98 commented on frontend/src/index.tsx
Adds OrganizationContextProvider to wrap the app, making it global. This way we can change stuff like the navbar

2024-07-30 15:40 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
> +        </Button>
Fixed

2024-07-30 15:41 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
> +  };
fixed

2024-07-30 15:41 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
> +  const UKA = 'UKA';
fixed

2024-07-30 20:51 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.module.scss
done

2024-07-30 21:33 UTC, Snorre98 commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/RecruitmentTabs/RecruitmentTabs.tsx
> +        <NoPositions />
Done

2024-07-30 22:08 UTC, robines requested changes

2024-07-30 22:08 UTC, robines commented on frontend/src/Pages/RecruitmentPage/Components/RecruitmentCard/RecruitmentCard.tsx
> +        <Text size={'m'} as={'strong'}>
```suggestion
      <Text size="m" as="p">
        <Text size="m" as="strong">
          {t(KEY.recruitment_organization)}
        </Text>
        {organizationName}
      </Text>
      <Text size="m" as="p">
        <Text size="m" as="strong">
          {t(KEY.application_deadline)}:
        </Text>
        <TimeDisplay timestamp={shown_application_deadline} displayType="nice-date" className={styles.timeDisplay} />
        {', '}
        <TimeDisplay timestamp={shown_application_deadline} displayType="time" className={styles.timeDisplay} />
      </Text>
      <Text size="m" as="p">
        <Text size="m" as="strong">
```

2024-07-30 22:08 UTC, robines commented on frontend/src/Pages/RecruitmentPage/Components/NoPositions/NoPositions.tsx
> +        </p>
Instead of using `<br>` tags like this, wrap each use of `useTextItem` in its own `<p>`

2024-07-30 22:08 UTC, robines commented on frontend/src/Pages/OrganizationRecruitmentPage/OrganizationRecruitmentPage.tsx
> +            <Text as={'strong'} size={isDesktop ? 'xl' : 'l'}>
```suggestion
            <Logo organization={organizationName} color="light" size={isDesktop ? 'small' : 'xsmall'} />
            <Text as="strong" size={isDesktop ? 'xl' : 'l'}>
```

2024-07-30 22:08 UTC, robines commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/PositionsTable/PositionsTable.tsx
> +        <Text as={'strong'} size={'l'}>
```suggestion
        <Text as="strong" size="l">
```

2024-07-30 22:08 UTC, robines commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/PositionsTable/PositionsTable.tsx
> +          <Text as={'p'} size={'m'}>
```suggestion
          <Text as="p" size="m">
```

2024-07-30 22:08 UTC, robines commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/GangsTabs/GangsTabs.tsx
> +        <Text as={'strong'} size={'l'}>
```suggestion
        <Text as="strong" size="l">
```

2024-07-30 22:10 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/Components/NoPositions/NoPositions.tsx
> +        </p>
Har issue på å endre denne, så vil helst la den være for nå. Var ikke jeg som lagde den, jeg bare flytta den ut.

2024-07-30 22:11 UTC, robines commented on frontend/src/Pages/RecruitmentPage/Components/NoPositions/NoPositions.tsx
> +        </p>
Den er good

2024-07-30 22:17 UTC, robines commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/GangPositionDropdown/GangPositionDropdown.module.scss
> -  color: white;
Hvorfor ble denne fjernet? Føler det ser bedre ut med hvit skrift?

![image](https://github.com/user-attachments/assets/8831f63f-51d9-4c8e-9bb8-333e546627c2) ![image](https://github.com/user-attachments/assets/21f7a6a0-06b6-4a70-bf65-d55adf0290d9)

2024-07-30 22:20 UTC, Snorre98 commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/GangPositionDropdown/GangPositionDropdown.module.scss
> -  color: white;
Ah, jeg trodde det ikke gjorde noe. Legge det tilbake.

2024-07-30 22:24 UTC, Snorre98 commented on frontend/src/Pages/OrganizationRecruitmentPage/Components/GangPositionDropdown/GangPositionDropdown.module.scss
> -  color: white;
done

2024-07-30 22:33 UTC, robines approved these changes

2024-07-30 22:35 UTC, merged