Rough draft recruitment overview page
Samfundet/Samfundet4 pull request #1123
Opened 2024-05-12 08:13 UTC by Snorre98

# Recruitment progression
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/e1d11916-b2c2-48ea-b7a5-c94c54810be9)

## Recruitment progression - all processed:
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/d08ef687-176b-4a11-ab36-9d7fbb95bb92)

# Recruitment statistics page (no chart components)
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/801e1875-c0e4-4b1d-86c4-506234627640)

2024-06-07 20:24 UTC, magsyg approved these changes
Alt ser ganske aight ut, og godt til å bygges på
Godkjenner, men lag først issues på å ha backendendepunkter og dtos for dataen som vises.

2024-06-07 20:24 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangOverviewPage/RecruitmentGangOverviewPage.tsx
> +      <Button theme="success" rounded={true} link={ROUTES.frontend.admin_recruitment_overview}>
Bør nok begrense dette her, tenker vell ikke en vanlig opptaksansvarlig for redaksjonen skal kunne se hvor mange som har søkt totalt dette opptaket

2024-06-07 20:24 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentProgression/RecruitmentProgression.tsx
> +  const [tableRows, setTableRowsState] = useState<TableRow[]>([]);
Godt mulig og kanskje lurere å omgjøre hele denne til sin egen Dto?

2024-06-07 20:24 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentProgression/RecruitmentProgression.tsx
> +    const totalRejected = mock_fetched_data.reduce((sum, current) => sum + current.rejected, 0);
Uansett om mock, lag issue og bør gjøres i backend

2024-06-07 20:24 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentProgression/RecruitmentProgression.tsx
> +  const setTableRows = () => {
Ya mulig alt av logic gjøres i backend her

2024-06-07 20:24 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentStatistics/RecruitmentStatistics.tsx
> +  const statisticsViews = () => {
mulig move til et subcomponent

2024-06-07 20:24 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/RecruitmentOverviewPage.tsx
> +    { key: 2, label: t(KEY.recruitment_statistics), value: <RecruitmentStatistics /> },
hmmm tabsystem kan være kult her

2024-06-11 16:30 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentGangOverviewPage/RecruitmentGangOverviewPage.tsx
> +      <Button theme="success" rounded={true} link={ROUTES.frontend.admin_recruitment_overview}>
Jaja, men det ligger jo utenfor scoep for dette issuet.

2024-06-11 16:31 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/RecruitmentOverviewPage.tsx
> +    { key: 2, label: t(KEY.recruitment_statistics), value: <RecruitmentStatistics /> },
Hva mener du? Det er jo et tab system

2024-06-11 16:35 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangOverviewPage/RecruitmentGangOverviewPage.tsx
> +      <Button theme="success" rounded={true} link={ROUTES.frontend.admin_recruitment_overview}>
Er det issue på det?

2024-06-11 16:43 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentGangOverviewPage/RecruitmentGangOverviewPage.tsx
> +      <Button theme="success" rounded={true} link={ROUTES.frontend.admin_recruitment_overview}>
Nei, kan lage. Men jeg ser for meg det blir et overordet permission issue på et eller annet tidspunkt.

2024-06-11 17:18 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentGangOverviewPage/RecruitmentGangOverviewPage.tsx
> +      <Button theme="success" rounded={true} link={ROUTES.frontend.admin_recruitment_overview}>
Har fiksa nå

2024-06-11 18:00 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentProgression/RecruitmentProgression.tsx
> +    const totalRejected = mock_fetched_data.reduce((sum, current) => sum + current.rejected, 0);
Har issue på det. Ligger til og med kommentert hvilket issue som skal løse det.

2024-06-11 18:21 UTC, hei98 approved these changes
Ser bra ut! Men kunne du lagt til en divider mellom disse i stedet for å ha de i to divs (to bokser)?
![image](https://github.com/Samfundet/Samfundet4/assets/144371674/eef8ef5c-b95e-4b98-8347-1ef270addc87)

2024-06-21 20:19 UTC, robines requested changes

2024-06-21 20:19 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangOverviewPage/RecruitmentGangOverviewPage.tsx
> +      <Button theme="success" rounded={true} link={ROUTES.frontend.admin_recruitment_overview}>
Må fylle recruitmentId i URLen.

```suggestion
      <Button
        theme="success"
        rounded={true}
        link={reverse({
          pattern: ROUTES.frontend.admin_recruitment_overview,
          urlParams: { recruitmentId },
        })}
      >
```

2024-06-21 20:19 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangOverviewPage/RecruitmentGangOverviewPage.tsx
>        <Button theme="blue" rounded={true} link={ROUTES.frontend.admin_recruitment_users_without_interview}>
Kan ta denne i samme slengen

```suggestion
      <Button
        theme="blue"
        rounded={true}
        link={reverse({
          pattern: ROUTES.frontend.admin_recruitment_users_without_interview,
          urlParams: { recruitmentId },
        })}
      >
```

2024-06-23 14:12 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentGangOverviewPage/RecruitmentGangOverviewPage.tsx
>        <Button theme="blue" rounded={true} link={ROUTES.frontend.admin_recruitment_users_without_interview}>
Did it

2024-06-23 14:12 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentGangOverviewPage/RecruitmentGangOverviewPage.tsx
> +      <Button theme="success" rounded={true} link={ROUTES.frontend.admin_recruitment_overview}>
Did it

2024-06-23 14:33 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentProgression/RecruitmentProgression.tsx
> +  const [tableRows, setTableRowsState] = useState<TableRow[]>([]);
Kan heller gjøre det i issue #1110. Tenker å implementere endepunkter osv. der

2024-06-23 14:34 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentProgression/RecruitmentProgression.tsx
> +  const setTableRows = () => {
Tenkte at det kan ligge for nå, så hente data i #1110 
Har lagt inn en del kommentarer i koden som refererer til det issuet

2024-06-23 14:37 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentStatistics/RecruitmentStatistics.tsx
> +  const statisticsViews = () => {
Tror det kommer til å bli gjort litt annerledes når det faktisk legges inn diagrammer her, så legger inn en kommentar, men tenker at det kan ligge til nå. Brukes mest for å demonstrere hvordan layout blir.

2024-06-23 14:39 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentProgression/RecruitmentProgression.tsx
> +    const totalRejected = mock_fetched_data.reduce((sum, current) => sum + current.rejected, 0);
Blir i #1110

2024-06-23 19:51 UTC, robines requested changes
Se kommentarer

2024-06-23 19:51 UTC, robines commented on frontend/src/i18n/translations.ts
> +  [KEY.common_has]: 'has',
Please remove all the unused translations. I feel like many of these will never end up being used, so while it is annoying to have to add translations for "basic" words you would have thought already existed, it's much better than having a bunch of unused code in my opinion.

2024-06-23 19:51 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentStatistics/RecruitmentStatistics.tsx
> +      <Text as={'strong'} size={'m'}>
```suggestion
      <Text as="strong" size="m">
```

2024-06-23 19:51 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentStatistics/RecruitmentStatistics.tsx
> +  }, []);
It's fine to use mock data for now, but unnecessary to call `setMockRecruitmentStatOne` with the same init data.

```suggestion
  // TODO: add dynamic data and might need backend features (in ISSUE #1110)
  const [mockRecruitmentStatOne, setMockRecruitmentStatOne] = useState([
    { at_date: '28-08-2024', recruitment_applications: 10 },
    { at_date: '25-08-2024', recruitment_applications: 2 },
  ]);
```

2024-06-23 20:32 UTC, Snorre98 commented on frontend/src/i18n/translations.ts
> +  [KEY.common_has]: 'has',
think I removed all unused which I added. Triple checked, should be good.

2024-06-23 20:32 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentStatistics/RecruitmentStatistics.tsx
> +      <Text as={'strong'} size={'m'}>
done

2024-06-23 20:32 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentStatistics/RecruitmentStatistics.tsx
> +  }, []);
done

2024-06-23 20:53 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/Components/RecruitmentStatistics/RecruitmentStatistics.tsx
> +  }, []);
satt mockRecruitmentStatOne som en const

2024-06-26 18:14 UTC, robines approved these changes

2024-06-26 18:45 UTC, merged