1125 implement permission system algorithm
Samfundet/Samfundet4 pull request #1126
Opened 2024-05-14 18:32 UTC by emsoraffa

see #1125 for info

2024-05-14 18:37 UTC, snorrekr commented on backend/root/utils/compute_permissions.py
> +            print()
Is this needed in prod?

2024-05-14 18:38 UTC, emilte commented on backend/root/utils/permission_algorithm.py
wow, hva skjer nå?

2024-05-14 18:42 UTC, tiniuspre requested changes

2024-05-14 18:42 UTC, tiniuspre commented on backend/root/utils/compute_permissions.py
> +                    print('%7d\t' % (1), end=' ')
Ikke bruk print, om du MÅ ha noe "printa" bruk logging. https://docs.djangoproject.com/en/5.0/topics/logging/ . Dette ville vært isåfall ved debugging.

2024-05-14 18:42 UTC, tiniuspre commented on backend/root/utils/compute_permissions.py
> +            print()
print

2024-05-14 18:42 UTC, tiniuspre commented on backend/root/utils/compute_permissions.py
> +        print(permissions)
print

2024-05-14 18:42 UTC, tiniuspre commented on backend/root/utils/compute_permissions.py
> +                for j in range(self.V):
Gjerne bruk forklarende navn isteden for k, i, j

2024-05-14 18:42 UTC, tiniuspre commented on backend/root/utils/permission_algorithm.py
> +        return self.index_array
Bruk mer forklarende navn ikke dictionary, self.dict, k, v, osv

2024-05-14 18:46 UTC, emsoraffa commented on backend/root/utils/compute_permissions.py
> +                    print('%7d\t' % (1), end=' ')
Dette var en gammel fil, har slettet den.

2024-05-14 18:49 UTC, snorrekr commented on backend/root/utils/permission_algorithm.py
![UAxa8](https://github.com/Samfundet/Samfundet4/assets/54811445/fed82a3d-e3cd-491b-8d84-e2f9c4642a79)

2024-05-14 18:56 UTC, emsoraffa commented on backend/root/utils/permission_algorithm.py
> +        return self.index_array
vanskelig å gjøre det så mye mer forklarende. Kan kanskje revurdere navn på klassen, er egt bare en datastruktur som er et dictionary med "set" values og mulighet for indeksering.

2024-05-14 19:03 UTC, emsoraffa commented on backend/root/utils/permission_algorithm.py
_O(n^3)_

2024-05-14 19:11 UTC, emilte commented on backend/root/utils/permission_algorithm.py
Her må jeg dessverre inn som kritisk pang

2024-05-14 19:11 UTC, emilte commented on backend/root/utils/permission_algorithm.py
Hva er bakgrunnen til alt dette?

2024-05-14 19:24 UTC, Snorre98 commented on backend/root/utils/permission_algorithm.py
Formålet er tilganger i tre-struktur. Er noe vi har snakket om en stund nå.

2024-05-14 19:28 UTC, emilte commented on backend/root/utils/permission_algorithm.py
Django kommer med innebygget rollesystem. Hvorfor finne opp hjulet på nytt?

2024-05-14 19:50 UTC, emsoraffa commented on backend/root/utils/permission_algorithm.py
Var ikke med i å ta den avgjørelsen. Men det ble vurdert at Django sitt rollesystem var problematisk. @robines kan kanskje forklare bedre

2024-05-14 20:03 UTC, emilte commented on backend/root/utils/permission_algorithm.py
Hvorfor trenger dere trestruktur?

2024-05-14 20:25 UTC, emsoraffa commented on backend/root/utils/permission_algorithm.py
Hvis du ser på issuet har jeg laget en pdf som går litt mer i dybden. Vil være konstant tid lookup. Trestruktur er blant annet veldig enkelt å forholde seg til for de som skal administrere permissions siden Grupper vil arve tilganger til Grupper som ligger over i hierarkiet.

2024-05-14 20:29 UTC, tiniuspre commented on backend/root/utils/permission_algorithm.py
> +        return self.index_array
Docstrings da, noe som er litt mer forklarende over hva som skjer og hvorfor

2024-05-14 20:35 UTC, tiniuspre commented on backend/root/utils/permission_algorithm.py
Er så vi hovedsakelig skal få enda mer kontroll over arvesystem, også ha flere "lag" med arving

2024-05-14 20:59 UTC, emilte commented on backend/root/utils/permission_algorithm.py
Har dere jobbet flere sammen om dette?

2024-05-14 21:08 UTC, emsoraffa commented on backend/root/utils/permission_algorithm.py
Har hatt felles diskusjoner

2024-05-14 21:17 UTC, emilte commented on backend/root/utils/permission_algorithm.py
Beklager, er ikke meningen å være kjip. Jeg virker strengere over tekst enn det som er meningen, er vanskelig å unngå. Det er sikkert en kul algoritme Emil, har ikke satt meg så dypt inn i koden ennå. Jeg frykter bare at dette er et villspor. Ved første øyeblikk virker det ikke lesbart eller intuitivt. Hvor lenge har dere jobbet med dette? Mathias startet på dette i fjor, men ser det er gjort en helomvending jeg ikke helt har fått med meg. Tror det hadde vært lurt å ta med meg i loopen her tidligere. Jeg har tilfeldigvis jobbet masse med rollesystem det siste året. Å gå helt offroad med noe som ikke er kompatibelt med Django har svært stor risiko for komplikasjoner senere, og jeg tror ikke vi klarer å tenke ut alt som kan skje. Jeg er usikker på hvordan dette skalerer på sikt. Men jeg trenger å forstå mer om hvordan dere har kommet frem til denne løsningen først. Jeg forstår ikke per nå helt hvordan dette kobles opp mot brukersystem og hvordan det skal være dynamisk og fleksibelt. Har dere lest Django sin dokumentasjon om Backends? Systemet deres kan faktisk modifiseres ganske mye etter behov. Vi bør ha svært gode grunner til å divergere i en såpass kritisk del av koden, og trestruktur-behovet trenger jeg mer innsikt i. Har dere en konkret use-case dere kan beskrive for meg? Kanskje finnes det løsninger der arv kan unngås 🙂

2024-05-14 21:21 UTC, emilte commented on backend/root/utils/permission_algorithm.py
Det kan også hende at jeg har misforstått noe her.

2024-05-14 21:26 UTC, emilte commented on backend/root/utils/permission_algorithm.py
Funker denne løsningen på tabell-nivå, kolonne-nivå, rad-nivå?

2024-05-14 21:40 UTC, emsoraffa commented on backend/root/utils/permission_algorithm.py
Har ikke mye erfaring med Django Groups så skal ikke uttale meg om hva som er eller ikke er mulig, den avgjørelsen ble tatt før jeg begynte å se på permissions. Tror dette heller burde diskuteres på arbeidskveld enn her. Som nevnt har jeg laget en pdf som forklarer mye bedre enn jeg får til her.

2024-05-14 21:55 UTC, emilte commented on backend/root/utils/permission_algorithm.py
Er nok lurere det ja.

2024-07-15 17:52 UTC, robines commented
@emsoraffa @aTrueYety Jeg og @emilte har fått snakket en del om dette med roller og permissions i Django, og vi kom frem til at det sannsynligvis vil være best å bare bygge på auth-systemet til Django, og droppe inheritance. Det vil forhåpentligvis være et mye enklere system å forstå, samt være et system som allerede er tilpasset Django. Det er kjipt at jeg ikke fant ut av det før dere begynte på dette, så beklager for det.

Har implementert dette i #1257, med noen eksempler på bruk også.

2024-07-15 17:52 UTC, closed without merging