689 custom stylization for admission organisations
Samfundet/Samfundet4 pull request #1127
Opened 2024-05-16 14:05 UTC by Snorre98

:wave: this PR does alot of the same as #1119, this is because I saw the need for splitting up. The overlapping functionality will be removed from #1119 and implemented from this when it is merged.

This PR aims to create custom styling to differentiate organizations recruiting through Samf. The issue stated that navbar and footer should should be stylized to reflect which organization is recruiting. I feel this is not necessary if we use logo components and headers like displayed in the image bellow. 
This PR adds a modular Logo component, with preset style configurations, which as of now can render Samfundet, ISFiT and UKA logo.

There is also added a context provider which can be used over pages where we want to differentiate organization style. It contains preset colors, organization name "formatted" correctly and button theme. From this I believe we will be able to sufficiently stylize based on organization without having to add this to the global context (which I feel is overkill). 
The style can be changed by taking the organization name as input, which might come from URL params or from data in API response.

There is a simple example in RecruitmentPage, but this does not reflect the actual organization which is recruiting on the page. It is only for demo purpose. I am not entirely set on the colors used in the color style of the different organizations, but this can be changed easily in the future.

![image](https://github.com/Samfundet/Samfundet4/assets/112980079/accb49b5-7645-45bf-a11c-f3367c1eeeb5)

2024-05-16 14:20 UTC, Snorre98 commented on frontend/src/AppRoutes.tsx
> +            <OrganizationContextProvider>
Will remove before merge. Only for demo of functionality.

2024-05-16 14:20 UTC, Snorre98 commented on frontend/src/Components/Logo/Logo.tsx
> +export type LogoProps = {
Logo might be used outside of OrgContext, so I did not include it in the context provider.

2024-05-16 14:20 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.module.scss
> +.orgHeader{
Only for demo purpose, will remove before merge.

2024-05-16 14:20 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
> +  const { organizationTheme, changeOrgTheme } = useOrganizationContext();
All changes here only for demo purpose. Will remove before merge.

2024-05-29 15:13 UTC, magsyg requested changes
Tror du bør flytte ut selve logoene ut til sine egne SVG filer og ikke tsx, og deretter laste de inn

Utenom det ser det nice ut

2024-06-10 04:41 UTC, Snorre98 commented
> Tror du bør flytte ut selve logoene ut til sine egne SVG filer og ikke tsx, og deretter laste de inn
> 
> Utenom det ser det nice ut

Sikker? Jeg prøvde nå, men ble ganske komplekst å kontrollere stilen. Vi har en annen Samf logo komponent hvor SVG elementet ligger i TSX filen, på samme måte som jeg har gjort her.

2024-06-13 20:33 UTC, hei98 commented
Når jeg går inn på siden for recruitment ved å trykke på opptak knappen i navbaren ser siden slik ut;
![image](https://github.com/Samfundet/Samfundet4/assets/144371674/7fc25fd8-2b05-4117-83d0-74b5c33d543f)
Men når jeg refresher siden eller trykker på enkelte av knappene i navbaren skifter den farge slik:
![image](https://github.com/Samfundet/Samfundet4/assets/144371674/154d8ab9-5e8b-4060-b47d-24aff19047b5)
Antar det ikke skal skje?

2024-06-22 17:08 UTC, robines requested changes

2024-06-22 17:08 UTC, robines commented on frontend/src/Components/Logo/components/SamfLogo.tsx
> +export function SamfLogo({ color, size }: SamfLogoProps) {
Foretrekker fullt navn: SamfundetLogo

2024-06-22 17:08 UTC, robines commented on frontend/src/Components/Logo/components/UkaLogo.tsx
> +type UkaLogoProps = {
```suggestion
type Props = {
```

2024-06-22 17:08 UTC, robines commented on frontend/src/Components/Logo/components/UkaLogo.tsx
> +export function UkaLogo({ color, size }: UkaLogoProps) {
Foretrekker å bruke riktig bokstavstørrelse her, så det blir UKA og ikke Uka.

```suggestion
export function UKALogo({ color, size }: Props) {
```

2024-06-22 17:08 UTC, robines commented on frontend/src/types.ts
> +  SAMF: 'samfundet',
Foretrekker å bruke fullt navn: `SAMFUNDET`

2024-06-22 17:20 UTC, robines commented
> The issue stated that navbar and footer should should be stylized to reflect which organization is recruiting. I feel this is not necessary if we use logo components and headers like displayed in the image bellow.

Jeg er uenig. Det er et stort selling point for UKA og ISFiT at utseendet på opptakssystemet kan endres basert på organisasjonen. At navbaren endres basert på organisasjon er noe som ble spesifikt nevnt. Det trenger ikke være noe veldig avansert, i første omgang er det mer enn nok å ha en fargelagt navbar med kun logo til organisasjonen og ingenting annet.

Foretrekker uansett at dette blir gjort i en annen PR.

2024-06-23 16:03 UTC, Snorre98 commented on frontend/src/Components/Logo/components/UkaLogo.tsx
> +type UkaLogoProps = {
Nei

2024-06-23 16:05 UTC, Snorre98 commented on frontend/src/Components/Logo/components/SamfLogo.tsx
> +export function SamfLogo({ color, size }: SamfLogoProps) {
Done

2024-06-23 16:20 UTC, Snorre98 commented on frontend/src/types.ts
> +  SAMF: 'samfundet',
done

2024-06-23 18:59 UTC, Snorre98 commented
> > The issue stated that navbar and footer should should be stylized to reflect which organization is recruiting. I feel this is not necessary if we use logo components and headers like displayed in the image bellow.
> 
> Jeg er uenig. Det er et stort selling point for UKA og ISFiT at utseendet på opptakssystemet kan endres basert på organisasjonen. At navbaren endres basert på organisasjon er noe som ble spesifikt nevnt. Det trenger ikke være noe veldig avansert, i første omgang er det mer enn nok å ha en fargelagt navbar med kun logo til organisasjonen og ingenting annet.
> 
> Foretrekker uansett at dette blir gjort i en annen PR.

Ok, har lagd issue på å videreutvikle organisasjon styling #1223

2024-06-23 19:34 UTC, robines requested changes

2024-06-23 19:34 UTC, robines commented on frontend/src/assets/isfit-logo.svg
> +<svg
Hva er vitsen med denne filen og `uka-logo.svg`? Ser ikke ut til at de brukes noe sted?

2024-06-23 19:36 UTC, Snorre98 commented on frontend/src/assets/isfit-logo.svg
> +<svg
La de inn i tilfelle man ønsker å bruke rene svg-er på et eller annet tidspunkt, men kan fjerne

2024-06-23 19:38 UTC, robines commented on frontend/src/assets/isfit-logo.svg
> +<svg
Skjønner. Det høres egentlig fint ut å ha, just in case. Så går fint å bare la de ligge

2024-06-23 19:39 UTC, robines approved these changes

2024-06-30 12:54 UTC, merged