1108 barchart component
Samfundet/Samfundet4 pull request #1132
Opened 2024-05-22 06:43 UTC by Snorre98

This became a big one 😶‍🌫️ In my defense; 12 of the files are below 10 lines and 17 of them below 50 lines. Most of this is types, constants or styling. **9** of the files contain the core functionality. 

#### What and why:
This PR creates PieChart, BarChart, and LineChart with a parent Chart component. This can be used to display recruitment statistics or stuff like "Kronerulling".

The PR contains a lot of added files because I have tried to make the components as modular as reasonable possible. What I have implemented can be used to create more chart types. 

‼️ I was not able to solve a type problem in Charts.tsx where TS is unable to recognize the categorized prop. TS gives a warning if for example cartesian chart props are used in a piechart, which is what I was aiming for, so I feel this works well enough.

‼️ For cartesian charts darkmode does not work in Storybook because the theme switching is being done with the useIsDarkeTheme-hook  in the TSX files, which apparently does not update in StoryBook.

#### Docs
The props of the Chart component is document in JDoc comments. 

#### [STORYBOOK LINK](http://localhost:6006/?path=/story/components-chart--applicants-per-day)

*The labels have been updated to stand at 45deg after I took the screenshots*
#### BarChart:

![image](https://github.com/Samfundet/Samfundet4/assets/112980079/7b4245c9-67ae-4ea1-b104-d145b51aa657)
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/5213996f-6d4b-4cd1-9715-e2e2937f4fcf)

#### LineChart:

![image](https://github.com/Samfundet/Samfundet4/assets/112980079/fc39de8f-b4ad-4f85-9dda-dafc98067ee9)
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/386861ea-3961-4e77-bb12-ea637a33f096)
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/6eb82a35-afe2-4c2a-9229-a661ebd05539)

#### PieChart

![image](https://github.com/Samfundet/Samfundet4/assets/112980079/19afff95-e6b1-4d73-ad9b-864ba958e33a)
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/4ebc599e-edbc-482a-bbd0-af119ab51eac)

2024-05-29 15:08 UTC, magsyg approved these changes
Sett gjennom ser aight ut, sikkert noe problemmer noe sted her, men de finner vi nok ut av det når dette brukes

2024-06-11 17:09 UTC, snorrekr commented on frontend/src/Components/Chart/CartesianCharts/BarChart/BarChart.tsx
> +  } = dimensions(sizes, size, data); // function which hold/calculate dimensions or other needed values.
Can't this be outside the function?

2024-06-11 17:12 UTC, snorrekr commented on frontend/src/Components/Chart/CartesianCharts/BarChart/index.ts
> +export { BarChart } from './BarChart';
Nice!

2024-06-11 17:34 UTC, snorrekr commented on frontend/src/Components/Chart/CartesianCharts/BarChart/BarChart.tsx
> +  isDarkMode ? (colors = lineChartPalette.dark) : (colors = lineChartPalette.light);
Can be moved out

2024-06-11 17:35 UTC, snorrekr commented on frontend/src/Components/Chart/CartesianCharts/LineChart/LineChart.tsx
> +  isDarkMode ? (colors = lineChartPalette.dark) : (colors = lineChartPalette.light);
Same here

2024-06-11 17:55 UTC, snorrekr commented on frontend/src/Components/Chart/CartesianCharts/utils/dimensions.ts
> +  const maxValue = Math.max(...data.map((item) => item.value));
Cant you use reducer

2024-06-11 17:58 UTC, snorrekr commented on frontend/src/Components/Chart/CartesianCharts/utils/dimensions.ts
> +  const maxValue = Math.max(...data.map((item) => item.value));
`data.reduce((acc, curr) => acc + curr.value, 0);`

2024-06-11 18:04 UTC, snorrekr commented on frontend/src/Components/Chart/CartesianCharts/utils/draw-labels.tsx
> +        {splitYLabel ? value.toFixed(0).toString().slice(splitYLabel[0], splitYLabel[1]) : value.toFixed(0)}
Maybe a comment explaining

2024-06-11 18:09 UTC, snorrekr commented on frontend/src/Components/Chart/CartesianCharts/utils/draw-labels.tsx
> +        >
Nice

2024-06-11 18:11 UTC, snorrekr commented on frontend/src/Components/Chart/Chart.tsx
> + * */
:vomiting_face:

2024-06-11 18:13 UTC, snorrekr commented on frontend/src/Components/Chart/CircularCharts/PieChart/PieChart.tsx
> +  const viewboxSize = radius * 2;
Move outside

2024-06-11 18:19 UTC, snorrekr approved these changes
nice, some comments added.
I think its fine to add instead of a library. While a library can achieve the same as the PR, with more functionality, this PR is implemented so why waste time implementing another solution. Additionally we dont have many charts available to the public, if that becomes a major requirment it can be added then.

2024-06-16 13:35 UTC, robines requested changes

2024-06-16 13:35 UTC, robines commented on frontend/src/Components/Chart/CartesianCharts/CartesianCharts.module.scss
> +  rotate: -90deg;
Ser ut til at teksten clippes av roteringen
![image](https://github.com/Samfundet/Samfundet4/assets/16273164/83d0ea3a-37a4-4444-9a0d-a726d239d6f3)

2024-06-16 13:35 UTC, robines commented on frontend/src/Components/Chart/CartesianCharts/BarChart/index.ts
> +export { BarChart } from './BarChart';
@snorrekr resolve? 🤡

2024-06-16 13:45 UTC, Snorre98 commented on frontend/src/Components/Chart/CartesianCharts/CartesianCharts.module.scss
> +  rotate: -90deg;
Ye, har funksjonalitet for å kontrollere lengden på label stringen, men kan se på å utvide svg-en dynamisk

2024-06-16 14:00 UTC, robines requested changes

2024-06-16 14:00 UTC, robines commented on frontend/src/Components/Chart/CartesianCharts/utils/types.ts
> +  cHeight: number;
Her må hjernen jobbe ekstra for å skjønne hva `c` er. Syns det er mye tydeligere å bare ha `width`/`height`

```suggestion
  width: number;
  height: number;
```

2024-06-16 14:00 UTC, robines commented on frontend/src/Components/Chart/CartesianCharts/utils/types.ts
> +  text: string;
Syns det er tydeligere med dette

```suggestion
  background: string;
  foreground: string;
```

2024-06-16 14:00 UTC, robines commented on frontend/src/Components/Chart/Chart.tsx
> +export function Chart({
Jeg skjønner ikke helt vitsen med denne komponenten, den virker bare overflødig? Mye tydeligere å bruke enten `BarChart` eller `LineChart` direkte i koden.

2024-06-16 14:00 UTC, robines commented on frontend/src/Components/Chart/CartesianCharts/BarChart/BarChart.tsx
> +  isDarkMode ? (colors = lineChartPalette.dark) : (colors = lineChartPalette.light);
Ikke ha assignments i ternary expressions, det er megaforvirrende

2024-06-16 14:00 UTC, robines commented on frontend/src/Components/Chart/CartesianCharts/BarChart/BarChart.tsx
> +  isDarkMode ? (colors = lineChartPalette.dark) : (colors = lineChartPalette.light);
```suggestion
  const colors = isDarkMode ? palette.dark : palette.light;
```

2024-06-16 14:00 UTC, robines commented on frontend/src/Components/Chart/CartesianCharts/utils/dimensions.ts
> +const getDatapointPadding = (entryCount: number) => (entryCount > 80 ? 1 : 2);
```suggestion
function getDatapointPadding(entryCount: number) {
  return entryCount > 80 ? 1 : 2;
}
```

2024-06-16 14:00 UTC, robines commented on frontend/src/Components/Chart/CartesianCharts/utils/dimensions.ts
> +) => {
```suggestion
function calculateDimensions(
  sizes: CartesianChartSizes,
  size: CartesianChartProps['size'],
  data: CartesianChartsData[],
) {
```

2024-06-16 14:00 UTC, robines commented on frontend/src/_constants.scss
> +$salmon_light: #fab4ac;
Follow naming convention

```suggestion
$salmon-light: #fab4ac;
```

2024-06-17 19:14 UTC, Snorre98 commented on frontend/src/Components/Chart/CartesianCharts/LineChart/LineChart.tsx
> +  isDarkMode ? (colors = lineChartPalette.dark) : (colors = lineChartPalette.light);
Nei, kan ikke flytte ut. Bruker en hook.

2024-06-17 19:30 UTC, Snorre98 commented on frontend/src/Components/Chart/CartesianCharts/utils/draw-labels.tsx
> +        >
ok

2024-06-17 19:48 UTC, Snorre98 commented on frontend/src/Components/Chart/Chart.tsx
> + * */
Ok

2024-06-17 20:03 UTC, Snorre98 commented on frontend/src/Components/Chart/CircularCharts/PieChart/PieChart.tsx
> +  const viewboxSize = radius * 2;
Ok

2024-06-17 20:44 UTC, Snorre98 commented on frontend/src/Components/Chart/CartesianCharts/utils/dimensions.ts
> +const getDatapointPadding = (entryCount: number) => (entryCount > 80 ? 1 : 2);
ok

2024-06-17 20:44 UTC, Snorre98 commented on frontend/src/Components/Chart/CartesianCharts/utils/dimensions.ts
> +) => {
ok

2024-06-17 20:47 UTC, Snorre98 commented on frontend/src/Components/Chart/CartesianCharts/BarChart/BarChart.tsx
> +  isDarkMode ? (colors = lineChartPalette.dark) : (colors = lineChartPalette.light);
fixed

2024-06-17 20:48 UTC, Snorre98 commented on frontend/src/Components/Chart/Chart.tsx
> + * */
fixed

2024-06-17 20:48 UTC, Snorre98 commented on frontend/src/Components/Chart/CircularCharts/PieChart/PieChart.tsx
> +  const viewboxSize = radius * 2;
fixed

2024-06-17 20:48 UTC, Snorre98 commented on frontend/src/_constants.scss
> +$salmon_light: #fab4ac;
fixed

2024-06-17 20:48 UTC, Snorre98 commented on frontend/src/Components/Chart/CartesianCharts/utils/dimensions.ts
> +const getDatapointPadding = (entryCount: number) => (entryCount > 80 ? 1 : 2);
fix

2024-06-17 20:49 UTC, Snorre98 commented on frontend/src/Components/Chart/CartesianCharts/utils/dimensions.ts
> +) => {
fixed

2024-06-17 20:49 UTC, Snorre98 commented on frontend/src/Components/Chart/Chart.tsx
> +export function Chart({
nei

2024-06-18 17:46 UTC, snorrekr commented on frontend/src/Components/Chart/CartesianCharts/BarChart/BarChart.tsx
> +  isDarkMode ? (colors = lineChartPalette.dark) : (colors = lineChartPalette.light);
Mer som ut av funksjoner.

2024-06-18 18:35 UTC, Snorre98 commented on frontend/src/Components/Chart/Chart.tsx
> +export function Chart({
@robines er PR-en good nå eller er det er dette dealbreaker for deg?

2024-06-21 20:23 UTC, robines commented on frontend/src/Components/Chart/Chart.tsx
> +export function Chart({
@Snorre98 Ikke dealbreaker, selv om jeg fremdeles ikke ser poenget.

2024-06-21 20:23 UTC, robines approved these changes

2024-06-23 13:08 UTC, merged