add csv downloader of recruitmentdata for gang
Samfundet/Samfundet4 pull request #1161
Opened 2024-06-08 17:33 UTC by magsyg

closes #1111

2024-06-22 14:53 UTC, robines requested changes
Veldig fint! Bare noen små ønsker til endringer bare

2024-06-22 14:53 UTC, robines commented on backend/samfundet/views.py
> +                'intervjuer_satt',
```suggestion
                'Navn',
                'Telefon',
                'Epost',
                'Campus',
                'Stilling',
                'Intervjutid',
                'Intervjusted',
                'Prioritet',
                'Status',
                'Søkers rangering',
                'Intervjuer satt',
```

2024-06-22 14:53 UTC, robines commented on backend/samfundet/views.py
> +                    'intervjuer_satt': f'{admission.get_total_interviews()}/{admission.get_total_admissions()}',
```suggestion
                    'Navn': admission.user.get_full_name(),
                    'Telefon': admission.user.phone_number,
                    'Epost': admission.user.email,
                    'Campus': admission.user.campus.name_en if admission.user.campus else '',
                    'Stilling': admission.recruitment_position.name_nb,
                    'Intervjutid': admission.interview.interview_time if admission.interview else '',
                    'Intervjusted': admission.interview.interview_location if admission.interview else '',
                    'Prioritet': admission.get_recruiter_priority_display(),
                    'Status': admission.get_recruiter_status_display(),
                    'Søkers rangering': f'{admission.applicant_priority}/{admission.get_total_admissions()}',
                    'Intervjuer satt': f'{admission.get_total_interviews()}/{admission.get_total_admissions()}',
```

2024-06-22 14:53 UTC, robines commented on backend/samfundet/views.py
> +            headers={'Content-Disposition': 'attachment; filename="somefilename.csv"'},
Og importer datetime

```suggestion
        filename = f"opptak_{gang.name_nb}_{datetime.now().strftime('%Y-%m-%d %H:%M')}.csv"
        response = HttpResponse(
            content_type='text/csv',
            headers={'Content-Disposition': f'Attachment; filename="{filename}"'},
```

2024-06-23 17:22 UTC, magsyg commented on backend/samfundet/views.py
> +                'intervjuer_satt',
Done

2024-06-23 17:23 UTC, magsyg commented on backend/samfundet/views.py
> +                    'intervjuer_satt': f'{admission.get_total_interviews()}/{admission.get_total_admissions()}',
done

2024-06-23 17:31 UTC, magsyg commented on backend/samfundet/views.py
> +            headers={'Content-Disposition': 'attachment; filename="somefilename.csv"'},
Done

2024-06-23 17:38 UTC, robines approved these changes
Nice!

2024-06-23 17:41 UTC, merged