Feature/createinterviewmodal
Samfundet/Samfundet4 pull request #1174
Opened 2024-06-09 11:46 UTC by magsyg

Created an interview modal to handle the dual datatypes and specifics when setting interview
May need to be updated later, with thoughts of design and additiona fields

![bilde](https://github.com/Samfundet/Samfundet4/assets/56266980/327e7597-0eb6-4fc6-afa5-570e039edd01)

2024-06-26 18:41 UTC, robines requested changes

2024-06-26 18:41 UTC, robines commented on backend/samfundet/migrations/0015_alter_interview_interviewers.py
> +                null=True,
![image](https://github.com/Samfundet/Samfundet4/assets/16273164/fe74c1d5-0920-4568-bc05-ead00ae89e73)

2024-07-07 12:30 UTC, magsyg commented
Jo mer jeg går gjennom disse gamle PRene jo mer lei blir jeg av den renamingen, kanskje ikke lurt å komme med en repo stor renaming når man har over 10 PRer som er avhengig av de?

2024-07-07 18:45 UTC, magsyg commented on backend/samfundet/migrations/0015_alter_interview_interviewers.py
> +                null=True,
Done

2024-07-07 19:22 UTC, robines requested changes
Bare små renames

2024-07-07 19:22 UTC, robines commented on frontend/src/api.ts
> +      urlParams: { pk: admissionId },
```suggestion
      urlParams: { pk: applicationId },
```

2024-07-07 19:22 UTC, robines commented on frontend/src/api.ts
> +  admissionId: string,
```suggestion
  applicationId: string,
```

2024-07-07 19:22 UTC, robines commented on backend/samfundet/views.py
> +            return Response(admission_serializer.data, status=status.HTTP_201_CREATED)
```suggestion
    def put(self, request: Request, pk: str) -> Response:
        application = get_object_or_404(RecruitmentApplication, id=pk)
        data = request.data.dict() if isinstance(request.data, QueryDict) else request.data
        serializer = self.serializer_class(data=data)
        if serializer.is_valid():
            existing_interview = application.interview
            if existing_interview:
                existing_interview.interview_location = serializer.validated_data['interview_location']
                existing_interview.interview_time = serializer.validated_data['interview_time']
                existing_interview.save()
                application_serializer = RecruitmentApplicationForGangSerializer(RecruitmentApplication.objects.get(id=pk))
                return Response(application_serializer.data, status=status.HTTP_200_OK)

            new_interview = serializer.save()
            application.interview = new_interview
            application.save()
            application_serializer = RecruitmentApplicationForGangSerializer(RecruitmentApplication.objects.get(id=pk))
            return Response(application_serializer.data, status=status.HTTP_201_CREATED)
```

2024-07-08 17:35 UTC, magsyg commented on backend/samfundet/views.py
> +            return Response(admission_serializer.data, status=status.HTTP_201_CREATED)
Done

2024-07-08 17:35 UTC, magsyg commented on frontend/src/api.ts
> +  admissionId: string,
Done

2024-07-08 17:35 UTC, magsyg commented on frontend/src/api.ts
> +      urlParams: { pk: admissionId },
Done

2024-07-08 21:36 UTC, robines approved these changes

2024-07-09 05:04 UTC, merged