927 recruitment rejection email
Samfundet/Samfundet4 pull request #1184
Opened 2024-06-11 19:02 UTC by hei98

[#927](https://github.com/Samfundet/Samfundet4/issues/927)

2024-09-21 14:43 UTC, emilte commented on backend/root/utils/routes.py
> +samfundet__rejected_applicants = 'samfundet:rejected_applicants/'
?

2024-09-21 14:44 UTC, emilte commented on frontend/src/Components/RejectionMail/RejectionMail.tsx
> +import { useState } from 'react';
Prøv å del opp i mindre deler. Frontend og backend trenger ikke være samme branch

2024-09-24 18:35 UTC, emsoraffa commented on frontend/src/Components/RejectionMail/RejectionMail.tsx
> +import { useState } from 'react';
Godt innspill

2024-09-24 20:07 UTC, Snorre98 approved these changes

2024-09-24 20:07 UTC, Snorre98 commented on frontend/src/Components/RejectionMail/RejectionMail.tsx
> +      <label>Subject</label>
transaltions

2024-09-24 20:07 UTC, Snorre98 commented on frontend/src/Components/RejectionMail/RejectionMail.tsx
> +      <label>Email</label>
translations

2024-09-24 23:47 UTC, robines requested changes

2024-09-24 23:47 UTC, robines commented on backend/samfundet/views.py
> +            rejected_users = User.objects.filter(admissions__recruitment=recruitment, admissions__recuiter_status__ne=3)
Ville brukt `RecruitmentStatusChoices` her så unngår vi magic numbers, og hvis statusene endrer verdi kan det få store konsekvenser her.

2024-09-24 23:47 UTC, robines commented on backend/samfundet/views.py
> +class SendRejectionMailView(APIView):
Trenger tester her så vi er sikre på at logikken er riktig. I det minste må tilfellene under testes. Opp til deg nøyaktig hvordan de skrives da, siden tilfellene sikkert overlapper litt så da kan man sikkert slå to fluer i en smekk hvis man skriver testene riktig.

Disse *skal* få rejection mail:
* En søker har søkt en eller flere stillinger, og ikke fått tilbud på noen
* En søker med én trekt søknad, og én søknad uten tilbud

Disse skal *ikke* få rejection mail:
* En søker med "Tilbud, takket ja" på en (eller flere) av søknadene sine.
* En søker med "Tilbud, takket nei" på en (eller flere) av søknadene sine.
* En søker med kun trekte søknader, uavhengig av status på disse
* En søker uten noen søknader

Kan være nyttig å grave litt i [Samf3 rejection mail-koden](https://github.com/Samfundet/Samfundet/blob/master/app/controllers/admissions_admin/admissions_controller.rb#L247) for å se hvordan det er løst der.

2024-09-25 07:14 UTC, Snorre98 commented on frontend/src/Components/RejectionMail/RejectionMail.tsx
> +      <label>Subject</label>
Bare å resolve disse når det er fikset.

2024-09-25 07:14 UTC, Snorre98 commented on frontend/src/Components/RejectionMail/RejectionMail.tsx
> +      <label>Email</label>
Bare å resolve disse når det er fikset.

2024-10-01 17:55 UTC, emsoraffa commented on backend/samfundet/views.py
> +            rejected_users = User.objects.filter(admissions__recruitment=recruitment, admissions__recuiter_status__ne=3)
Dette skal være i orden nå.

2024-10-01 20:25 UTC, emsoraffa commented on backend/samfundet/views.py
> +class SendRejectionMailView(APIView):
Logikken skal være good nå. Opretta nytt issue og assigna meg selv for tester #1505

2024-10-03 18:38 UTC, merged