add all applicants for gang page
Samfundet/Samfundet4 pull request #1188
Opened 2024-06-13 12:13 UTC by magsyg

Does more or less the same as in samf3, show alls admissions for a gang
The other todos mentioned here are already done in other PRs

![bilde](https://github.com/Samfundet/Samfundet4/assets/56266980/6b8da658-6577-4a99-a718-39753065c931)

2024-06-22 22:17 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +      <Button theme="outlined" display="pill" onClick={() => alert('TODO add export to csv')}>
Siden #1161 er straks klar til å merges, er det fint om du etter det kobler opp dette i samme slengen og

2024-06-26 21:48 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +      <Button theme="outlined" display="pill" onClick={() => alert('TODO add export to csv')}>
Gjort nå, men ser ut som det er vanskelig å få med filnavnet som er gitt i backend, siden denne headeren er av en eller annen grunn ikke synlig gjennom axios. 
Er muligheter, men da må vi configurere axios og det har vi ikke gjort ennå så er ute av scopet her

2024-06-26 21:51 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +      <Button theme="outlined" display="pill" onClick={() => alert('TODO add export to csv')}>
#1238

2024-06-26 22:09 UTC, magsyg commented
Skjønner ikke erroren som kommer, funker for meg, filen eksisterer @robines

2024-07-07 18:36 UTC, robines requested changes
Må nok merge fra master for at mine foreslåtte endringer (admission -> application) skal bli gyldige

2024-07-07 18:36 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAdminPage/RecruitmentGangAdminPage.tsx
> +          pattern: ROUTES.frontend.admin_recruitment_gang_all_admissions,
```suggestion
          pattern: ROUTES.frontend.admin_recruitment_gang_all_applications,
```

2024-07-07 18:36 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +  const [admissions, setAdmissions] = useState<RecruitmentApplicationDto[]>([]);
```suggestion
  const [applications, setApplications] = useState<RecruitmentApplicationDto[]>([]);
```

2024-07-07 18:36 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +          setAdmissions(response.data);
```suggestion
          setApplications(response.data);
```

2024-07-07 18:36 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +    });
```suggestion
  const data = applications.map((application) => {
    const applicationURL = reverse({
      pattern: ROUTES.frontend.admin_recruitment_applicant,
      urlParams: {
        applicationID: application.id,
      },
    });
```

2024-07-07 18:36 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +            {admission.user.first_name} {admission.user.last_name}
```suggestion
          <Link url={applicationURL}>
            {application.user.first_name} {application.user.last_name}
```

2024-07-07 18:36 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +      admission.recruiter_status,
```suggestion
      application.user.email,
      application.user?.phone_number,
      { content: <Link url={applicationURL}>{dbT(application.recruitment_position, 'name')}</Link> },
      application.interview?.interview_time,
      application.interview?.interview_location,
      application.recruiter_status,
```

2024-07-07 18:36 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +  const title = t(KEY.recruitment_all_admissions);
```suggestion
  const title = t(KEY.recruitment_all_applications);
```

2024-07-07 18:36 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +      {admissions.length > 0 ? (
```suggestion
      {applications.length > 0 ? (
```

2024-07-07 18:36 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +        <Text>{t(KEY.recruitment_no_current_admissions_gang)}</Text>
```suggestion
        <Text>{t(KEY.recruitment_no_current_applications_gang)}</Text>
```

2024-07-07 18:36 UTC, robines commented on frontend/src/i18n/constants.ts
> +  recruitment_all_admissions: 'recruitment_all_admissions',
```suggestion
  recruitment_all_applications: 'recruitment_all_applications',
```

2024-07-07 18:36 UTC, robines commented on frontend/src/i18n/constants.ts
> +  recruitment_no_current_admissions_gang: 'recruitment_no_current_admissions_gang',
```suggestion
  recruitment_no_current_applications_position: 'recruitment_no_current_applications_position',
  recruitment_no_current_applications_gang: 'recruitment_no_current_applications_gang',
```

2024-07-07 18:36 UTC, robines commented on frontend/src/i18n/translations.ts
> +  [KEY.recruitment_all_admissions]: 'Alle søknader',
```suggestion
  [KEY.recruitment_all_applications]: 'Alle søknader',
```

2024-07-07 18:36 UTC, robines commented on frontend/src/i18n/translations.ts
> +  [KEY.recruitment_no_current_admissions_gang]: 'Denne gjengen har ennå ikke fått noen søknader',
```suggestion
  [KEY.recruitment_no_current_applications_position]: 'Denne stilling har ennå ikke fått noen søknader',
  [KEY.recruitment_no_current_applications_position]: 'Denne gjengen har ennå ikke fått noen søknader',
```

2024-07-07 18:36 UTC, robines commented on frontend/src/i18n/translations.ts
> +  [KEY.recruitment_all_admissions]: 'All admissions',
```suggestion
  [KEY.recruitment_all_applications]: 'All applications',
```

2024-07-07 18:36 UTC, robines commented on frontend/src/i18n/translations.ts
> +  [KEY.recruitment_no_current_admissions_gang]: 'This gang has no current applicants',
```suggestion
  [KEY.recruitment_no_current_applications_position]: 'This gang currently has no applicants',
  [KEY.recruitment_no_current_applications_gang]: 'This gang currently has no applicants',
```

2024-07-07 18:36 UTC, robines commented on frontend/src/router/router.tsx
> +            path={ROUTES.frontend.admin_recruitment_gang_all_admissions}
```suggestion
            path={ROUTES.frontend.admin_recruitment_gang_all_applications}
```

2024-07-07 18:36 UTC, robines commented on frontend/src/routes/frontend.ts
> +  admin_recruitment_gang_all_admissions: '/control-panel/recruitment/:recruitmentId/:gangId/all-admissions/',
```suggestion
  admin_recruitment_gang_all_applications: '/control-panel/recruitment/:recruitmentId/:gangId/all-applications/',
```

2024-07-07 18:43 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangAdminPage/RecruitmentGangAdminPage.tsx
> +          pattern: ROUTES.frontend.admin_recruitment_gang_all_admissions,
Done

2024-07-07 18:43 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +  const [admissions, setAdmissions] = useState<RecruitmentApplicationDto[]>([]);
Done

2024-07-07 18:43 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +          setAdmissions(response.data);
Done

2024-07-07 18:43 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +    });
Done

2024-07-07 18:43 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +            {admission.user.first_name} {admission.user.last_name}
Done

2024-07-07 19:28 UTC, robines requested changes

2024-07-07 19:28 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +      application.user?.phone_number,
Epost står under "Telefonnummer" atm, flip for å fikse

```suggestion
      application.user?.phone_number,
      application.user.email,
```

2024-07-08 17:40 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +      application.user?.phone_number,
Hmmm ja det var leit å se
Fikset opp i det nå

2024-07-08 20:09 UTC, robines requested changes

2024-07-08 20:09 UTC, robines commented on backend/samfundet/views.py
> +            headers={'Content-Disposition': f'Attachment; filename="{filename}"', 'lol': 'bloody cunt'},
Fjern? :D
```suggestion
            headers={'Content-Disposition': f'Attachment; filename="{filename}"'},
```

2024-07-23 18:06 UTC, magsyg commented on backend/samfundet/views.py
> +            headers={'Content-Disposition': f'Attachment; filename="{filename}"', 'lol': 'bloody cunt'},
done

2024-08-20 18:58 UTC, robines approved these changes

2024-08-20 19:00 UTC, merged