999 recruitment position tags
Samfundet/Samfundet4 pull request #1190
Opened 2024-06-14 04:55 UTC by Snorre98

This PR creates tag functionality for recruitment positions. It does not implement the tag functionality to suggest similar positions, but adds a view in backend (gets positions filtered on tags ) which can be used for this.
The PR also makes a small fix to serializing of positions which have a single interview for multiple positions. This functionality was not completely implemented in the RecruitmentPositionSerializer.

Assigning tags to recruitment positions through the recruitment position form is not implemented in this PR, but will be in #1189

:exclamation:  The RecruitmentPositionTag model is exactly the same as the Tag model (used for images). I thought it might be reasonable to have these in separate tables, which is why they are distinct models.

For further information I have commented as I reviewed the code my selfie.

Tags are set and created with a "TagSelect" component. This can be used with any "tag-like" system which have tag data matching the TagDto.

### "out-of-focus" TagSelect
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/82a14ecd-e346-43b2-aaa7-358ebd46ae84)

### "in-focus" TagSelect
Tag colors are randomly generated in backend. Tag text color is set by condition of the brightness of the tag color, which is calcualted in frontend.
If the tag has no color attribute the default color is an off-white color.
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/124ec031-a4b0-44a2-a354-adabe45851a0)

### TagSelect with search value (filter in frontend, but can gets options from backend)
If the search value does not match some excising tag exactly a "new" unregistered tag is represented as well. In this image the tag at the top of the list of tag options is a new tag. It obviously has no color attribute yet, as color is set in backend so it is off-white.
(plakat was created before automatic color generation, so it has no color attribute.)
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/fb690b0e-83d8-437e-b3b7-125278b4c287)

### TagSelect with search value matching exact excising tag
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/206ac07e-0820-4d7f-b659-1cee15956945)

### TagSelect with search value not matching any excising tag
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/41f403ad-d989-4b59-8c78-789a142a22a4)

### TagSelect with new tag selected ("Katt!")
![image](https://github.com/Samfundet/Samfundet4/assets/112980079/513b4aaf-7696-4019-aa69-244ff1efe124)

### TagSelect darkmode

![image](https://github.com/Samfundet/Samfundet4/assets/112980079/0d3224c2-dfb7-4ec8-9dd0-1a7e60b59a1d)

2024-06-14 05:17 UTC, Snorre98 commented on backend/samfundet/models/recruitment.py
> +            self.color = generate_random_hex_color()
genererer tilfeldig farge hvis det ikke er satt

2024-06-14 05:17 UTC, Snorre98 commented on backend/samfundet/models/recruitment.py
> +    tags = models.ManyToManyField(
Tags har en relasjon til RecruitmentPosition. En stilling kan ha flere tags. På denne måten kan vi filtrere stillinger basert på en eller flere tags i backend view.

2024-06-14 05:17 UTC, Snorre98 commented on backend/samfundet/models/utils/genrate_random_color.py
> +    random_number = random.randint(0, 0xFFFFFF)  # noqa: S311 --> weird crypto rule
noqa: S311 sier at randint ikke er trygt for kryptografi...

2024-06-14 05:17 UTC, Snorre98 commented on backend/samfundet/serializers.py
> +    # other positions with same interview, hence shared interview
oppdatering av stillinger med samme interview (grupperer stillingene i ett symmetrisk mange-til-mange forhold) er egentlig utefor scopet av dette issuet, men det var irriterend å jobbe at det ikke var implementert så jeg fikset det her. Ganske sikker på at det ikke eksisterte issue på det.

2024-06-14 05:17 UTC, Snorre98 commented on backend/samfundet/serializers.py
> +                    tag_obj = RecruitmentPositionTag.objects.get_or_create(name=tag["name"])[0]
oppdatere og/eller lager ny. Litt rar syntaks. Var enten dette eller å bruke en created variabel som aldri ble brukt

2024-06-14 05:17 UTC, Snorre98 commented on backend/samfundet/serializers.py
> +    def validate(self, attrs: dict) -> dict:
En av grunnene til at disse valideres her er fordi mange-til-mange felter ikke kan manipuleres direkte.

2024-06-14 05:17 UTC, Snorre98 commented on frontend/src/Components/ImagePicker/ImagePicker.tsx
> -        {/* TODO tags and other metadata */}
Skal legge denne tilbake

2024-06-14 05:17 UTC, Snorre98 commented on frontend/src/Components/TagSelect/TagSelect.module.scss
> +  /* Disable text select */
mer passende å skrive "disable text highlight"

2024-06-14 05:17 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +        console.log(response);
Skal fjerne

2024-06-14 05:17 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +  const [excitingTags, setExcitingTags] = useState<TagDto[]>([]); // tags which are associated with some position(s)
Kastet TagSelect komponenten inn her for demonstarsjon, men den kommer til å bli brukt her ved utførelse av #1189

2024-06-14 05:17 UTC, Snorre98 commented on frontend/src/routes/backend.ts
> -} as const;
:eyes:

2024-06-14 05:17 UTC, Snorre98 commented on frontend/src/utils.ts
> +  // Calculate brightness (YIQ formula)
På en "chat" ting

2024-06-14 05:17 UTC, Snorre98 commented on backend/samfundet/views.py
> +class RecruitmentPositionByTagView(ListAPIView):
For å hente stillinger med overlappende tags

2024-06-15 10:33 UTC, magsyg commented
Damn stor PR

2024-06-15 10:58 UTC, magsyg reviewed
Mer eller mindre, omgjør tagnavn til ID istedenfor UUID

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/models/recruitment.py
> +    name = models.CharField(max_length=100, help_text='Tags for the position')
Her kan nok navn og id bli det samme

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/models/recruitment.py
> +    gang = models.ForeignKey(to=Gang, on_delete=models.CASCADE, help_text='The gang that is recruiting', null=True, blank=True)
Hvorfor skal gang være null?
Dersom det blir bugs i posting, så heller sett det til blank, da ignorerer den at den ikke må bli lagt til under put

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/models/utils/genrate_random_color.py
> +    random_number = random.randint(0, 0xFFFFFF)  # noqa: S311 --> weird crypto rule
Du kan ikke ignorere ruff :,(

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/serializers.py
> +            raise ValidationError('Invalid tag name') from None
Dette bør nok puttes i selve modellen, gjennom custombase admin og custom base serializer, vil denne erroren bli passet til frontend dersom du gjør slik som i recruitment modellen

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/serializers.py
> +    # other positions with same interview, hence shared interview
Har bypasset dette ved å sette interview til å være null, bør virkelig rehaule hele intervjusystemet snart

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/serializers.py
> +    def validate(self, attrs: dict) -> dict:
Dette burde virkelig vært en annen PR

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/views.py
> +    def create(self, request: Request, *args: tuple, **kwargs: dict) -> Response:
er det dict og tuple som er riktig type her?

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/views.py
> +        tag, created = RecruitmentPositionTag.objects.get_or_create(name=data.get('name'))
Som sagt, gjør om navn om til pk, da vil dette valideres direkte i .is_valid()

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/views.py
> +                return Response({'message': 'Position not found'}, status=status.HTTP_404_NOT_FOUND)
Bruk get_or_404

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/views.py
> +            try:
Så viewet er for å lage tags, samtidig som man skal automatisk legge til dem til en position? 

Føler det burde være 2 views, eller muligens et apiview, med et urlparam av recruitment position. Siden tror ikke vi skal bare lage params uten posisjon?

2024-06-15 10:58 UTC, magsyg commented on backend/samfundet/views.py
> +        tag_ids = self.request.query_params.get('id', None)
Her burde det heller være på navn?

2024-06-15 10:58 UTC, magsyg commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +const FOUR_POINT_FIVE_REM = 4.5;
Hvorfor brukes denne konstanten?

2024-06-15 10:58 UTC, magsyg commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +          <div className={styles.unselectedContainer}>{filteredTagOptions().reverse()}</div>
Trenger ikke farge i selector, blir ganske jalla, men for pillsene så er det ganske nice.

2024-06-15 10:58 UTC, magsyg commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +        />
Nice å ha søk

2024-06-15 10:58 UTC, magsyg commented on frontend/src/api.ts
> +
Ikke noe create or put for tag?

2024-06-15 10:58 UTC, magsyg commented on frontend/src/utils.ts
> +  // Calculate brightness (YIQ formula)
Burde basere heller på HSV, enn RGB i dette tilfellete, tror skal være noen extensions for å transformere fra RGB til HSV, siden et av feltene baserer seg på lyshet

2024-06-20 21:05 UTC, Snorre98 commented on backend/samfundet/models/utils/genrate_random_color.py
> +    random_number = random.randint(0, 0xFFFFFF)  # noqa: S311 --> weird crypto rule
fixed, la til trygg random hex

2024-06-20 21:09 UTC, Snorre98 commented on frontend/src/Components/TagSelect/TagSelect.module.scss
> +  /* Disable text select */
fixed

2024-06-20 21:09 UTC, Snorre98 commented on frontend/src/Components/ImagePicker/ImagePicker.tsx
> -        {/* TODO tags and other metadata */}
fixed

2024-06-20 21:24 UTC, Snorre98 commented on backend/samfundet/models/recruitment.py
> +    gang = models.ForeignKey(to=Gang, on_delete=models.CASCADE, help_text='The gang that is recruiting', null=True, blank=True)
Ikke med vilje. Fixed

2024-06-20 21:27 UTC, Snorre98 commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +const FOUR_POINT_FIVE_REM = 4.5;
la inn kommentar i koden

2024-06-20 21:34 UTC, Snorre98 commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +        />
mhm

2024-06-20 22:26 UTC, Snorre98 commented on backend/samfundet/models/recruitment.py
> +    name = models.CharField(max_length=100, help_text='Tags for the position')
done

2024-06-21 06:59 UTC, Snorre98 commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +          <div className={styles.unselectedContainer}>{filteredTagOptions().reverse()}</div>
ok, fjernet farge for options

2024-06-23 09:53 UTC, robines requested changes

2024-06-23 09:53 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +  const [excitingTags, setExcitingTags] = useState<TagDto[]>([]); // tags which are associated with some position(s)
```suggestion
  const [existingTags, setExistingTags] = useState<TagDto[]>([]);
```

2024-06-23 09:53 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +        setExcitingTags(response.data);
```suggestion
        setExistingTags(response.data);
```

2024-06-23 09:53 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +              <TagSelect currentTagOptions={excitingTags} exportTags={setNewTags} />
```suggestion
              <TagSelect currentTagOptions={existingTags} exportTags={setNewTags} />
```

2024-06-23 09:53 UTC, robines commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +type TagSelectProps = {
```suggestion
type Props = {
```

2024-06-23 09:53 UTC, robines commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +export function TagSelect({ currentTagOptions, exportTags }: TagSelectProps) {
```suggestion
export function TagSelect({ currentTagOptions, exportTags }: Props) {
```

2024-06-23 09:53 UTC, robines commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +import styles from './TagSelect.module.scss';
På en eksisterende stilling får jeg dette:

<img width="568" alt="image" src="https://github.com/Samfundet/Samfundet4/assets/16273164/c127b0b0-d122-44e1-be0f-528ab6234fca">

2024-06-23 09:53 UTC, robines commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +  // tag representation
Unødvendig kommentar

```suggestion
```

2024-06-23 09:53 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +import { TagSelect } from '~/Components/TagSelect/TagSelect';
TagSelect mangler en barrel file (index.ts)

2024-06-30 18:23 UTC, Snorre98 commented on frontend/src/Components/TagSelect/TagSelect.tsx
> +  // tag representation
fixed

2024-06-30 18:23 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +import { TagSelect } from '~/Components/TagSelect/TagSelect';
fixed

2024-06-30 18:39 UTC, Snorre98 commented on backend/samfundet/views.py
> +            try:
Ja, dette viewet oppretter tags på en stilling samtidig som stillingen lages. Har RecruitmentPositionByTagView for å hente stillinger basert på tags.
Svarer det på spm?

2024-07-31 07:59 UTC, Snorre98 commented on backend/samfundet/views.py
> +                return Response({'message': 'Position not found'}, status=status.HTTP_404_NOT_FOUND)
done

2024-07-31 08:02 UTC, Snorre98 commented on backend/samfundet/serializers.py
> +            raise ValidationError('Invalid tag name') from None
fjernet den

2024-09-24 22:36 UTC, robines commented
@Snorre98 Status?

2025-03-02 03:10 UTC, closed without merging