add recruitmentgangdto
Samfundet/Samfundet4 pull request #1203
Opened 2024-06-17 15:01 UTC by magsyg

Discovered that on gang overview for recruitment, you could not see which gangs had positoions, added a new endpoint, serializr and dto to handle this.

Where it will fetch all gangs for recruitment, with appropriate positions

2024-06-18 18:32 UTC, snorrekr approved these changes

2024-07-07 17:58 UTC, robines requested changes

2024-07-07 17:58 UTC, robines commented on backend/samfundet/serializers.py
> +        return RecruitmentPositionForApplicantSerializer(positions, many=True).data
Mulig å kanskje endre dette til å kun vise count av positions? Virker som det er kun det som brukes nå og da blir det litt unødvendig å returnere alt

2024-07-07 18:29 UTC, magsyg commented on backend/samfundet/serializers.py
> +        return RecruitmentPositionForApplicantSerializer(positions, many=True).data
La til nå et annet bruksfelt, reduserer antall api kall nå

2024-07-08 21:35 UTC, robines commented on backend/samfundet/serializers.py
> +        return RecruitmentPositionForApplicantSerializer(positions, many=True).data
Jeg tenkte mer på å endre om slik at get_positions returnerer et tall istedenfor liste. RecruitmentGangOverviewPage bruker kun counten av recruitment_positions, så det er unødvendig å returnere en liste med alle stillingene. 

Jeg ser for meg at det kan være gunstig å splitte opp denne serializeren i to, slik at vi får `RecruitmentGangSerializer` og `RecruitmentGangsSerializer`, hvor den første returnerer alle stillingene som vanlig, mens den andre returnerer kun counten av stillingene.

Noe slikt:

```python
class RecruitmentGangsSerializer(CustomBaseSerializer):
    recruitment_positions = serializers.SerializerMethodField(method_name='get_positions_count', read_only=True)

    class Meta:
        model = Gang
        fields = '__all__'

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        # This will allow it to filter admissions on recruitment
        self.recruitment = kwargs.pop('recruitment', None)
        self.gang = kwargs.pop('gang', None)
        super().__init__(*args, **kwargs)

    def get_positions_count(self, obj: Gang) -> list[int]:
        """Return total number of positions for this gang's recruitment."""
        return RecruitmentPosition.objects.filter(recruitment=self.recruitment, gang=obj).count()
```

2024-07-10 22:28 UTC, robines commented
Superseded by #1264

2024-07-10 22:28 UTC, closed without merging