RecruitmentForRecruiterSerializer and recruitment_progress
Samfundet/Samfundet4 pull request #1214
Opened 2024-06-19 13:23 UTC by magsyg

Added a field to handle recruitment progress, and a serializer for fetching recruitment with extra data for recruiters

2024-06-20 17:11 UTC, Frenje123 commented
Can you please link this to an issue, or some details about what this pull request solves/adds to the solution?

2024-09-02 21:18 UTC, robines requested changes

2024-09-02 21:18 UTC, robines commented on backend/samfundet/serializers.py
> +    def get_interview_time(self, instance: Recruitment) -> float:
Feil navn?

```suggestion
    def get_recruitment_progress(self, instance: Recruitment) -> float:
```

2024-09-05 17:46 UTC, robines approved these changes

2024-09-05 17:48 UTC, merged

2024-09-05 17:48 UTC, Snorre98 approved these changes