use replace on 404 redirects
Samfundet/Samfundet4 pull request #1260
Opened 2024-07-07 16:12 UTC by magsyg

Entering a page that would enter a 404 would make going back not work, therefore added replace to all 404 locations

2024-07-07 18:11 UTC, robines requested changes

2024-07-07 18:11 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionOverviewPage/RecruitmentPositionOverviewPage.tsx
> +  }, [recruitmentId, gangId, positionId, navigate, t]);
`t` trenger ikke være i deplist

2024-07-07 18:11 UTC, robines commented on frontend/src/hooks.ts
> +      navigate(typeof url === 'number' ? url : finalUrl, { replace: replace });
```suggestion
      navigate(typeof url === 'number' ? url : finalUrl, { replace });
```

2024-07-07 18:30 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentPositionOverviewPage/RecruitmentPositionOverviewPage.tsx
> +  }, [recruitmentId, gangId, positionId, navigate, t]);
Nå har jeg fått besjed tidligere det var nødvendig, blir forvirret nå

2024-07-07 18:30 UTC, magsyg commented on frontend/src/hooks.ts
> +      navigate(typeof url === 'number' ? url : finalUrl, { replace: replace });
Funker sånt?

2024-07-07 19:14 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionOverviewPage/RecruitmentPositionOverviewPage.tsx
> +  }, [recruitmentId, gangId, positionId, navigate, t]);
Slik jeg har skjønt det er det ikke det. Men er ikke big deal, tror skjeldent det vil egentlig påvirke noe. Jeg resolver, trenger ikke gjøre noe

2024-07-07 19:15 UTC, robines commented on frontend/src/hooks.ts
> +      navigate(typeof url === 'number' ? url : finalUrl, { replace: replace });
Jepp, siden variabelnavnene er like er det en gyldig forkortning i JS

2024-07-08 17:43 UTC, magsyg commented on frontend/src/hooks.ts
> +      navigate(typeof url === 'number' ? url : finalUrl, { replace: replace });
oki done

2024-07-08 20:02 UTC, robines approved these changes

2024-07-11 19:26 UTC, Snorre98 commented
@magsyg denne kan merges

2024-07-13 08:12 UTC, merged