Find optimal interview slot
Samfundet/Samfundet4 pull request #1271
Opened 2024-07-22 11:22 UTC by Snorre98

# draft! A lot to come here
## finds "interview blocks" for positions
## gives each block a rating
## allocate  interviews to blocks with the highest rating first
- interview buffer for interviewers as well as a larger buffer for applicants
- might updated unavailability to reflect current interview time ?? Would help with re-generating or manually setting interview

Rating will be based on 1) the number of available interviewers in the block, 2) num. of available interviewers in the preceding and succeeding  blocks (if any), as well as 3) the time-length of the block.
Weighting of these factors will be important.

Still considering whether or not to represent blocks in db

Also, there might be some value to having a "manipulated availability" table in db to avoid computing updated unavailability every time

2024-09-29 21:51 UTC, robines requested changes

2024-09-29 21:51 UTC, robines commented on backend/samfundet/migrations/0004_merge_20240924_0058.py
> +# Generated by Django 5.1.1 on 2024-09-23 22:58
Slett fil

2024-09-29 21:51 UTC, robines commented on backend/samfundet/migrations/0006_merge_20240925_1842.py
> +# Generated by Django 5.1.1 on 2024-09-25 16:42
Slett fil

2024-09-29 21:51 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionOverviewPage/RecruitmentPositionOverviewPage.tsx
> +          console.log(data.data)
Fjern

2024-09-29 21:51 UTC, robines commented on backend/samfundet/views.py
> +        except Exception as e:
Ikke ha en catch all her, dette vil ødelegge fremtidig error handling/reporting, da vi ikke lar exceptionen boble opp.

2024-09-29 21:51 UTC, robines commented on backend/samfundet/migrations/0002_interviewtimeblock.py
> +# Generated by Django 5.0.7 on 2024-07-22 13:18
Vi kan sikkert snakke mer om det på arbeidskveld, men jeg syns det å ha "interview timeblock"-konseptet lagret i databasen blir unødvendig komplisert og at vi ikke får noe særlig for det. Vi kan fjerne det fullstendig og fortsatt ha intervjufordeling som fungerer.

2024-09-29 21:51 UTC, robines commented on backend/root/management/commands/seed_scripts/recruitment_position_interviewers.py
> +from __future__ import annotations
Dette seedscriptet er ikke helt relatert til resten av PRen, så kan være greit å kopiere det over til en ny PR? Så vil det nok kunne merges raskere enn denne PRen

2024-09-29 21:51 UTC, robines commented on backend/samfundet/utils.py
> +def mark_applicant_unavailable(applicant, start_dt, end_dt, buffer_hours=2):
Dette blir feil bruk av OccupiedTimeslot. Modellen er ment for brukerens egen utilgjengelighet uavhengig av opptaket. Systemet burde hente brukerens intervjuer automatisk istedenfor dette.

2024-10-01 17:53 UTC, Snorre98 commented on backend/root/management/commands/seed_scripts/recruitment_position_interviewers.py
> +from __future__ import annotations
done

2024-10-01 17:53 UTC, Snorre98 commented on backend/samfundet/utils.py
> +def mark_applicant_unavailable(applicant, start_dt, end_dt, buffer_hours=2):
ok

2024-10-01 17:54 UTC, Snorre98 commented on backend/samfundet/migrations/0002_interviewtimeblock.py
> +# Generated by Django 5.0.7 on 2024-07-22 13:18
kan finne en annen møte

2024-10-18 04:38 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentPositionOverviewPage/RecruitmentPositionOverviewPage.tsx
> +          console.log(data.data)
done

2024-10-18 04:38 UTC, Snorre98 commented on backend/samfundet/migrations/0002_interviewtimeblock.py
> +# Generated by Django 5.0.7 on 2024-07-22 13:18
done, bruker ikke en tabell for dette nå

2024-10-18 05:43 UTC, Snorre98 commented on backend/samfundet/utils.py
> +def mark_applicant_unavailable(applicant, start_dt, end_dt, buffer_hours=2):
henter intervjuer, så done

2024-10-18 16:10 UTC, emilte commented on backend/samfundet/automatic_interview_allocation/utils.py
> +def mark_interviewers_unavailable(interviewers: list[Any], start_dt: datetime, end_dt: datetime, unavailability: defaultdict[Any, list]) -> None:
list any?

2024-10-18 16:11 UTC, emilte commented on backend/samfundet/automatic_interview_allocation/allocate_interviews_for_position.py
> +def allocate_single_interview(current_time, block, applications, interviewer_unavailability, position, interview_duration):
typer?

2024-10-22 17:44 UTC, Snorre98 commented on backend/samfundet/migrations/0006_merge_20240925_1842.py
> +# Generated by Django 5.1.1 on 2024-09-25 16:42
dont

2024-10-22 18:15 UTC, Snorre98 commented on backend/samfundet/automatic_interview_allocation/utils.py
> +def mark_interviewers_unavailable(interviewers: list[Any], start_dt: datetime, end_dt: datetime, unavailability: defaultdict[Any, list]) -> None:
done?

2024-10-22 18:15 UTC, Snorre98 commented on backend/samfundet/automatic_interview_allocation/allocate_interviews_for_position.py
> +def allocate_single_interview(current_time, block, applications, interviewer_unavailability, position, interview_duration):
done

2024-10-22 18:15 UTC, Mathias-a reviewed
Hadde det ikke bare funket med en greedy algoritme?

2024-10-22 19:02 UTC, robines commented on backend/samfundet/automatic_interview_allocation/utils.py
> +UnavailabilityTypeDict = dict[UserIdType, list[TimeSlotType]]
Drop UserIdType and just add a comment

```suggestion
TimeSlotType = tuple[datetime, datetime]

# int is user Id
UnavailabilityTypeDict = dict[int, list[TimeSlotType]]
```

2024-10-22 19:07 UTC, robines commented on backend/samfundet/views.py
> +            NoApplicationsWithoutInterviewsError: ('No applications without interviews found.', status.HTTP_400_BAD_REQUEST),
Not really an error. If there's nothing to do, we're good

2025-03-25 16:55 UTC, closed without merging