1080 add date validation to recruitment form
Samfundet/Samfundet4 pull request #1301
Opened 2024-08-27 20:23 UTC by amaliejvik

- Add toast errors for when invalid dates are tried submitted in the Recruitment form 
(ex: displayed deadline must be before actual deadline, visible from must be before reprioritization deadline etc.)
- Add translations with TextItems
<img width="1218" alt="Skjermbilde 2024-08-27 kl  22 18 13" src="https://github.com/user-attachments/assets/1ff6ebfe-5629-4595-912d-f713a440d861">

Closes #1080

2024-08-28 09:54 UTC, robines requested changes

2024-08-28 09:54 UTC, robines commented on backend/root/management/commands/seed_scripts/textitems.py
> +            'key': 'error_recruitment_form_1',
Jeg syns disse feilmeldingene hører bedre til hardkodet i translations, da de er konkrete feilmeldinger knyttet til applikasjonslogikken, og ikke noe vi kommer til å trenge å endre uten at vi også endrer logikken.

2024-08-29 16:46 UTC, amaliejvik commented on backend/root/management/commands/seed_scripts/textitems.py
> +            'key': 'error_recruitment_form_1',
Done @robines :))

2024-08-29 16:50 UTC, robines approved these changes
LGTM!

2024-08-29 17:24 UTC, merged