Skeleten for show unprocessed application
Samfundet/Samfundet4 pull request #1313
Opened 2024-09-05 17:31 UTC by nemisis84

Added the page "unprocessed-applicants/". Choose to only do sorting on applicant status, rather than making a filter to make development faster. 

![image](https://github.com/user-attachments/assets/ad458cc4-b880-4b31-843b-b067a2a8d4f2)

2024-09-05 18:00 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionOverviewPage/RecruitmentPositionOverviewPage.tsx
> -
unødvendige line changes

2024-09-05 18:00 UTC, robines requested changes

2024-09-05 18:00 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentUnprocessedApplicantsPage/RecruitmentUnprocessedApplicantsPage.tsx
> +const data = [
Lag issue/TODO på å fylle inn med backend-data

2024-09-05 18:04 UTC, nemisis84 commented on frontend/src/PagesAdmin/RecruitmentUnprocessedApplicantsPage/RecruitmentUnprocessedApplicantsPage.tsx
> +const data = [
Dette finnes og jeg assigna det til meg 😎

2024-09-05 18:06 UTC, nemisis84 commented on frontend/src/PagesAdmin/RecruitmentUnprocessedApplicantsPage/RecruitmentUnprocessedApplicantsPage.tsx
> +const data = [
https://github.com/orgs/Samfundet/projects/3/views/1?pane=issue&itemId=62454407

2024-09-05 20:40 UTC, Snorre98 submitted a review, later dismissed
lgtm

2024-09-05 23:31 UTC, robines requested changes

2024-09-05 23:31 UTC, robines commented on frontend/src/router/router.tsx
> +            element={<RecruitmentUnprocessedApplicantsPage />}
Som diskutert på arbeidskveld hadde det vært fint å sette inn breadcrumbs her, ellers ser alt bra ut!

2024-09-06 05:51 UTC, Snorre98 commented
@nemisis84 det hadde vært nice om man lett kan se hvor mange søkere det er i tabellen. Altså en count på hvor mange ubehandlede søknader det er.

2024-09-10 20:04 UTC, nemisis84 commented
> @nemisis84 det hadde vært nice om man lett kan se hvor mange søkere det er i tabellen. Altså en count på hvor mange ubehandlede søknader det er.

Hvor på siden tenker du?

2024-09-11 16:53 UTC, nemisis84 commented
Done, please approve @robines @Snorre98

2024-09-11 16:57 UTC, Snorre98 approved these changes

2024-09-11 17:19 UTC, robines approved these changes

2024-09-11 17:19 UTC, merged