Rename GangType to Department
Samfundet/Samfundet4 pull request #1506
Opened 2024-10-01 20:25 UTC by Frenje123

GangType is now called Department.

Fixes #1278

2024-10-01 21:41 UTC, robines commented
Helt imot dette, GangType gir fullstendig mening. Drift, kunstneriske, arragerende osv er ikke departementer, de er bare en kategorisering av gjengene!! Kan da heller rename til GangCategory, hvis folk faktisk ikke skjønner GangType

2024-10-02 11:57 UTC, Mathias-a requested changes
Enig med Robin

2024-10-02 11:57 UTC, Mathias-a commented on backend/root/management/commands/seed_scripts/gangs.py
Starter en thread jeg. Enig med Robin. Departments er et helt fremmed ord i Samfundet kontekst. 

Jeg tror at hvis man hadde lest "department" hadde man aldri ever skjønt at det refererte til "kunstneriske", "Drift". Enig i at det ikke er intuitivt med GangType heller, men da er det iaf 5% sjanse for at noen klarer å gjette det?

2024-10-03 01:15 UTC, Snorre98 commented on backend/root/management/commands/seed_scripts/gangs.py
Jeg liker department. Syns GangType var ekstremt forvirrende første gang jeg leste det. Syns ikke det burde ha noe å si om det passer inn i vokabularet på Samfundet. Bruker vi ikke "Sulten" nettopp fordi vi prøver å unngå å referer til Samfundet vokabular?

Og i tillegg: nå har jo Marcus brukt litt tid på denne PR-en, så vi må finne en måte å bli enig om slike ting før arbeidet blir gjort. Ganske sikker på at Robin i det minste har vært kjent med dette issuet. Det burde blitt diskutert mye tidligere, spesielt hvis man har spesifikte ønsker som "GangCategory".

2024-10-03 02:34 UTC, robines commented on backend/root/management/commands/seed_scripts/gangs.py
> Syns GangType var ekstremt forvirrende første gang jeg leste det

Jeg kan egentlig si meg enig i at det ikke er intuitivt nøyaktig hva det betyr, men etter man får det forklart én gang så sitter det jo. Det er mange andre navn og konsepter i Samfundet4 som er mye mer forvirrende enn akkurat dette syns jeg, selv etter man har fått det forklart flere ganger (feks application priority vs. status).

Departement er hundre ganger verre. Det bringer inn alt for mange assosiasjoner, og ordet refererer nesten alltid til en organisatorisk struktur/enhet. Og det er jo litt dumt, siden det ikke finnes noen gjeng-departementer på Samf! Derfor ville det ha vært utrolig forvirrende å introdusere det som et begrep i prosjektet. Man har ikke det samme problemet med “type” eller “category” fordi de er såpass vage begrep, og man skjønner intuitivt at da handler det om “hva slags type gjeng er det”, i motsetning til “hvilket departement tilhører denne gjengen”.

> Syns ikke det burde ha noe å si om det passer inn i vokabularet på Samfundet. Bruker vi ikke "Sulten" nettopp fordi vi prøver å unngå å referer til Samfundet vokabular?

Apples and oranges. Sulten heter Sulten fordi Lyche endret navn way back in the day, og da tenkte man at man vil unngå refaktorering om det skulle skje igjen. Så problemet er ikke “om det passer inn i vokabularet på Samfundet”, men heller at her virker det som om man prøver å *introdusere* et ord som om det faktisk var i vokabularet.

> Og i tillegg: nå har jo Marcus brukt litt tid på denne PR-en, så vi må finne en måte å bli enig om slike ting før arbeidet blir gjort.

Det er synd ja, men jeg var ikke klar over at dette foregikk, som sikkert skyldes at Marcus ikke har vært på innsjekksrunden på en stund. Hadde noen sagt at de jobbet med dette på runden hadde jeg protestert.

> Ganske sikker på at Robin i det minste har vært kjent med dette issuet.

Jeg husker at du har tatt opp dette som en mulighet tidligere to-tre ganger. Kanskje jeg ikke har vært tydelig nok, men jeg mener at jeg har svart at jeg var imot det hver gang.

Angående GangType vs GangCategory syns jeg GangCategory er mest intuitiv, men forskjellen på de syns jeg er for liten til å være verdt å bruke tid på å refaktorere. Men nå er vi jo her, så da kan vi like godt endre til GangCategory hvis alle er enige?

2024-10-03 14:08 UTC, emilte commented on backend/root/management/commands/seed_scripts/gangs.py
Navnebytte på slike variabler er som oftest bare noen få minutters jobb, så tipper at lite tid er sløst. Dere ville oppdaget dette tidligere også hvis dere deler opp i mindre deler i stedet for slike kembo PR som jeg har anbefalt tidligere.

2024-10-03 14:09 UTC, emilte commented on backend/root/management/commands/seed_scripts/gangs.py
Dere bør kanskje tagge issues som needs-discussion

2024-10-03 17:05 UTC, Snorre98 commented on backend/root/management/commands/seed_scripts/gangs.py
@Frenje123 (etter diskusjon på arbeidskveld) Hva tenker du om å bytte til GangCategory?

2024-10-17 15:51 UTC, Snorre98 commented
Jeg endrer denne til draft

2025-03-17 17:28 UTC, robines commented
@Frenje123 @Snorre98 Kan denne lukkes?

2025-03-18 10:40 UTC, closed without merging