1426 fix create position form
Samfundet/Samfundet4 pull request #1511
Opened 2024-10-03 19:02 UTC by Mathias-a

Gjør følgende: 
- Bytter til react hook form m/ zod
- Fikser opp i serializeren i backend som stoppet oss fra å opprette / endre gangs

2024-10-03 21:03 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +                      <Input type="text" {...field} />
Kan dette være et TextField, hvis vi har det? Eller er dette React Hook Form?

2024-10-03 21:03 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +                      <Input type="text" {...field} />
Samme som over, kan dette være TextField?

2024-10-08 19:03 UTC, Mathias-a commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +const recruitmentPositionSchema = z.object({
Done

2024-10-08 19:35 UTC, Mathias-a commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +                      <Input type="text" {...field} />
Finnes ikke enda, burde lages issue på det

2024-10-09 12:35 UTC, robines requested changes

2024-10-09 12:35 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +                      <Input type="text" {...field} />
Har laget Textarea-komponent nå: #1522

2024-10-09 12:35 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +import { zodResolver } from '@hookform/resolvers/zod';
Kan du extracte selve formen til egen fil/komponent?

2024-10-10 05:40 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +import { zodResolver } from '@hookform/resolvers/zod';
backer

2024-10-10 19:22 UTC, Mathias-a commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +                      <Input type="text" {...field} />
Used

2024-10-10 19:22 UTC, Mathias-a commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +                      <Input type="text" {...field} />
used

2024-10-10 19:44 UTC, Mathias-a commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormAdminPage.tsx
> +import { zodResolver } from '@hookform/resolvers/zod';
Ikke helt solgt, men done

2024-10-15 17:22 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionFormSchema.ts
> +  tags: z.string(),
Jeg syns det er lurt. Da får man definisjonen til hvert felt på ett sted, som gjør det enklere å endre på senere. Om man for eksempel nå skulle ha krevd at long_description består av 5 bokstaver blir det litt jobb siden schemaet bruker bare `NON_EMPTY_STRING`. Hvis du hadde feks `LONG_DESCRIPTION` ville du ikke trengt å endre det noe annet sted enn i selve `schema` mappa

2024-10-17 23:21 UTC, robines requested changes

2024-10-17 23:21 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionForm.tsx
> +}) => {
```suggestion
export function RecruitmentPositionForm({ initialData, positionId, recruitmentId, gangId }: Props) {
```

2024-10-17 23:21 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionForm.tsx
> +type RecruitmentPositionFormType = z.infer<typeof recruitmentPositionSchema>;
Bare pirk, men syns det blir mye finere og letter å lese med kortere variabelnavn. Siden de ikke eksporteres er det heller ikke noe problem.

```suggestion
type SchemaType = z.infer<typeof schema>;
```

2024-10-17 23:21 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionForm.tsx
> +export const recruitmentPositionSchema = z.object({
Kortere variabelnavn, og trenger ikke eksportere

```suggestion
const schema = z.object({
```

2024-10-17 23:21 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionForm.tsx
> +interface RecruitmentPositionFormProps {
Konvensjonen i prosjektet er å bruke `type` til props (vet at det er noen tilfeller som ikke gjør det).
Kan også ha kortere navn, ingen ulempe siden den ikke eksporteres.

```suggestion
type Props = {
```

2024-10-17 23:21 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionForm.tsx
> +    resolver: zodResolver(recruitmentPositionSchema),
```suggestion
  const form = useForm<SchemaType>({
    resolver: zodResolver(schema),
```

2024-10-17 23:21 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionForm.tsx
> +          <Button type="submit">{submitText}</Button>
Kjekt om du kunne endret til grønn rounded knapp, aligned til høyre og med litt spacing fra resten av formet, slik som andre forms har det

2024-10-17 23:21 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionForm.tsx
> +  const onSubmit = (data: RecruitmentPositionFormType) => {
```suggestion
  function onSubmit(data: SchemaType) {
```

2024-10-17 23:21 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionForm.tsx
> +  initialData: Partial<RecruitmentPositionFormType>;
```suggestion
  initialData: Partial<SchemaType>;
```

2024-10-22 16:13 UTC, Mathias-a commented on frontend/src/PagesAdmin/RecruitmentPositionFormAdminPage/RecruitmentPositionForm.tsx
> +  const onSubmit = (data: RecruitmentPositionFormType) => {
Foretrekker function selv, men prinsipielt uenig i kommentaren

2024-10-22 17:01 UTC, Snorre98 approved these changes

2024-10-22 17:04 UTC, merged

2024-10-22 17:05 UTC, robines commented
@Snorre98 ikke dismisse andres reviews uten å spørre de