Feat: Basic setup for role view.
Samfundet/Samfundet4 pull request #1514
Opened 2024-10-03 19:42 UTC by andsamfu

2024-10-06 15:00 UTC, robines requested changes
Veldig fint!:)

Se kommentarer

2024-10-10 17:59 UTC, andsamfu commented on frontend/src/api.ts
> +// TODO: Setup backend later. Using test data now.
Lagt til Issue [#1520](https://github.com/Samfundet/Samfundet4/issues/1520) i kommentaren i koden

2024-10-10 18:01 UTC, andsamfu commented on frontend/src/router/loaders.ts
> +export async function roleViewLoader({ params }: LoaderFunctionArgs): Promise<RoleViewLoader> {
Har oppdatert

2024-10-17 15:51 UTC, robines approved these changes

2024-10-17 17:01 UTC, merged