Created missing useTitle to files
Samfundet/Samfundet4 pull request #1545
Opened 2024-10-24 19:40 UTC by andsamfu

Fix title next to favicon on multiple pages #1450

2024-10-25 00:44 UTC, robines commented on .vscode/settings.default.json
> -{
Var kanskje ikke meningen å slette denne filen?

2024-10-25 00:46 UTC, robines requested changes
Fint!

2024-10-25 00:46 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/RecruitmentOverviewPage.tsx
> +  useTitle(`${t(KEY.recruitment_overview)}`);
```suggestion
  useTitle(t(KEY.recruitment_overview));
```

2024-10-25 17:16 UTC, Snorre98 commented on .vscode/settings.default.json
> -{
Ah, min feil. Fikk for meg den var ignored

2024-10-29 18:20 UTC, andsamfu commented on frontend/src/PagesAdmin/RecruitmentOverviewPage/RecruitmentOverviewPage.tsx
> +  useTitle(`${t(KEY.recruitment_overview)}`);
Har oppdatert koden til forslaget over

2024-10-29 20:43 UTC, Snorre98 approved these changes
![crowd-1780456340](https://github.com/user-attachments/assets/059b7157-81e7-4b84-a5b5-3498922c5e2a)

2024-10-29 20:51 UTC, Snorre98 approved these changes
![7linva-135863957](https://github.com/user-attachments/assets/964c47bd-54ec-4788-8dc3-52860961ce82)

2024-10-29 20:52 UTC, robines approved these changes

2024-10-31 19:06 UTC, merged