Begin interview availability admin page
Samfundet/Samfundet4 pull request #1559
Opened 2024-10-27 03:11 UTC by robines

2025-01-28 18:00 UTC, nemisis84 commented
Link to an issue or describe the feature/fix pls :) A friendly reminder that Snorre requires us to comment our own code before a review as well

2025-01-28 19:26 UTC, emsoraffa commented
Litt pirkete men hadde vært digg om input feltet automatisk formaterte klokkeslett. Altså så man slapp å skrive kolon osv
<img width="966" alt="Screenshot 2025-01-28 at 20 24 13" src="https://github.com/user-attachments/assets/cc57b87b-acb5-4a17-b8d6-ff0bf4a8dcc4" />

2025-01-28 19:57 UTC, emsoraffa requested changes

2025-01-28 19:57 UTC, emsoraffa commented on frontend/src/PagesAdmin/RecruitmentInterviewAvailabilityAdminPage/RecruitmentInterviewAvailabilityForm.tsx
> +  }
```suggestion
    const intervalList = [];
    for (let i = 0; i < intervalCount; i++) {
      intervalList.push(format(addMinutes(startTime, i * interval), 'HH:mm'));
    }
    setTimeslots(intervalList);
  }
```

2025-01-28 19:57 UTC, emsoraffa commented on frontend/src/PagesAdmin/RecruitmentInterviewAvailabilityAdminPage/RecruitmentInterviewAvailabilityForm.tsx
> +  }
Får også en bug hvor siden blir uresponsiv når jeg setter rare verdier i formet, virker som det har med små intervallverdier å gjøre. Mistenker at det skjer pga at det genereres extremt mange intervaller i denne koden

2025-01-28 19:57 UTC, emsoraffa commented on frontend/src/PagesAdmin/RecruitmentInterviewAvailabilityAdminPage/RecruitmentInterviewAvailabilityForm.tsx
> +                    />
Kan også være at det er måten dette gjøres på som forårsaker at siden blir uresponsiv. Får lov å skrive verdier mindre en AVAILABILITY_TIMESLOT_INTERVAL_MIN men da slutter formet å fungere

2025-04-22 17:58 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentInterviewAvailabilityAdminPage/RecruitmentInterviewAvailabilityForm.tsx
> +                    />
Har endret til dropdown, fikser kanskje problemet?

2025-04-24 17:46 UTC, Mathias-a approved these changes
![](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExNml2cW8zZzVrbmRpZThxZHNzZ3NlYjFxMXFsdnduenVzZ3BubTl6dCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/uZjtSy1BYPNcXj5MTA/giphy.webp)

2025-04-24 17:52 UTC, emsoraffa approved these changes
LGTM
![image](https://github.com/user-attachments/assets/f2520f12-90ed-4faa-bcb3-10b9eb591087)

2025-04-24 17:55 UTC, merged