Make status display actually human-readable statuses
Samfundet/Samfundet4 pull request #1581
Opened 2024-10-31 20:47 UTC by amaliejvik

- Make status column display actually human-readable statuses (called and rejected, called and accepted etc.) instead of ID's(0,1,2,3) in both RecruitmentGangAllApplicantsAdminPage (http://localhost:3000/control-panel/recruitment/10/2/all-applications/) and in RecruitmentPositionOverviewPage (http://localhost:3000/control-panel/recruitment/10/gang/2/position/109) with translations

### RecruitmentGangAllApplicantsAdminPage:
<img width="1453" alt="Skjermbilde 2024-10-31 kl  21 30 00" src="https://github.com/user-attachments/assets/6a862840-dc2e-49b9-8ef7-fc09385b9725">

### RecruitmentPositionOverviewPage:

**Før:**
<img width="1361" alt="Skjermbilde 2024-10-31 kl  21 45 54" src="https://github.com/user-attachments/assets/b913d812-fbbd-41f3-bfec-e1d54a0f1677">

**Etter:**
<img width="1387" alt="Skjermbilde 2024-10-31 kl  21 43 08" src="https://github.com/user-attachments/assets/91b64a87-6eda-450b-907a-6756c17b1c0a">

Related to #1431
Closes #1431

2024-11-01 00:16 UTC, robines requested changes

2024-11-01 00:16 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +  const getStatusOption = (id: number | undefined): string => {
Gjerne flytt til en egen globalt tilgjengelig funksjon/hook. Og bruk `RecruitmentStatusChoices` konstantene istedenfor tall

2024-11-01 23:30 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +  const getStatusOption = (id: number | undefined): string => {
Til det siste; er et issue på å hente choices fra backend og implementere de for dette formålet: https://github.com/Samfundet/Samfundet4/issues/1575

2024-11-07 16:52 UTC, amaliejvik commented on frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx
> +  const getStatusOption = (id: number | undefined): string => {
bruker RecruitmentStatusChoices nå:) @robines

2024-11-07 18:19 UTC, emsoraffa approved these changes
LGTM :))

2025-01-16 21:02 UTC, Snorre98 approved these changes

2025-01-19 19:43 UTC, robines approved these changes

2025-01-20 13:35 UTC, emsoraffa approved these changes

2025-01-23 18:17 UTC, merged