adds all, very inspired by shadcn
Samfundet/Samfundet4 pull request #1586
Opened 2024-11-01 22:39 UTC by Snorre98

Creates a modular pagination component, and a specific implementation for DRF pagination.
Component is inspired by how it is done here: https://ui.shadcn.com/docs/components/pagination#

See docs on DRF pagination here: https://www.django-rest-framework.org/api-guide/pagination/

2024-11-06 13:30 UTC, robines requested changes
Se kommentarer

2024-11-06 13:30 UTC, robines commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +        pages.push('ellipsis');
Litt dumt at det vises en ellipsis her istedenfor å bare vise "2"-knappen.

<img width="395" alt="image" src="https://github.com/user-attachments/assets/d3b44552-271e-4d12-b3fc-b1b62fbbc9b0">

2024-11-06 13:30 UTC, robines commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +          <PaginationItem className={itemClassName}>
Både `className` og `itemClassName` kan være undefined, så her ender man opp med mye `undefined`. Du kan løse det ved å bare bruke `classNames`

<img width="262" alt="image" src="https://github.com/user-attachments/assets/7e1161b6-1312-42d2-9dbc-e3678974a63a">

2024-11-06 13:30 UTC, robines commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +    <div className={styles.container}>
Komponenten fungerer ikke særlig bra på mobile.

|||
|---|---|
|<img width="710" alt="image" src="https://github.com/user-attachments/assets/5eadd866-7184-44cf-bfbe-af11ae576ea5"> | <img width="653" alt="image" src="https://github.com/user-attachments/assets/ddd2f043-fed7-421d-96e5-9945aec33ec6">

2024-11-06 13:30 UTC, robines commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +              controllText="Previous"
Mangler translations. Jeg syns uansett det blir litt unødvendig mye å skulle ha tekst her. Heller ersatt Previous/Next med chevrons/piler, mye enklere å forstå visuelt, samt da slipper man å deale med i18n

2024-11-06 13:30 UTC, robines commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +              controllText="Next"
Samme her

2024-11-06 13:30 UTC, robines commented on frontend/src/Components/Pagination/components/PaginationEllipsis/PaginationEllipsis.tsx
> +export const PaginationEllipsis = React.forwardRef<HTMLSpanElement, React.ComponentProps<'span'>>(
```suggestion
import styles from './PaginationEllipsis.module.scss';

export const PaginationEllipsis = React.forwardRef<HTMLSpanElement, React.ComponentProps<'span'>>(
```

2024-11-06 13:30 UTC, robines commented on frontend/src/Components/Pagination/components/PaginationItem/PaginationItem.tsx
> +export const PaginationItem = React.forwardRef<HTMLLIElement, React.ComponentProps<'li'>>(
```suggestion
import styles from './PaginationItem.module.scss';

export const PaginationItem = React.forwardRef<HTMLLIElement, React.ComponentProps<'li'>>(
```

2024-11-06 13:30 UTC, robines commented on frontend/src/Components/Pagination/components/index.ts
> +export { PaginationItem } from './PaginationItem/PaginationItem';
Her kan man se det mangler noen barrel-filer.

Syns egentlig uansett vi burde gå bort ifra de, men det blir en helt egen issue utenfor scopet til PRen her.

2024-11-06 13:30 UTC, robines commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +interface DRFPaginationProps {
```suggestion
import { Pagination, PaginationContent, PaginationControll, PaginationEllipsis, PaginationItem } from './components';

interface DRFPaginationProps {
```

2024-11-06 13:30 UTC, robines commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +    if (totalPages <= 7) {
Hadde vært fint om denne logikken var litt mer customizable, for eksempel ved å legge til to props: `siblingCount` og `boundaryCount`. Da vil det være litt mer fleksibel og kunne brukes av flere komponenter som kanskje er litt mindre, eller litt større og som har plass til å vise flere sider samtidig.

`siblingCount`: Endrer på hvor mange søsken den nåværende valgte knappen har.

* 1 blir da feks: `     ... <4> [5] <6> ...     `
* 2 blir da feks: `... <3> <4> [5] <6> <7> ...`

`boundaryCount`: Hvor mange knapper som vises på kantene, ved siden av Prev/Next-knappene.

* 1 blir da feks: `<Prev> <1> ...`
* 2 blir da feks: `<Prev> <1> <2> ...`

2024-11-06 14:10 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationItem/PaginationItem.tsx
> +  ({ className, ...props }, ref) => <li ref={ref} className={`${styles.item} ${className}`} {...props} />,
Done:
 https://github.com/Samfundet/Samfundet4/commit/18119b6cf0e6202ad760c25e3492f49a4733e12d

2024-11-06 15:27 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationEllipsis/PaginationEllipsis.tsx
> +      . . .
Endret til dette: https://github.com/Samfundet/Samfundet4/commit/3a200870c5c77ba9f7e39f98ed997c6f9c8f50e4

2024-11-06 15:36 UTC, Snorre98 commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +export const DrfPagination: React.FC<DRFPaginationProps> = ({
Kalte den dette fordi det er en wrapper rundt pagineringen som kun (så vidt jeg vet) kan ta data fra DRF paginering. Kan kalle den PagenumberPagination? Jeg har i hvert fall tenkt at det kommer til å bli forskjellige pagineringskomponenter i frontend/src/Components/Pagination for å støtte de forskjellige paginering-klasse i DRF.

2024-11-06 15:41 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationContent/PaginationContent.tsx
> +  ({ className, ...props }, ref) => <ul ref={ref} className={`${styles.list} ${className}`} {...props} />,
Done https://github.com/Samfundet/Samfundet4/commit/26bc9688756d2d5693712042703465df818b1c60

2024-11-06 15:46 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/Pagination/Pagination.tsx
> +  <nav ref={ref} aria-label="pagination" className={`${styles.nav} ${className}`} {...props} />
done: https://github.com/Samfundet/Samfundet4/commit/506d188e432a886ba171819ddadbf16c718c6219

2024-11-06 15:47 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/Pagination/Pagination.tsx
> +export const Pagination = React.forwardRef<HTMLElement, React.ComponentProps<'nav'>>(({ className, ...props }, ref) => (
Done: https://github.com/Samfundet/Samfundet4/commit/551da4799ce385348168b5d6ad68372eb18fc21a

2024-11-06 15:52 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationControll.tsx
> +export function PaginationControll({
done: https://github.com/Samfundet/Samfundet4/commit/432f7b7f127bb6ea6093ee4df720972cbdade5f2

2024-11-06 15:55 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationControll.tsx
> +  controllText: string;
endret til controlSymbol: https://github.com/Samfundet/Samfundet4/commit/58a4d59c9e0dbce7583054338e6d4b1f04c514ed

2024-11-06 16:07 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationControll.tsx
> +type PaginationControllProps = {
Fjernet muligheten til å gjøre store endringer på stilen, så fjernet mange props fra PaginationControlProps (endret navn).
https://github.com/Samfundet/Samfundet4/commit/59120ebfe5203469ddc5703a54dc289236af12af
https://github.com/Samfundet/Samfundet4/commit/a2bd9757c3e37358ab80c63198ef0d78db8f9793

Hvis jeg skal extende etter denne endringene må jeg vel bruke Omit på masse props, som er like nasty som den orginale løsningen?

2024-11-06 16:08 UTC, Snorre98 commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +              controllText="Previous"
done

2024-11-06 16:08 UTC, Snorre98 commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +              controllText="Next"
done

2024-11-06 16:09 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationEllipsis/PaginationEllipsis.tsx
> +export const PaginationEllipsis = React.forwardRef<HTMLSpanElement, React.ComponentProps<'span'>>(
https://github.com/Samfundet/Samfundet4/commit/7fd57785500a6ab48287a70f55a9b28e4eb9d235

2024-11-06 16:10 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationItem/PaginationItem.tsx
> +export const PaginationItem = React.forwardRef<HTMLLIElement, React.ComponentProps<'li'>>(
https://github.com/Samfundet/Samfundet4/commit/b873652c23e2c03b5fb017ca41fd4108a32ea67a

2024-11-06 16:15 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/index.ts
> +export { PaginationItem } from './PaginationItem/PaginationItem';
https://github.com/Samfundet/Samfundet4/commit/a15170912adc2f47615109b3040bb4923336ed11

2024-11-06 16:18 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationEllipsis/PaginationEllipsis.module.scss
> +.ellipsis {
størrelsen er nå lik

2024-11-06 16:19 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationEllipsis/PaginationEllipsis.module.scss
> +.ellipsis {
https://github.com/Samfundet/Samfundet4/commit/993e2ddfc6ea63fd281e5aadd463dd9241426b5a

styling for mobil  / dynamisk width kommer i en senere commit

2024-11-06 16:45 UTC, Snorre98 commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +  const generatePagination = () => {
done

2024-11-06 17:22 UTC, robines requested changes

2024-11-06 17:22 UTC, robines commented on frontend/src/Components/Pagination/components/PaginationControl/PaginationControl.tsx
> +export function PaginationControl({
Føler egentlig kanskje at `PaginationControl` er et litt for lite beskrivende navn. Det første jeg tenkte var at det hadde noe med state å gjøre. Kanskje rename til `PaginationButton`?

2024-11-06 17:22 UTC, robines commented on frontend/src/Components/Pagination/components/PaginationControll.tsx
> +type PaginationControllProps = {
@Snorre98 Poenget er at hvis man feks legger til props til Button-komponenten så slipper man å måtte oppdatere PaginationControl. Syns ikke det er negativt å bruke Omit om du for eksempel vil fjerne mulighet til å sette `theme` på PaginationControl.

Det kan bli ganske clean om du extender ButtonProps (som forsåvidt ikke er exported, det må også gjøres) og fjerner det som uansett er default-verdier:

```jsx
type PaginationControlProps = Omit<ButtonProps, 'theme'> & {
  isActive?: boolean;
  controlSymbol: string | ReactNode;
};

export function PaginationControl({ isActive, className, controlSymbol, ...props }: PaginationControlProps) {
  return (
    <Button theme={isActive ? 'basic' : 'samf'} className={classNames(styles.control, className)} {...props}>
      {controlSymbol}
    </Button>
  );
}
```

2024-11-06 17:22 UTC, robines commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +export const DrfPagination: React.FC<DRFPaginationProps> = ({
Da ville jeg heller kalt den for `PagedPagination` eller noe sånt ja, det er mindre forvirrende.

2024-11-06 19:48 UTC, Snorre98 commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +    if (totalPages <= 7) {
done

2024-11-06 19:53 UTC, Snorre98 commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +    <div className={styles.container}>
Ser bedre ut nå. I hvert fall hvis man setter sibling count og boundry count til 0

2024-11-06 19:54 UTC, Snorre98 commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +        pages.push('ellipsis');
Denne skjønner jeg ikke hvordan jeg kan få til å fikse

2024-11-06 20:01 UTC, Snorre98 commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +          <PaginationItem className={itemClassName}>
done?

2024-11-06 20:09 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationControll.tsx
> +type PaginationControllProps = {
done

2024-11-06 20:10 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationEllipsis/PaginationEllipsis.module.scss
> +.ellipsis {
done

2024-11-06 20:10 UTC, Snorre98 commented on frontend/src/Components/Pagination/components/PaginationControl/PaginationControl.tsx
> +export function PaginationControl({
done

2024-11-07 18:58 UTC, emsoraffa commented
Er komponenten kompatibel med Qutebrowser?

2024-11-07 19:07 UTC, robines approved these changes

2024-11-07 19:09 UTC, robines commented on frontend/src/Components/Pagination/DrfPagination.tsx
> +        pages.push('ellipsis');
Tar det i en ny PR

2024-11-07 19:12 UTC, merged