Bug withdrawn application backend
Samfundet/Samfundet4 pull request #1594
Opened 2024-11-03 02:47 UTC by Snorre98

Replaces backend part of #1542

closes https://github.com/Samfundet/Samfundet4/issues/1535

2024-11-12 21:06 UTC, Mathias-a reviewed
idk se på litt

2024-12-10 22:45 UTC, magsyg commented
Hvordan er denne over 1000 linjer lang wut

2024-12-10 22:58 UTC, magsyg commented
Hmmm ser ganske greit ut, men burde nok egt vært flere issues, ser ut som  dette er en stor refactor av application og modulasering med _ functionene

2025-01-07 18:55 UTC, robines requested changes

2025-01-07 18:55 UTC, robines commented on backend/samfundet/models/recruitment.py
> +        """
Unødvendig docs, fjern

2025-01-07 18:55 UTC, robines commented on backend/samfundet/models/recruitment.py
> +        """
Unødvendig docs, fjern

2025-01-07 18:55 UTC, robines commented on backend/samfundet/models/recruitment.py
> +        self._original_withdrawn = self.withdrawn if self.pk else False
^

2025-02-14 17:35 UTC, closed without merging