Bug withdrawn application frontend
Samfundet/Samfundet4 pull request #1595
Opened 2024-11-03 03:19 UTC by Snorre98

frontend part of #1542

closes https://github.com/Samfundet/Samfundet4/issues/1483
closes https://github.com/Samfundet/Samfundet4/issues/1482

2025-03-21 01:26 UTC, Snorre98 commented on frontend/src/Pages/ApplicantApplicationOverviewPage/ApplicantApplicationOverviewPage.tsx
deleted empty file

2025-03-21 01:26 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/RecruitmentApplicationsOverviewPage.module.scss
styling moved to relevant component/page

2025-03-21 01:26 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/RecruitmentApplicationsOverviewPage.tsx
content improved and or moved to relevant component/page.
implemented RQ

2025-03-25 17:05 UTC, robines requested changes

2025-03-25 17:05 UTC, robines commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/ActiveApplications/ActiveApplications.tsx
> +    queryFn: () => getRecruitmentApplicationsForApplicant(recruitmentId as string).then((response) => response.data),
Endre på getRecruitmentApplicationsForApplicant til å returnere data, og så:

```suggestion
    queryFn: () => getRecruitmentApplicationsForApplicant(recruitmentId as string),
```

2025-03-25 17:05 UTC, robines commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/WithdrawnApplications/WithdrawnApplications.module.scss
> +@import 'src/constants';
Bruk `@use`

2025-03-25 17:05 UTC, robines commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/WithdrawnApplications/WithdrawnApplications.tsx
> +export function WithdrawnApplications({ recruitmentId, queryKey }: WithdrawnApplicationsProps) {
```suggestion
};

export function WithdrawnApplications({ recruitmentId, queryKey }: WithdrawnApplicationsProps) {
```

2025-03-25 17:05 UTC, robines commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/WithdrawnApplications/WithdrawnApplications.tsx
> +  const { data: withdrawnApplications = [] } = useQuery({
Bruk initialData

2025-03-25 17:05 UTC, robines commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/WithdrawnApplications/WithdrawnApplications.tsx
> +    queryFn: () => getWithdrawnRecruitmentApplicationsApplicant(recruitmentId).then((response) => response.data),
Endre på getWithdrawnRecruitmentApplicationsApplicant til å returnere data, og så:

```suggestion
    queryFn: () => getWithdrawnRecruitmentApplicationsApplicant(recruitmentId),
```

2025-03-25 17:54 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/ActiveApplications/ActiveApplications.tsx
> +  const { data: applications = [] } = useQuery({
https://github.com/Samfundet/Samfundet4/pull/1595/commits/719b9b24d11026b44af16a9d57ee92ba179373c2

2025-03-25 17:54 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/ActiveApplications/ActiveApplications.tsx
> +    queryFn: () => getRecruitmentApplicationsForApplicant(recruitmentId as string).then((response) => response.data),
https://github.com/Samfundet/Samfundet4/pull/1595/commits/129d3a9de0b3f72dc376c2c29a65b64c6497ade9

2025-03-25 17:55 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/WithdrawnApplications/WithdrawnApplications.module.scss
> +@import 'src/constants';
https://github.com/Samfundet/Samfundet4/pull/1595/commits/2302f46f047874e630d282f3ba334860c77c4034

2025-03-25 17:56 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/WithdrawnApplications/WithdrawnApplications.tsx
> +  const { data: withdrawnApplications = [] } = useQuery({
https://github.com/Samfundet/Samfundet4/pull/1595/commits/498cc05815ad8e69db1b8ee606e28fba4f3bc2bb

2025-03-25 17:59 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/WithdrawnApplications/WithdrawnApplications.tsx
> +    queryFn: () => getWithdrawnRecruitmentApplicationsApplicant(recruitmentId).then((response) => response.data),
https://github.com/Samfundet/Samfundet4/pull/1595/commits/b92b70c96f8a4d07e50383f5fce1686d8b4d201d

2025-03-25 18:10 UTC, Snorre98 commented on frontend/src/Pages/RecruitmentApplicationsOverviewPage/components/ActiveApplications/ActiveApplications.tsx
> +    queryKey: ['applications', recruitmentId],
https://github.com/Samfundet/Samfundet4/pull/1595/commits/f3b641aff0fa37f1ddb48e74d3f131e2e630c5d1

2025-03-25 20:49 UTC, robines reviewed
Det ser ikke ut til å funke helt? Hvertfall frem til man refresher

https://github.com/user-attachments/assets/6c7ef886-2a30-4a7f-8f53-2587bf7a4e34

2025-03-25 21:53 UTC, Snorre98 commented
> Det ser ikke ut til å funke helt? Hvertfall frem til man refresher
> 
>  Screen.Recording.2025-03-25.at.21.48.04.mov

Ok, skal se på det. Er mye treigere for meg enn det var før.

2025-04-03 04:29 UTC, Snorre98 commented
> Det ser ikke ut til å funke helt? Hvertfall frem til man refresher
> 
>  Screen.Recording.2025-03-25.at.21.48.04.mov

Det er fikset nå @robines

2025-04-24 18:45 UTC, merged