Feature/upgradeapplicantstateview
Samfundet/Samfundet4 pull request #1603
Opened 2024-11-05 22:05 UTC by magsyg

Make a view for and serializer where applicants are organized

Before it was done in frontend, now it is moved to backend

This will also make it easier to fetch the status with how dynamic it is

2024-11-05 22:06 UTC, Snorre98 commented
Jeg har en PR på akkurat dette

2024-11-05 22:07 UTC, Snorre98 commented
https://github.com/Samfundet/Samfundet4/pull/1574

2024-11-07 16:40 UTC, robines requested changes

2024-11-07 16:40 UTC, robines commented on backend/root/utils/routes.py
> +samfundet__api_root = 'samfundet:api-root'
Fjern linje

2024-11-07 16:40 UTC, robines commented on frontend/src/routes/backend.ts
> +  samfundet__api_root: '/api/:format',
Fjern linje

2024-11-07 16:40 UTC, robines commented on backend/samfundet/urls.py
> +        'recruitment-position-organized-applications/<slug:pk>/',
Hvorfor `slug`?

2024-11-12 21:00 UTC, magsyg commented on frontend/src/routes/backend.ts
> +  samfundet__api_root: '/api/:format',
Done

2024-11-12 21:00 UTC, magsyg commented on backend/root/utils/routes.py
> +samfundet__api_root = 'samfundet:api-root'
Done

2024-11-12 21:08 UTC, magsyg commented on backend/samfundet/urls.py
> +        'recruitment-position-organized-applications/<slug:pk>/',
Er det som er gjort andre steder

2024-11-16 14:38 UTC, robines commented on backend/root/utils/routes.py
> +samfundet__api_root = 'samfundet:api-root'
Linjen er der fortsatt

2024-11-16 14:41 UTC, robines commented on backend/samfundet/urls.py
> +        'recruitment-position-organized-applications/<slug:pk>/',
Slug er litt misvisende syns jeg, her er det jo en ID som brukes. Slug er mer for strings som er gjort URL-vennlig. 

For eksempel: `https://stackoverflow.com/questions/4230846/what-is-the-etymology-of-slug-in-a-url`

Her er `what-is-the-etymology-of-slug-in-a-url` slugen, som er generert fra tittelen `What is the etymology of 'slug' in a URL?`

2024-12-06 13:21 UTC, magsyg commented on backend/samfundet/urls.py
> +        'recruitment-position-organized-applications/<slug:pk>/',
Oki byttet det til id

2025-02-18 18:59 UTC, robines approved these changes

2025-02-18 18:59 UTC, merged