fix postitions can have gangs from seperate organizations
Samfundet/Samfundet4 pull request #1636
Opened 2024-12-08 14:48 UTC by magsyg

Found a bug where a recruitment can have positions from gangs from other organizations, such as an UKA position in a Samf recruitment

These would not appear in the admin panel

2024-12-10 20:39 UTC, Snorre98 reviewed
Det ligger også gjenger på opptak som ikke er "eid" av organisasjonen som "eier" opptaket. 
Det finnes altså f.eks. en side for "Økonomi" i et Samf opptak. Se http://localhost:3000/control-panel/recruitment/1/gang/23

Bare å bytte ut gjeng id (den siste) i URLen. Alle over 17 er ikke Samf gjenger.

Så problemet du løser i denne PR-en burde i tillegg løses på et nivå over hvor du gjør det her.

2024-12-10 20:39 UTC, Snorre98 commented on backend/samfundet/models/recruitment.py
> +        raise ValidationError(errors)
Noe av dette blir vel gjort i https://github.com/Samfundet/Samfundet4/pull/1632/ også

2024-12-10 22:59 UTC, magsyg commented on backend/samfundet/models/recruitment.py
> +        raise ValidationError(errors)
Yes, vet det

2024-12-10 23:02 UTC, magsyg commented
> Det ligger også gjenger på opptak som ikke er "eid" av organisasjonen som "eier" opptaket. Det finnes altså f.eks. en side for "Økonomi" i et Samf opptak. Se http://localhost:3000/control-panel/recruitment/1/gang/23
> 
> Bare å bytte ut gjeng id (den siste) i URLen. Alle over 17 er ikke Samf gjenger.
> 
> Så problemet du løser i denne PR-en burde i tillegg løses på et nivå over hvor du gjør det her.

Økonomi blir fortsatt et samf opptak? 

> Det ligger også gjenger på opptak som ikke er "eid" av organisasjonen som "eier" opptaket. Det finnes altså f.eks. en side for "Økonomi" i et Samf opptak. Se http://localhost:3000/control-panel/recruitment/1/gang/23
> 
> Bare å bytte ut gjeng id (den siste) i URLen. Alle over 17 er ikke Samf gjenger.
> 
> Så problemet du løser i denne PR-en burde i tillegg løses på et nivå over hvor du gjør det her.

damn nice spotta

2025-01-07 20:03 UTC, robines requested changes

2025-01-07 20:03 UTC, robines commented on frontend/src/PagesAdmin/RecruitmentGangAdminPage/RecruitmentGangAdminPage.tsx
> +      getRecruitmentPositionsGangForGang(recruitmentId, gangId)
Gjerne bytt til å bruke react query. [Docs her](https://github.com/Samfundet/Samfundet4/blob/master/docs/technical/frontend/data-fetching.md)

2025-01-20 16:53 UTC, magsyg commented on frontend/src/PagesAdmin/RecruitmentGangAdminPage/RecruitmentGangAdminPage.tsx
> +      getRecruitmentPositionsGangForGang(recruitmentId, gangId)
Done

2025-01-30 20:26 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentGangAdminPage/RecruitmentGangAdminPage.tsx
> +      getRecruitmentPositionsGangForGang(recruitmentId, gangId)
@robines resovle eller se om det kan gjøres på en annen måte. Trengs det for eksempel å bruke en useEffect i det heletatt når man bruker react query?

2025-01-30 20:47 UTC, Snorre98 commented on backend/samfundet/views.py
> +        if recruitment.resolve_org() != gang.resolve_org():
Hvis dette viewet skal sørge for man ikke kan gjenger som ikke er i organisasjonene, så virker det ikke. Mulig det ikke virker fordi vi ikke har en ekte relasjon mellom gjenger og organisasjoner i seedscript?
@magsyg hvis du vet hvorfor denne checken ikke gjør det den er ment å gjøre hadde det vært nice om du lager et issue på det og kommenterer Todo og viser til det spesifikke issue nummeret.

2025-01-30 20:47 UTC, Snorre98 commented on frontend/src/PagesAdmin/RecruitmentGangAdminPage/RecruitmentGangAdminPage.tsx
>    useEffect(() => {
@robines trenger man bruke useEffect her?

2025-03-01 10:50 UTC, closed without merging