add opening hours
Samfundet/Samfundet4 pull request #251
Opened 2022-12-04 23:54 UTC by magsyg

added opening hours
also added time to timedisplay
also added time duration component

2022-12-11 00:44 UTC, emilte approved these changes

2022-12-11 00:44 UTC, emilte commented on frontend/src/Components/OpeningHours/OpeningHours.tsx
> +  venues: Array;
Venues[]

2022-12-11 00:44 UTC, emilte commented on frontend/src/Components/OpeningHours/OpeningHours.module.scss
> +  }
Kan være egen klasse

2022-12-11 00:45 UTC, emilte requested changes
Venter til du er ferdig bare

2022-12-13 15:52 UTC, magsyg commented on frontend/src/Components/OpeningHours/OpeningHours.module.scss
> +  }
p styler timeduration p også, vil at de skal skal ha lik stil

2022-12-13 15:53 UTC, magsyg commented on frontend/src/Components/OpeningHours/OpeningHours.tsx
> +  venues: Array;
hvordan da? får bare feil

2022-12-14 00:43 UTC, emilte commented on frontend/src/Components/OpeningHours/OpeningHours.tsx
> +  venues: Array;
Hmm, kan du vise meg?

2022-12-14 10:31 UTC, emilte commented on frontend/src/Components/OpeningHours/OpeningHours.module.scss
> +  }
Har ikke TimeDuration hook for className? Isåfall kunne den kanskje trengt det

2022-12-14 16:10 UTC, magsyg commented on frontend/src/Components/OpeningHours/OpeningHours.tsx
> +  venues: Array;
kan du gi meg linja?
tenker du
venues[]: Array;

2022-12-15 19:16 UTC, magsyg commented on frontend/src/Components/OpeningHours/OpeningHours.tsx
> +  venues: Array;
OKi done, skjønte det nå

2022-12-15 21:16 UTC, emilte commented on frontend/src/Components/OpeningHours/OpeningHours.module.scss
> +  margin-bottom: 20px;
Margin passer å bruke em tror jeg

2022-12-15 21:18 UTC, emilte approved these changes

2022-12-15 21:18 UTC, merged