Add created_at and updated_at fields to each model
Samfundet/Samfundet4 pull request #370
Opened 2023-02-16 19:43 UTC by robines

User model already has `date_joined` field, so I've only added `updated_at` field to it

2023-02-16 20:09 UTC, emilte requested changes
Kan du legge inn i Admin?

2023-02-16 21:00 UTC, emilte approved these changes

2023-02-22 18:41 UTC, Mathias-a approved these changes

2023-02-23 17:52 UTC, eiriksho approved these changes
LGTM

2023-02-24 10:20 UTC, merged