Add AccessDenied component
Samfundet/Samfundet4 pull request #381
Opened 2023-02-23 21:03 UTC by Frenje123

Add access denied component

2023-02-23 23:34 UTC, robines commented
Is there still a need for this component, instead of just using the newly created [Error](https://github.com/Samfundet/Samfundet4/blob/master/frontend/src/Components/Error/Error.tsx) component?

2023-02-24 08:46 UTC, emilte commented
> Is there still a need for this component, instead of just using the newly created [Error](https://github.com/Samfundet/Samfundet4/blob/master/frontend/src/Components/Error/Error.tsx) component?

For meg er det hvert fall litt forskjell på å få error i forhold til permission denied. Tror dette er en fin komponent å ha jeg.

2023-02-24 08:48 UTC, emilte commented on frontend/src/Components/AccessDenied/AccessDenied.tsx
>  }
Det hadde vært kult med en svg ellerno her.

2023-02-24 08:51 UTC, emilte commented on frontend/src/Components/AccessDenied/AccessDenied.tsx
> +export function AccessDenied({ header, message, children }: AccessDeniedProps) {
Jeg skjønner godt at Robin stusser litt, den er veldig lik. Disse komponentene trenger kanskje ikke være veldig generiske. Sett gjerne inn noen default verdier og bilde/animasjon slik at vi skiller dem fra hverandre.

2023-03-07 22:15 UTC, emilte commented
@Frenje123 Progresjon her?

2023-03-12 11:14 UTC, Frenje123 commented on frontend/src/Components/AccessDenied/AccessDenied.tsx
> +export function AccessDenied({ header, message, children }: AccessDeniedProps) {
Modified

2023-03-12 11:14 UTC, Frenje123 commented on frontend/src/Components/AccessDenied/AccessDenied.tsx
>  }
Modified

2023-03-12 15:15 UTC, emilte commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +
Helst trekk ut farger som lokale eller globale konstanter, kanskje har vi noen fra før?

2023-03-12 15:16 UTC, emilte commented on frontend/src/Components/AccessDenied/AccessDenied.tsx
>  }
Gidder du sende screenshot?

2023-03-12 15:21 UTC, robines requested changes

2023-03-12 15:21 UTC, robines commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +  height: 10em;
La boksen ekspandere med content

```suggestion
  min-height: 10em;
```

2023-03-12 15:21 UTC, robines commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +  margin: 1em 0 1em 0;
```suggestion
  margin: 0 0 1em;
```

2023-03-12 15:21 UTC, robines commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +  font-family: arial, sans-serif;
```suggestion
  font-family: arial, sans-serif;
  padding: 1em;
```

2023-03-12 15:21 UTC, robines commented on frontend/src/Components/AccessDenied/AccessDenied.tsx
> +export function AccessDenied({ header, message }: AccessDeniedProps) {
Kan vi sette default verdier på header og message? Som de i stories filen

2023-03-12 16:10 UTC, emilte commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +  margin: 1em 0 1em 0;
```suggestion
  margin: 0 1em;
```

2023-03-12 17:59 UTC, Frenje123 commented on frontend/src/Components/AccessDenied/AccessDenied.tsx
>  }
![image](https://user-images.githubusercontent.com/48588529/224563353-e0d0bdea-6217-4d77-ab2a-9d4881279730.png)
Almost identical to: https://www.samfundet.no/403

2023-03-12 18:13 UTC, Frenje123 commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +
Done

2023-03-12 18:17 UTC, Frenje123 commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +  margin: 1em 0 1em 0;
![image](https://user-images.githubusercontent.com/48588529/224564221-5beb5453-8441-4791-abea-9a238e2c2cd9.png)
I think that looks quite bad,

2023-03-12 18:19 UTC, Frenje123 commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +  margin: 1em 0 1em 0;
Changed to "0 1em 1em", and added padding as suggested below

2023-03-12 18:19 UTC, Frenje123 commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +  font-family: arial, sans-serif;
Done

2023-03-12 18:20 UTC, Frenje123 commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +  margin: 1em 0 1em 0;
![image](https://user-images.githubusercontent.com/48588529/224564378-f5281b7b-15bf-4bbb-bbc1-29657f9cfe18.png)
I think this looks better

2023-03-12 18:21 UTC, Frenje123 commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +  height: 10em;
Done

2023-03-12 20:13 UTC, emilte commented on frontend/src/Components/AccessDenied/AccessDenied.module.scss
> +  margin: 1em 0 1em 0;
haha, skummel mld

2023-03-12 20:14 UTC, emilte approved these changes

2023-03-16 20:13 UTC, Frenje123 commented on frontend/src/Components/AccessDenied/AccessDenied.tsx
> +export function AccessDenied({ header, message }: AccessDeniedProps) {
Done

2023-03-16 20:21 UTC, robines requested changes

2023-03-16 20:21 UTC, robines commented on frontend/src/i18n/translations.ts
> +  you've done!`,
```suggestion
  [KEY.access_denied_message]:
    `You somehow bypassed the outermost security layer, but luckily we stopped you! You could have hurt someone! Now, go to your room and think about what you've done!`,
```

2023-03-16 20:52 UTC, Frenje123 commented on frontend/src/i18n/translations.ts
> +  you've done!`,
Done

2023-03-16 20:53 UTC, robines approved these changes

2023-03-17 11:41 UTC, merged