388 create lyche landing page
Samfundet/Samfundet4 pull request #394
Opened 2023-03-08 17:42 UTC by Mathias-a

Remaining
- [ ] Add translations
- [ ] Add text as text items
- [ ] Set default height for cards 
- [ ] Align åpningstider
- [ ] Improve åpningstider, so it won't say man-tor open if its incorrect
- [ ] Add onclick function to card, so you can click on the button and go to other pages
- [ ] Fix image scaling on desktop

2023-03-12 15:21 UTC, emilte commented on frontend/src/Components/SultenCard/SultenCard.module.scss
> +/* stylelint-disable declaration-no-important */
Trenger du denne?

2023-03-12 15:26 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +        setConsistentWeekendHours(lycheVenue?.opening_friday === lycheVenue?.opening_saturday);
Kan gjøres tydeligere på flere linjer.

2023-03-12 15:27 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +    lycheVenue?.opening_wednesday,
Kan de være i riktig rekkefølge? :P

2023-03-12 15:28 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +
Skjer mye i denne komponenten, men orker ikke se gjennom det nå. Vi kan se på det senere

2023-03-12 15:29 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +      text={useTextItem('sulten_reservation_text', i18n)}
Samle alle nøkler som konstanter et sted

2023-03-12 15:30 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +      onButtonClick={() => navigate(ROUTES.frontend.sulten_menu)}
Universell utforming sier vi bør bruke lenker

2023-03-12 15:31 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +      text={useTextItem('sulten_about_us_text', i18n)}
.

2023-03-12 15:33 UTC, emilte commented on frontend/src/hooks.ts
> +export function useTextItem(key: string, i18n: i18n): string | undefined {
Kunne ikke denne bare brukt i18n hook by default? Den finner språket selv.

2023-03-12 15:33 UTC, emilte commented on frontend/src/hooks.ts
> +  const isNorwegian = i18n.language === 'nb';
Bruk konstanten

2023-03-12 15:34 UTC, emilte commented on frontend/src/i18n/constants.ts
> +  sulten_more_about_us: 'more_about_us',
Se docstring øverst

2023-03-12 15:34 UTC, emilte commented on frontend/src/i18n/constants.ts
> +  sulten_more_about_us: 'more_about_us',
Se docstring øverst

2023-03-12 16:26 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +        setConsistentWeekendHours(lycheVenue?.opening_friday === lycheVenue?.opening_saturday);
Ved å legge til en pretter-ignore da?

2023-03-12 16:26 UTC, Mathias-a commented on frontend/src/Components/SultenCard/SultenCard.module.scss
> +/* stylelint-disable declaration-no-important */
Fjernet

2023-03-12 16:27 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +    lycheVenue?.opening_wednesday,
Skylder på autocomplete her assa 😆 Fixed

2023-03-12 16:28 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +      text={useTextItem('sulten_reservation_text', i18n)}
Tanker om hvor dette burde ligge?

2023-03-12 16:29 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +
Kunne potensielt laget en egen komponent for åpningstider boksen

2023-03-12 16:43 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +      onButtonClick={() => navigate(ROUTES.frontend.sulten_menu)}
Fixed med React router sin <Link> komponent

2023-03-12 16:51 UTC, Mathias-a commented on frontend/src/hooks.ts
> +export function useTextItem(key: string, i18n: i18n): string | undefined {
Skjønner ikke hva du mener

2023-03-12 16:54 UTC, Mathias-a commented on frontend/src/i18n/constants.ts
> +  sulten_more_about_us: 'more_about_us',
Fixed

2023-03-12 16:54 UTC, Mathias-a commented on frontend/src/i18n/constants.ts
> +  sulten_more_about_us: 'more_about_us',
Fixed

2023-03-12 16:55 UTC, Mathias-a commented on frontend/src/hooks.ts
> +  const isNorwegian = i18n.language === 'nb';
Fixed

2023-03-12 17:10 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +      text={useTextItem('sulten_about_us_text', i18n)}
Fixed

2023-03-12 17:10 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +        setConsistentWeekendHours(lycheVenue?.opening_friday === lycheVenue?.opening_saturday);
La til en prettier-ignore

2023-03-12 17:11 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +      text={useTextItem('sulten_reservation_text', i18n)}
Lagde en egen fil som heter TextItems.ts, ligger for øyeblikket bare i src

2023-03-12 20:16 UTC, emilte commented on frontend/src/hooks.ts
> +export function useTextItem(key: string, i18n: i18n): string | undefined {
Hvis du ikke oppgir `i18n` burde den klare å skjønne nåværende språk automatisk

2023-03-12 20:17 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +      text={useTextItem('sulten_reservation_text', i18n)}
Kan bruke constants.ts

2023-03-12 20:18 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +        setConsistentWeekendHours(lycheVenue?.opening_friday === lycheVenue?.opening_saturday);
Nei tenker å trekke ut i constanter

2023-03-12 20:19 UTC, emilte commented on frontend/src/Components/SultenButton/SultenButton.module.scss
> +/* stylelint-disable declaration-no-important */
.

2023-03-12 20:21 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
>          const lyche = data.find((venue) => venue.name?.toLowerCase() === 'lyche');
Trenger nok konstanter for venue names også

2023-03-12 20:22 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Uten å ha sett på det høres substrings feil ut, hvordan garanterer du samme resultat? Se TimeDisplay

2023-03-12 20:23 UTC, emilte commented on frontend/src/hooks.ts
> +// Hook that returns the correct translation for given key
/** ... */

2023-03-12 20:24 UTC, emilte commented on frontend/src/i18n/constants.ts
> +  sulten_page_more_about_us: 'more_about_us',
Fortsatt

2023-03-12 20:25 UTC, emilte commented on frontend/src/textItems.ts
> +export const TextItem = {
constants.ts

2023-03-13 15:56 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +      text={useTextItem('sulten_reservation_text', i18n)}
Vil ikke det føles litt som slutter? Kan legge det der, men syntes det føles riktigere ut med en egen fil, siden det er sånn vi gjør det for vanlige translations

2023-03-13 15:56 UTC, Mathias-a commented on frontend/src/hooks.ts
> +export function useTextItem(key: string, i18n: i18n): string | undefined {
Ah, du mener ved å importere i18next? For I så fall fixed

2023-03-13 15:57 UTC, Mathias-a commented on frontend/src/hooks.ts
> +// Hook that returns the correct translation for given key
Det er ikke standarden som er fulgt ellers i filen, skal jeg endre alle tilfellene?

2023-03-13 15:58 UTC, Mathias-a commented on frontend/src/i18n/constants.ts
> +  sulten_page_more_about_us: 'more_about_us',
Du mener det bør stå Lyche page ikke sulten page?

2023-03-13 16:19 UTC, emilte commented on frontend/src/i18n/constants.ts
> +  sulten_page_more_about_us: 'more_about_us',
Bare samme på begge sider, unngå tvetydighet
```
sulten_page_more_about_us: 'sulten_page_more_about_us',
```

2023-03-13 16:21 UTC, Mathias-a commented on frontend/src/i18n/constants.ts
> +  sulten_page_more_about_us: 'more_about_us',
Åja, hehe my bad

2023-03-13 16:22 UTC, emilte commented on frontend/src/hooks.ts
> +export function useTextItem(key: string, i18n: i18n): string | undefined {
Ikke helt, jeg tenker at siden dette er en hook kan den bruke useTranslation

2023-03-13 16:24 UTC, Mathias-a commented on frontend/src/hooks.ts
> +export function useTextItem(key: string, i18n: i18n): string | undefined {
Ah ok, fixed, noe grunn til at dette er en bedre praksis?

2023-03-13 16:30 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
>          const lyche = data.find((venue) => venue.name?.toLowerCase() === 'lyche');
Eller mente du åpningstidene til Lyche som venue?

2023-03-13 16:36 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Glemte at TimeDisplay var en greie, men TimeDisplay gjør basically det samme, men bruker slice istedenfor substring

2023-03-13 22:22 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Jeg er skeptisk til det der også. Hvorfor skal man slice?

2023-03-13 22:23 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Det finnes vel en format metode et sted?

2023-03-14 14:24 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Kan undersøke det, tanken er jo at det er et date objekt med bare timer, så man slicer timer fra å inkludere sekunder til å bare være timer, altså fra 20:00:00 til 20:00

2023-03-14 15:35 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Jo men det virker ikke som folk har gjort research
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString

2023-03-14 17:46 UTC, Mathias-a commented on frontend/src/Components/SultenButton/SultenButton.module.scss
> +/* stylelint-disable declaration-no-important */
Done

2023-03-14 17:50 UTC, Mathias-a commented on frontend/src/hooks.ts
> +// Hook that returns the correct translation for given key
Fixed

2023-03-14 18:02 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
>          const lyche = data.find((venue) => venue.name?.toLowerCase() === 'lyche');
=== 'lyche'

2023-03-14 18:02 UTC, emilte commented on frontend/src/hooks.ts
>    return isNorwegian ? textItem?.text_nb : textItem?.text_en;
Man bør fortsatt kunne sende inn optional language, noen ganger vil man ha noe annet enn nåværende.

2023-03-14 20:50 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +      text={useTextItem('sulten_reservation_text', i18n)}
Endte i en egen fil, se TextItems.ts

2023-03-16 18:17 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
>          const lyche = data.find((venue) => venue.name?.toLowerCase() === 'lyche');
Fixed

2023-03-16 18:21 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Skjønner ikke helt hva jeg skal gjøre her, jeg får vel ikke et date objekt fra backend?

2023-03-16 18:22 UTC, Mathias-a commented on frontend/src/i18n/constants.ts
> +  sulten_page_more_about_us: 'more_about_us',
Fixed

2023-03-16 18:26 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Du kan parse det

2023-03-16 18:30 UTC, Mathias-a commented on frontend/src/hooks.ts
>    return isNorwegian ? textItem?.text_nb : textItem?.text_en;
Fixed

2023-03-16 19:08 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Som diskutert er det time på format 20:00:00så slice funker vel?

2023-03-16 19:10 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Ja jeg hadde misforstått, slice går sikkert fint

2023-03-16 19:14 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +
Future problem

2023-03-16 19:15 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
>          const lyche = data.find((venue) => venue.name?.toLowerCase() === 'lyche');
Global konstant

2023-03-16 19:15 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
>          const lyche = data.find((venue) => venue.name?.toLowerCase() === 'lyche');
samme som textitems

2023-03-16 19:31 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
>          const lyche = data.find((venue) => venue.name?.toLowerCase() === 'lyche');
https://github.com/Samfundet/Samfundet4/issues/426

2023-03-21 19:31 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +        setConsistentWeekendHours(consistentWeekendOpeningHours && consistentWeekendClosingHours);
utils

2023-03-21 19:32 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +
Kan lage issue forsåvidt, gidder du

2023-03-21 19:52 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +
https://github.com/Samfundet/Samfundet4/issues/438

2023-03-21 19:53 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +        const lyche = data.find((venue) => venue.name?.toLowerCase() === venueName);
Fixed

2023-03-21 19:53 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +        setConsistentWeekendHours(consistentWeekendOpeningHours && consistentWeekendClosingHours);
Fixed

2023-03-21 19:59 UTC, emilte commented on frontend/src/Pages/LychePage/LychePage.tsx
> +    lycheVenue,
meningen?

2023-03-21 20:03 UTC, emilte approved these changes

2023-03-21 20:06 UTC, Mathias-a commented on frontend/src/Pages/LychePage/LychePage.tsx
> +    lycheVenue,
Litt unødvendige ting her, endret det til bare å være lychevenue

2023-03-23 17:54 UTC, evgiz requested changes

2023-03-23 17:54 UTC, evgiz commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
Disse har alle samme logikk som kan flyttes til `openingHourRow(day_key, open_day, close_day)`. Der kan man evt også bruke `<TimeDisplay>`

2023-03-23 17:55 UTC, evgiz commented on frontend/src/Pages/LychePage/LychePage.tsx
> +            `${lycheVenue?.opening_monday?.substring(0, 5)}-${lycheVenue?.closing_monday?.substring(0, 5)}`,
`openingHourRow(day: string, openTime: string, closeTime: string)`

2023-03-23 19:07 UTC, evgiz approved these changes
Nice!

2023-03-23 20:44 UTC, merged