265 checkbox disabled styling
Samfundet/Samfundet4 pull request #546
Opened 2023-04-10 21:39 UTC by Snorre98

2023-04-10 23:05 UTC, emilte approved these changes

2023-04-11 18:55 UTC, robines requested changes

2023-04-11 18:55 UTC, robines commented on frontend/src/Components/Checkbox/Checkbox.module.scss
> +}
Fjern duplikat kode med `.checkbox__box`, og heller legg til denne klassen når checkboxen er disabled

```suggestion
.checkbox__disabled {
  border-color: $grey-3;
  background-color: $grey-3;
  cursor: not-allowed;
}
```

2023-04-11 18:55 UTC, robines commented on frontend/src/Components/Checkbox/Checkbox.tsx
> +      <div className={disabled ? styles.checkbox__disabled : styles.checkbox__box}></div>
Knyttet til andre kommentaren min

```suggestion
      <div className={classNames(styles.checkbox__box, disabled && styles.checkbox__disabled)}></div>
```

2023-04-13 17:33 UTC, Snorre98 commented on frontend/src/Components/Checkbox/Checkbox.module.scss
> +  content: '\2714'; /* ASCII "check"-symbol. */
Gjort

2023-04-13 17:34 UTC, Snorre98 commented on frontend/src/Components/Checkbox/Checkbox.module.scss
> +.checkbox__input + .checkbox__disabled::after {
Gjort (på en måte)

2023-04-13 17:36 UTC, Snorre98 commented on frontend/src/Components/Checkbox/Checkbox.module.scss
> +}
Ble ikke helt som forventet, mulig jeg har missforstått noe. Den ser ut som jeg vil den skal se ut, men extender css fra både .checkbox__box og .checkbox__disabled

2023-04-13 17:56 UTC, robines commented on frontend/src/Components/Checkbox/Checkbox.tsx
> +import classNames from 'classnames';
```suggestion
```

2023-04-13 17:59 UTC, robines commented on frontend/src/Components/Checkbox/Checkbox.module.scss
> +  content: $checkmark;
```suggestion
.checkbox__input:disabled + .checkbox__box {
  border-color: $grey-3;
  background-color: $grey-3;
  cursor: not-allowed;
}
```

2023-04-13 18:46 UTC, Snorre98 commented on frontend/src/Components/Checkbox/Checkbox.tsx
> +      <div className={disabled ? styles.checkbox__disabled : styles.checkbox__box}></div>
Nå tror jeg de ble som du mener

2023-04-13 18:47 UTC, Snorre98 commented on frontend/src/Components/Checkbox/Checkbox.tsx
> +      {/* <div className={disabled ? styles.checkbox__disabled : styles.checkbox__box}></div> */}
Nå tror jeg de ble som du mener

2023-04-13 18:47 UTC, Snorre98 commented on frontend/src/Components/Checkbox/Checkbox.tsx
> +import classNames from 'classnames';
Nå tror jeg de ble som du mener

2023-04-13 18:47 UTC, Snorre98 commented on frontend/src/Components/Checkbox/Checkbox.module.scss
> +  content: $checkmark;
Nå tror jeg de ble som du mener

2023-04-13 18:59 UTC, robines approved these changes

2023-04-14 16:03 UTC, evgiz commented on frontend/src/Components/Checkbox/Checkbox.module.scss
> +  content: $checkmark;
Jeg tenker vi burde bytte denne med et penere ikon fra iconify, men det krever nok litt mer jobb for å få til

2023-04-14 16:06 UTC, evgiz approved these changes

2023-04-14 21:32 UTC, emilte commented on frontend/src/Components/Checkbox/Checkbox.module.scss
> +  content: $checkmark;
Enig

2023-04-18 23:14 UTC, merged