Create new auth backend for case-insensitive username
Samfundet/Samfundet4 pull request #574
Opened 2023-04-18 18:33 UTC by robines

Basically a copy of the currently used ModelBackend, except username is now case-insensitive

2023-04-18 18:43 UTC, emilte requested changes
Alt kan være lowercase

2023-04-18 19:02 UTC, emilte approved these changes

2023-04-18 19:53 UTC, emilte approved these changes

2023-04-19 16:56 UTC, robines commented
@emilte Tanker om siste endring? Migrationen gjorde ikke om brukernavn med store bokstaver til små, da i UsernameFields øyne er alt lowercase uansett, så jeg la til først konvertering av alle brukernavn til lowercase. Hvis det oppstår konflikter her vil migrationen krasje (det ser jeg egentlig på som ønskelig)

2023-04-19 21:49 UTC, emilte commented on backend/samfundet/migrations/0025_alter_user_username.py
> +            user.save()
Jeg tror ikke dette er nødvendig, vi har ikke noe data å konvertere

2023-04-19 21:49 UTC, emilte commented on backend/samfundet/migrations/0025_alter_user_username.py
> +            user.save()
Bare slett lokal db

2023-04-20 19:17 UTC, robines commented on backend/samfundet/migrations/0025_alter_user_username.py
> +            user.save()
Den er grei. Fjernet endringen nå.

2023-04-20 19:29 UTC, emilte commented
@evgiz Nå kreves visst approval fra begge

2023-04-20 19:30 UTC, emilte commented
Nvm, jeg så feil

2023-04-21 00:01 UTC, merged