Made Infobox model
Samfundet/Samfundet4 pull request #599
Opened 2023-04-25 19:54 UTC by Snorre98

2023-04-25 21:22 UTC, evgiz requested changes
Nice, bare en liten typo som mangler! 

Vi trenger muligens en status/plassering i modellen for å vite hvor på homescreen den skal plasseres, men har ikke tenkt helt på hvordan det er best å gjøre dette. Kan evt ha en egen homescreen-modell elns som man styrer dette fra. Kan ta det etterhvert!

2023-04-25 21:22 UTC, evgiz commented on backend/samfundet/models/general.py
> +    titel_nb = models.CharField(max_length=60, blank=False, null=False, verbose_name="Infoboks titel (norsk)")
`title_nb`

2023-04-26 05:54 UTC, emilte approved these changes

2023-04-27 12:31 UTC, Snorre98 commented on backend/samfundet/models/general.py
> +    titel_nb = models.CharField(max_length=60, blank=False, null=False, verbose_name="Infoboks titel (norsk)")
endret

2023-05-09 17:32 UTC, evgiz approved these changes
Nice!

2023-05-09 18:19 UTC, merged