Draft general Samf4 tech stack
Samfundet/Samfundet4 pull request #657
Opened 2023-08-23 00:19 UTC by Snorre98

Tar gjerne tilbakemelding på dette, både det tekniske og finskriving. Det er ment mer som en forklaring av teknologiene som brukes i prosjektet til personer som ikke har mye erfaring med webutvikling enn teknisk dokumentasjon.

2023-08-29 17:00 UTC, Snorre98 commented on docs/technical/Samf4Tech.md
> +In backend we use the Python formatter [yapf](https://pypi.org/project/yapf/) because it is a formatter that offers multiple populare Python formats and standards. The format is configured in a Pytho
Må forklare hvordan dette brukes loklalt

2023-09-03 15:15 UTC, Mathias-a approved these changes
Nice med litt docs :)

2023-09-03 15:15 UTC, Mathias-a commented on docs/technical/Samf4Tech.md
> +To learn more about TypeScript you can check out the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html ) or simple [tutorials on W3Schools](https://www.w3sch
Denne burde kanskje nevne eller forklare forskjellen på TypeScript og TSX/JSX

2023-09-03 22:24 UTC, Snorre98 commented on docs/technical/Samf4Tech.md
> +To learn more about TypeScript you can check out the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html ) or simple [tutorials on W3Schools](https://www.w3sch
Gjort, sannsyligvis med masse typos.

2023-09-05 17:47 UTC, evgiz requested changes
Noice

2023-09-05 17:47 UTC, evgiz commented on docs/technical/Samf4Tech.md
> +If you are new to web development you might not have experience with dependencies. Dependencies are packages or modules that are required for a web development project to run properly and package man
Ikke bare for å kjøre, men også ekstra funksjonalitet og div

2023-09-05 17:47 UTC, evgiz commented on docs/technical/Samf4Tech.md
> +To make the code we write on the project high quality, have a standardised format and generally readable we use the formatters and linters. This is very useful when writing code as a team. The main p
*purpose

2023-09-05 17:47 UTC, evgiz commented on docs/technical/Samf4Tech.md
> +To use our code format and linting rules you have to configure a JSON file locally, and of course have the tools installed in your IDE. After installing the project and getting it to run, you need to
Gjelder kun vscode, kan kanskje skrive det for de som ikke bruker det :))

2023-09-05 17:47 UTC, evgiz commented on docs/technical/Samf4Tech.md
> +In backend we use the Python formatter [yapf](https://pypi.org/project/yapf/) because it is a formatter that offers multiple populare Python formats and standards. The format is configured in a Pytho
*popular

2023-09-05 17:47 UTC, evgiz commented on docs/technical/Samf4Tech.md
> +For linting we use [flake8](https://flake8.pycqa.org/en/latest/) and [pylint](https://pypi.org/project/pylint/). They have similar functions, but flake8 has some more functionality. These tools are e
*Python code more strictly typed

2023-09-05 17:47 UTC, evgiz commented on docs/technical/Samf4Tech.md
> +React exploits something called a virtual DOM(document object model) to render HTML(in acctuality something similar to it) content on the web. Historically when webdevelopers wanted to controll how H
*actuality
*controls
*control

2023-09-05 20:55 UTC, Snorre98 commented on docs/technical/Samf4Tech.md
> +If you are new to web development you might not have experience with dependencies. Dependencies are packages or modules that are required for a web development project to run properly and package man
La til noe kort om Docker funksjonalitet

2023-09-05 20:55 UTC, Snorre98 commented on docs/technical/Samf4Tech.md
> +To make the code we write on the project high quality, have a standardised format and generally readable we use the formatters and linters. This is very useful when writing code as a team. The main p
done

2023-09-05 20:55 UTC, Snorre98 commented on docs/technical/Samf4Tech.md
> +To use our code format and linting rules you have to configure a JSON file locally, and of course have the tools installed in your IDE. After installing the project and getting it to run, you need to
La til en linje om dette

2023-09-05 20:55 UTC, Snorre98 commented on docs/technical/Samf4Tech.md
> +In backend we use the Python formatter [yapf](https://pypi.org/project/yapf/) because it is a formatter that offers multiple populare Python formats and standards. The format is configured in a Pytho
fixed

2023-09-05 20:55 UTC, Snorre98 commented on docs/technical/Samf4Tech.md
> +For linting we use [flake8](https://flake8.pycqa.org/en/latest/) and [pylint](https://pypi.org/project/pylint/). They have similar functions, but flake8 has some more functionality. These tools are e
fixed

2023-09-05 20:55 UTC, Snorre98 commented on docs/technical/Samf4Tech.md
> +React exploits something called a virtual DOM(document object model) to render HTML(in acctuality something similar to it) content on the web. Historically when webdevelopers wanted to controll how H
fixed

2023-09-07 18:24 UTC, robines commented
Ser veldig bra ut!

2023-09-07 20:07 UTC, evgiz approved these changes

2023-09-07 20:10 UTC, merged