Implement MenuItemComponent for Lyche
Samfundet/Samfundet4 pull request #710
Opened 2023-10-03 20:06 UTC by amaliejvik

Create MenuItemComponent. 
Create Route from Lychee start page to Lyche menu page
#705

2023-10-31 19:15 UTC, amaliejvik commented on frontend/src/Components/MenuItem/MenuItem.tsx
> +      {recommendations ? <div className={styles.item_recommendations}> {recommendations} </div> : <div></div>}
Fixed!

2023-10-31 19:15 UTC, amaliejvik commented on frontend/src/Components/MenuItem/MenuItem.module.scss
> +  // flex-direction: column;
Fixed

2023-10-31 19:15 UTC, amaliejvik commented on frontend/src/Pages/LycheMenuPage/LycheMenuPage.module.scss
> +.noe{
Fixed!

2023-10-31 19:15 UTC, amaliejvik commented on frontend/src/Pages/LycheMenuPage/LycheMenuPage.tsx
> +      ></MenuItem>
Fixed:)

2023-10-31 22:25 UTC, emilte commented on frontend/src/AppRoutes.tsx
>    LycheAboutPage,
Ønsker gjerne å resolve mine egne tråder. Trenger ofte bare et en avsluttende kommentar som signal på at tråden er ferdig :) Det står mer i docs/ i prosjektet

2023-11-16 19:27 UTC, robines commented on frontend/src/Components/MenuItem/MenuItem.module.scss
> +  font-family: 'Lora', sans-serif;
Siden alt unntatt `.item_name` bruker denne font-stacken, er det bedre å sette `font-family` på for eksempel `.menu_item`. Da vil alle elementer under automatisk arve fonten.

Det samme gjelder `color`. Og da får man plutselig fjernet flere unødvendige css-klasser :)

2023-11-16 19:29 UTC, robines commented on frontend/src/Pages/LycheMenuPage/LycheMenuPage.tsx
> +      <br></br>
Hadde vært fint å kunne droppe å bruke `<br>`-taggene. Det regnes som litt bad practice å bruke de for å skape mellomrom. Foretrekker å bruke CSS.
Her kan du for eksempel lage et nytt container-element med en css klasse som skaper mellomrom mellom barne-elementene. F.eks. `.menu_item_container`

2023-11-16 19:30 UTC, robines commented on frontend/src/Pages/LycheMenuPage/LycheMenuPage.tsx
> +    <SultenPage>
Virker som at siden starter litt under navigasjonsbaren. Kunne vi ha endret noe styling for å "dytte" innholdet lenger ned?

2023-11-16 19:31 UTC, robines requested changes
Se kommentarer

2023-12-18 12:16 UTC, magsyg commented
Ooopsi ser ut som godkjente en som branchet ut av denne, fixer disse feilene

2023-12-18 12:31 UTC, emilte commented on frontend/src/Components/SultenPage/SultenPage.module.scss
> +  padding: calc($sulten-navbar-height);
```suggestion
  padding: $sulten-navbar-height;
```

2023-12-18 12:31 UTC, emilte commented on frontend/src/Components/SultenPage/SultenPage.module.scss
> +    padding: calc($sulten-navbar-height);
```suggestion
    padding: $sulten-navbar-height;
```

2023-12-18 13:05 UTC, magsyg commented on frontend/src/Components/SultenPage/SultenPage.module.scss
> +    padding: calc($sulten-navbar-height);
Ti hi

2023-12-18 13:20 UTC, emilte commented
@magsyg Ikke force push

2023-12-19 10:49 UTC, Mathias-a approved these changes

2023-12-19 10:49 UTC, Mathias-a commented on frontend/src/Components/MenuItem/MenuItem.module.scss
> +  font-family: 'Lora', sans-serif;
Er dette en unik font for Lyche menyen? Hvis ikke burde den sikkert arves fra et annet sted

2024-01-09 19:40 UTC, amaliejvik commented on frontend/src/Components/MenuItem/MenuItem.module.scss
> +  font-family: 'Lora', sans-serif;
Sygard fikset!

2024-01-09 19:41 UTC, amaliejvik commented on frontend/src/Pages/LycheMenuPage/LycheMenuPage.tsx
> +      <br></br>
sygard fikset!

2024-01-09 20:01 UTC, amaliejvik commented on frontend/src/Components/MenuItem/MenuItem.module.scss
> +  font-family: 'Lora', sans-serif;
skal være ordnet nå:)

2024-01-09 20:03 UTC, amaliejvik commented on frontend/src/Components/SultenPage/SultenPage.module.scss
> +  padding: calc($sulten-navbar-height);
sygard fikset!

2024-01-31 21:51 UTC, robines approved these changes

2024-02-01 22:21 UTC, robines commented
@amaliejvik Denne ser bra ut, bare å fikse conflict og så merge

2024-02-10 01:26 UTC, magsyg approved these changes

2024-02-10 01:29 UTC, merged

2024-02-10 01:31 UTC, robines commented
@magsyg Ikke merge andre folks PRer.