create lyche menu divider
Samfundet/Samfundet4 pull request #789
Opened 2023-10-24 17:57 UTC by marionlys

2023-10-24 18:03 UTC, robines requested changes

2023-10-24 20:07 UTC, Mathias-a approved these changes

2023-10-24 20:07 UTC, Mathias-a commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.module.scss
> +}
Ville vurdert å hindre denne fra å splittes i to separate linjer hvis det typ er en header på 2 ord

2023-10-25 14:06 UTC, hei98 approved these changes
Ser bra ut for meg

2023-10-25 15:04 UTC, emilte commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.module.scss
> +}
bilde-url kan også flyttes til egen filer med flere slike

2023-10-25 15:06 UTC, emilte commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.tsx
> +interface MenuCategory {
Vi pleier å bruke type
```suggestion
interface LycheMenuDividerProps {
```

2023-10-25 15:06 UTC, emilte commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.tsx
> +export function LycheMenuDivider({ title }: MenuCategory) {
```suggestion
export function LycheMenuDivider({ title }: LycheMenuDividerProps) {
```

2023-10-25 15:07 UTC, emilte approved these changes

2023-10-26 17:05 UTC, marionlys commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.module.scss
> +  font-family: 'LemonMilkLight', sans-serif;
donido

2023-10-26 17:05 UTC, marionlys commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.tsx
> +      <div className={styles.lyche_menu_divider_title}>Menu category</div>
ai fix

2023-10-26 17:08 UTC, marionlys commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.module.scss
> +}
fiksa

2023-10-26 17:08 UTC, marionlys commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.module.scss
> +}
ye

2023-10-26 17:12 UTC, marionlys commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.tsx
> +interface MenuCategory {
done

2023-10-26 17:12 UTC, marionlys commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.tsx
> +export function LycheMenuDivider({ title }: MenuCategory) {
done

2023-10-26 17:33 UTC, Mathias-a commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.module.scss
> +}
Nice

2023-10-26 17:33 UTC, Mathias-a commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.module.scss
> +}
Nice

2023-10-29 12:34 UTC, emilte commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.tsx
> +interface MenuCategory {
Forslaget mitt glemte å endre type

2023-11-07 19:59 UTC, robines approved these changes

2023-11-09 17:50 UTC, marionlys commented on frontend/src/Components/LycheMenuDivider/LycheMenuDivider.tsx
> +interface MenuCategory {
derda

2023-11-09 19:35 UTC, merged