Hide browser's default checkbox
Samfundet/Samfundet4 pull request #806
Opened 2023-11-02 20:06 UTC by JohanneD

Changed css to hide browser's default checkbox.

2023-11-07 20:27 UTC, robines requested changes

2023-11-07 20:27 UTC, robines commented on frontend/src/Components/Checkbox/Checkbox.module.scss
> +  position: absolute;
Bør legge til `position: relative;` til parent-elementet (altså label)

2023-11-16 19:15 UTC, robines approved these changes

2023-11-17 00:44 UTC, emilte approved these changes

2023-11-19 21:33 UTC, merged