680 update opening hours
Samfundet/Samfundet4 pull request #832
Opened 2023-11-09 19:58 UTC by johannegg

Create a custom TimeInput component and use it in OpeningHouersAdminPage to make it look ok in different browsers.

2023-11-09 21:41 UTC, emilte commented on frontend/src/Components/InputTime/InputTime.tsx
Hva er denne komponenten til? Hva skiller den fra TimeDisplay?

2023-11-30 12:21 UTC, robines commented on frontend/src/Components/InputTime/InputTime.tsx
Til blant annet Opening hours, siden `<input type="date">` blir så ulik på tvers av nettlesere.

2023-11-30 12:24 UTC, robines commented on frontend/src/Components/InputTime/InputTime.tsx
> +    e.target.value = '';
Lurer på om det hadde vært mer brukervennlig å ikke cleare input når man trykker inn

2023-11-30 12:28 UTC, robines commented on frontend/src/Components/InputTime/InputTime.tsx
> +      onChange?.(numericValue.padStart(2, '0') + ':' + minute.padStart(2, '0'));
Kan vi legge til støtte for å kunne skrive `00` i hour? Hadde sett litt bedre ut enn kun `0` når man vil ha midnatt

2023-11-30 12:37 UTC, robines commented on frontend/src/Components/InputTime/InputTime.module.scss
> +  box-shadow: 0 0 2px 2px #999999;
`--active` finnes ikke i prosjektet. Fjern outline kanskje? Holder nok med box-shadow

Kan også bruke box-shadow'en jeg nylig merga inn i master fra `ToggleSwitch`-komponenten, for å få litt bedre synergi mellom input-elementene våre. Den finner du [her](https://github.com/Samfundet/Samfundet4/blob/8624e65c25d260dbeebbbd75e98444184bb74ed4/frontend/src/Components/ToggleSwitch/ToggleSwitch.module.scss#L16C1-L16C1). Hvis du velger å bruke den hadde det vært nais om du flytta den ut til `_constants.scss` så flere komponenter kan enkelt bruke den

2023-11-30 12:38 UTC, robines requested changes
Se kommentarer

2023-11-30 16:05 UTC, emilte commented on frontend/src/Components/InputTime/InputTime.tsx
Skjønner. Har vel i ettertid sett at dette er for input, noe den andre ikke er

2023-12-18 13:15 UTC, magsyg commented
Ser ut som noe jeg trenger for Avaiability, nice å få fått denne inn

2023-12-18 13:25 UTC, magsyg commented on frontend/src/Components/InputTime/InputTime.tsx
> +    e.target.value = '';
Fjernet, ville nok blitt ganske irriterende

2023-12-18 14:30 UTC, magsyg commented on frontend/src/Components/InputTime/InputTime.module.scss
> +  box-shadow: 0 0 2px 2px #999999;
Jo visstnok eksiterer det, påvirker utseende dersom det fjernes.
Fjernign vil gi en stygg blå outline

2023-12-18 14:30 UTC, magsyg commented on frontend/src/Components/InputTime/InputTime.tsx
> +      onChange?.(numericValue.padStart(2, '0') + ':' + minute.padStart(2, '0'));
Lagt til

2023-12-18 14:36 UTC, magsyg approved these changes
Looks good!
Should probably implement a joint hour and minute too if desired

2023-12-18 17:42 UTC, magsyg commented
@robines trenger godkjenning for anne PR

2024-01-09 18:32 UTC, merged