first draft of occupied form
Samfundet/Samfundet4 pull request #866
Opened 2023-12-18 17:37 UTC by magsyg

Draft of inputform for occupied periods
Pretty sure this can be bad practice, since we send and create the full list of occupied times each time we update
Will check for create or set is possible

2023-12-18 19:49 UTC, magsyg commented
Waiting for #680

2023-12-18 20:03 UTC, magsyg commented
For det meste ferdig, men trenger input fra "the experts" og den er egt ganske stygg, så skal sette på finstasen. Venter på input for å få videreforbedre denne

2023-12-18 21:26 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +    if (!isNaN(startDt.getTime())) setEndTime(endDt.toLocaleTimeString('no-NO').substring(0, 5));
Det er ikke så lett å se hva som skjer her. Prøv å gjøre det enklere?

2023-12-18 21:27 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }, []);
Hva er planen her?

2023-12-18 21:27 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }, [date, startTime, endTime]);
Jeg tror bør forenkle dette.

2023-12-18 21:28 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +function OccupiedLine({ timeslot, onChange, onDelete, index }: OccupiedLineProps) {
Max 1 komponent per fil. Du kan lage som sub-komponent.

2023-12-18 21:29 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }
Vurder utils.ts fil hvis det passer seg.

2023-12-18 21:35 UTC, emilte commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.module.scss
> +}
Funker det for alle skjermstørrelser?

2023-12-18 21:35 UTC, emilte commented on frontend/src/api.ts
> +  console.log(timeslots);
.

2023-12-18 21:35 UTC, emilte commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
> +            <OccupiedForm recruitmentId={1}></OccupiedForm>
.

2023-12-18 21:35 UTC, emilte commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
> +          <div>
Du kan bruke fragment <>

2023-12-18 21:35 UTC, emilte commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
> +        <Modal isOpen={occupiedModal}>
Kan vurdere å lage sub-komponent for denne.

2023-12-18 21:35 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
Jeg må se over senere, den er litt stor atm

2023-12-18 21:38 UTC, emilte commented on frontend/src/api.ts
Api integrasjon kunne f.eks. vært egen PR. Du hadde fått godkjent med en gang fra meg hvert fall.

2023-12-18 21:40 UTC, emilte commented on frontend/src/api.ts
Sannsynligvis fra noen andre også. Da får du merget litt og litt. Nå risikere du for høy terskel til at noen av de andre orker å se på den.

2023-12-18 21:49 UTC, emilte commented on backend/root/utils/routes.py
![image](https://github.com/Samfundet/Samfundet4/assets/22004178/96d090f6-3503-4286-92c4-06977829fa9e)

Tror pluss knappen bør plasseres et annet sted.
Lurer på om kanskje vanlig knapp er finere enn fluid?

2023-12-18 22:07 UTC, magsyg commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +    if (!isNaN(startDt.getTime())) setEndTime(endDt.toLocaleTimeString('no-NO').substring(0, 5));
Sjekker om den allerede har start_dt, og konverterer den så til lokaltid for å unngå endringer som kan oppstå av det
Dermed får delen av stringen som kan brukes til date

2023-12-18 22:09 UTC, magsyg commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }, []);
Har dependence på timeslot, men problemet med dette er at da vil den loope evig

2023-12-18 22:11 UTC, magsyg commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }, [date, startTime, endTime]);
Litt usikker på om det er mulig, alle sjekkene er nødvendige

2023-12-18 22:21 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +    if (!isNaN(startDt.getTime())) setEndTime(endDt.toLocaleTimeString('no-NO').substring(0, 5));
Det er vanskelig å vite hva dette er `.substring(0, 5)`
Gjerne refaktorer slik at det er enklere å lese.

2023-12-18 22:23 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }, []);
Hvorfor looper den evig?

2023-12-18 22:24 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +export function OccupiedForm({ recruitmentId = 1 }: OccupiedFormProps) {
Er det en generisk komponent, eller hører den bare til RecruitmentPage?

2023-12-18 22:26 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }, [date, startTime, endTime]);
Du kan lage hjelpefunksjoner

2024-01-05 20:20 UTC, Snorre98 commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +    if (!isNaN(startDt.getTime())) setEndTime(endDt.toLocaleTimeString('no-NO').substring(0, 5));
Kanskje legg til kommentarer på linjene:
39 //retrives substring "YYYY-MM-DD" from "YYYY-MM-DDTHH:mm:ss.sssZ"

40 //retrives substring "hh:mm" from "hh:mm:ss"

2024-01-05 20:22 UTC, Snorre98 commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +    if (!isNaN(startDt.getTime())) setEndTime(endDt.toLocaleTimeString('no-NO').substring(0, 5));
Eller reformater koden ca. sånn:
```suggestion
  const formatDate = (date: Date) => date.toISOString().substring(0, 10);
  const formatTime = (date: Date) => date.toLocaleTimeString('no-NO').substring(0, 5);
  const startDt = new Date(timeslot.start_dt);
  const endDt = new Date(timeslot.end_dt);
  setDate(formatDate(startDt));
  setStartTime(formatTime(startDt));
  setEndTime(formatTime(endDt));
```

2024-01-05 20:24 UTC, Snorre98 commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }, [date, startTime, endTime]);
Hjelpefunksjoner samme som f.eks. 
``` TypeScript
const formatDate = (date: Date) => date.toISOString().substring(0, 10);
```

2024-01-05 20:25 UTC, Snorre98 commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +function OccupiedLine({ timeslot, onChange, onDelete, index }: OccupiedLineProps) {
Se https://github.com/Samfundet/Samfundet4/blob/2a5ec044e6817f83d08593292198ad1dedf11cd0/frontend/src/Components/Template

2024-01-05 20:28 UTC, Snorre98 approved these changes
Funker fjell når alle covos. er resolved :)

2024-01-09 20:59 UTC, magsyg commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +    if (!isNaN(startDt.getTime())) setEndTime(endDt.toLocaleTimeString('no-NO').substring(0, 5));
Legger til kommentar, er ganske enkelt

2024-01-09 21:01 UTC, magsyg commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }, []);
Blir cirkular, når timeslot blir oppdatert, så vil den så oppdatere linjen, men når linjen blir oppdatert så oppdaterer den timesloten

2024-01-11 18:15 UTC, magsyg commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }, [date, startTime, endTime]);
Done

2024-01-11 18:16 UTC, magsyg commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +function OccupiedLine({ timeslot, onChange, onDelete, index }: OccupiedLineProps) {
Done

2024-01-11 18:17 UTC, magsyg commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.module.scss
> +}
Yup

2024-01-11 18:18 UTC, magsyg commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
> +            <OccupiedForm recruitmentId={1}></OccupiedForm>
Må legge til todo, ikke lagt til ennå

2024-01-11 18:19 UTC, magsyg commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }
Benytter seg her av state, så vanskelig

2024-01-11 18:38 UTC, magsyg commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
> +          <div>
done

2024-01-11 18:38 UTC, magsyg commented on frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
> +        <Modal isOpen={occupiedModal}>
Done

2024-01-11 18:38 UTC, magsyg commented on backend/root/utils/routes.py
Done

2024-01-11 18:38 UTC, magsyg commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +export function OccupiedForm({ recruitmentId = 1 }: OccupiedFormProps) {
Er nok både på denne siden, og hvor man sjekker sine egne søknader

2024-01-11 19:56 UTC, robines requested changes
Trenger bare å rejecte input når "til" tidspunkt er høyere enn "fra" for å unngå forvirring.

Ellers ser det bra ut!

2024-01-11 20:05 UTC, robines approved these changes

2024-01-11 20:07 UTC, merged

2024-01-12 10:31 UTC, emilte commented on backend/samfundet/serializers.py
> +class OccupiedtimeslotSerializer(serializers.ModelSerializer):
.