Update and post admission fix
Samfundet/Samfundet4 pull request #876
Opened 2023-12-20 22:56 UTC by magsyg

You can now update and fix admission you have sent

2023-12-21 12:54 UTC, emilte commented on frontend/src/Pages/RecruitmentAdmissionFormPage/RecruitmentAdmissionFormPage.tsx
> +    all([
Jeg tror denne er deprecated, du kan bruke Promise.all

2023-12-21 12:55 UTC, emilte commented on backend/samfundet/views.py
> +        Returns a list of all the admissions for an user for a specified recruitment
```suggestion
        Returns a list of all the admissions for a user for a specified recruitment
```

2023-12-21 12:59 UTC, emilte commented on backend/samfundet/views.py
> +        return Response(serializer.data)
hva trenger du dette til?

2023-12-21 13:01 UTC, emilte commented on backend/samfundet/views.py
> +        return Response(request.data)
hva skjer her?

2023-12-21 13:02 UTC, magsyg commented on backend/samfundet/views.py
> +        return Response(serializer.data)
brukes for å få din egen admission for en viss posisjon?
Er get, bare bruker parameter av position og optional user_id dersom man skal se søknaden som intervjuer

2023-12-21 13:04 UTC, magsyg commented on frontend/src/Pages/RecruitmentAdmissionFormPage/RecruitmentAdmissionFormPage.tsx
> +    all([
Done

2023-12-21 13:05 UTC, magsyg commented on backend/samfundet/views.py
> +        Returns a list of all the admissions for an user for a specified recruitment
? er vell an user? lol søkte det oppp engelsk er wack as

2023-12-21 13:06 UTC, magsyg commented on backend/samfundet/views.py
> +        Returns a list of all the admissions for an user for a specified recruitment
Done

2023-12-21 13:09 UTC, magsyg commented on backend/samfundet/views.py
> +        return Response(request.data)
Er post/put i en, men istedenfor å bruke søknad ID, bruker heller stillingen, som jeg antar ikke funker med modelview set automatisk siden den justerer seg for den angitte serializeren sin PK?

2023-12-22 13:24 UTC, Mathias-a commented on backend/samfundet/views.py
> +                prev_admission.save()
prev _admission er litt misvisende? Kanskje ha noe som existing admission? jeg leste prev og tenkte previous, som i forrige admission brukeren sendte. Alternativt legg inn noe kommentar som forklarer greia

2023-12-22 13:24 UTC, Mathias-a commented on backend/samfundet/views.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
Hvorfor gjøres if user_id checken her? Dette viewet er vel for søkeren selv, så man skal ikke kunne gå inn og hente søknader fra en søker (for applicant view), med mindre man er søkeren selv?

2023-12-22 13:24 UTC, Mathias-a commented on backend/samfundet/views.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
Det vil si det er forskjellige felter en søker skal kunne se og redigere en en samfer, så per nå er vel dette splittet i to forskjellige serializers?

2023-12-22 13:24 UTC, Mathias-a commented on frontend/src/Pages/RecruitmentAdmissionFormPage/RecruitmentAdmissionFormPage.tsx
> +        >
Er det et ønske om at man skal kunne endre på en søknad etter den er skrevet? Er ikke sånn per nå, og virker imo litt unaturlig å kunne gjøre det? 
@robines dette vet nok du best

2023-12-22 14:06 UTC, emilte commented on backend/samfundet/views.py
> +                prev_admission.save()
Jeg skjønner ikke at man jobber på noe eksisterende når endepunktet er create jeg

2023-12-22 14:09 UTC, magsyg commented on backend/samfundet/views.py
> +                prev_admission.save()
er post endepunktet, ikke put

2023-12-22 14:11 UTC, magsyg commented on backend/samfundet/views.py
> +                prev_admission.save()
renamet til existing
Er litt enklere enn å splitte det i 2 requests

2023-12-22 14:13 UTC, magsyg commented on backend/samfundet/views.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
Er samme du satt opp for 3 måneder siden
Bare kopierte over i tilfelle det skulle overføres.
Men er vell da for at admins kunne se søknader

2023-12-22 14:15 UTC, magsyg commented on frontend/src/Pages/RecruitmentAdmissionFormPage/RecruitmentAdmissionFormPage.tsx
> +        >
Ser ikke helt hvorfor man skal ikke kunne det, men tenker det kan komme inn når man lager withdraw mekanismen jeg tenkte å sette opp etter dette.

For føler det kanskje er en case om at folk trekker søknaden sin siden de følte den var dårlig skrevet? Og så innser de ikke kan søke igjen? Man kan nok sette opp at det ikke er mulig å endre til søknadsfrist

2023-12-23 22:45 UTC, emilte commented on backend/samfundet/views.py
> +        Returns a list of all the admissions for an user for a specified recruitment
Det har med hvordan det uttales. `User` uttales med J-lyd, da bruker man `an` for enklest mulig uttale.

2023-12-23 22:48 UTC, emilte commented on backend/samfundet/views.py
> +                prev_admission.save()
Jeg skjønner hvordan du tenker, og er delvis enig. Det var slik vi gjorde på rekenett. Men tror vi bør følge det skjemaet DRF gir oss, så unngår vi custom kode. Frontend sørger da bare for å velge riktig handler når den ønsker å sende data. Det er litt forskjell på de ulike http-metodene nemlig.

2023-12-24 11:29 UTC, magsyg commented on backend/samfundet/views.py
> +                prev_admission.save()
Men blir jo ekstra overhead å ha 2 endepunkter når den er unik. Dersom den poster med ekisterende vil den ikke funke, men kan ikke putte uten den. Blir jo at kun en av post og put som kan kjøres, bedre å bare sammensette dem til 1?

2023-12-25 12:10 UTC, robines commented on frontend/src/Pages/RecruitmentAdmissionFormPage/RecruitmentAdmissionFormPage.tsx
> +        >
Jeg syns det er naturlig å skulle kunne redigere søknaden sin. Å fjerne den muligheten etter søknadsfrist høres også logisk ut.

2023-12-27 21:27 UTC, Frenje123 commented
Denne PRen er for at en _søker_ skal kunne oppdatere en søknad som allerede er sendt inn? Gjerne beskriv litt utfyllende i PR description, evt. link til et issue, så er det enklere å reviewe uten kontekst :nerd_face:

2023-12-27 21:31 UTC, magsyg commented
> Denne PRen er for at en _søker_ skal kunne oppdatere en søknad som allerede er sendt inn? Gjerne beskriv litt utfyllende i PR description, evt. link til et issue, så er det enklere å reviewe uten kontekst 🤓

Er generelt å fixe at man kan sende inn søknad, man kan ikke det nå, funket ikke helt. Satt opp også muligheten til å oppdatere søknad, dette vil settes til en frist. Tenkte kanskje søknadsfristen i seg selv

2023-12-27 23:00 UTC, magsyg commented
Endret det nå til put istedet. Navnekonvesjonen er litt fucked, men blir så mye mer overhead å splitte det pga navnekonvesjonen til ModelViewset

2024-01-24 18:05 UTC, robines commented on frontend/src/Pages/RecruitmentAdmissionFormPage/RecruitmentAdmissionFormPage.tsx
> +      getRecruitmentAdmissionForApplicant(positionID as string).then((res) => {
Burde sjekke om bruker er logget inn før vi sender denne

2024-01-24 18:07 UTC, robines requested changes
Se kommentar

2024-01-25 00:00 UTC, emilte commented on frontend/src/Pages/RecruitmentAdmissionFormPage/RecruitmentAdmissionFormPage.tsx
> +      getRecruitmentAdmissionForApplicant(positionID as string).then((res) => {
Vi har ikke kommet dit ennå, men backend er nok den som skal sjekke alt dette. Frontend trenger ikke bry seg med noe annet enn visuell opplevelse for bruker.

2024-01-25 17:52 UTC, magsyg commented
@robines its done

2024-01-25 17:55 UTC, robines approved these changes
Ser bra ut!

2024-02-15 00:02 UTC, emilte commented on backend/samfundet/views.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
Klarer serializeren å gjøre dette selv? Da slipper vi custom her

2024-02-15 00:06 UTC, emilte commented on backend/samfundet/views.py
> +        return Response(serializer.data)
Jeg tror ikke vi trenger å skrive over så mye. Filtrer i get_queryset

2024-02-15 00:08 UTC, emilte commented on backend/samfundet/views.py
>      def list(self, request: Request) -> Response:
Mye av dette tror jeg er helt unødvendig

2024-02-15 17:47 UTC, magsyg commented on backend/samfundet/views.py
> +        return Response(serializer.data)
Er jo for enkelt? Queryset er jo litt forskjellig

2024-02-15 17:48 UTC, magsyg commented on backend/samfundet/views.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
Vanskelig når den benytter seg av url?

2024-02-15 18:07 UTC, Snorre98 approved these changes
Looks good to me

2024-02-15 18:09 UTC, merged