Add withdrawn and created_at fields for admission
Samfundet/Samfundet4 pull request #886
Opened 2023-12-24 13:53 UTC by magsyg

2023-12-27 15:27 UTC, emilte commented on backend/samfundet/models/recruitment.py
> +            self.recruiter_status = 3
Du kan legge inn unit test å dette

2023-12-27 18:45 UTC, magsyg commented on backend/samfundet/models/recruitment.py
> +            self.recruiter_status = 3
Will do må bare få inn choices filen

2023-12-27 20:58 UTC, emilte commented on backend/samfundet/models/recruitment.py
> +            self.recruiter_status = 3
Hvorfor må du vente på den?

2023-12-27 21:18 UTC, magsyg commented on backend/samfundet/models/recruitment.py
> +            self.recruiter_status = 3
Idk spiller vell egt ikke rolle hvilke rettnign som blir tatt

2023-12-29 13:27 UTC, emilte commented on backend/samfundet/models/recruitment.py
> +            self.recruiter_status = 3
Bruk konstanter, 1 og 3 gir ingen mening

2023-12-29 13:28 UTC, emilte commented on backend/samfundet/models/tests/test_recruitment.py
> +        assert fixture_recruitment_admission.recruiter_priority == 1
konst

2023-12-29 14:37 UTC, magsyg commented on backend/samfundet/models/tests/test_recruitment.py
> +        assert fixture_recruitment_admission.recruiter_priority == 1
Yup, vet, er i fisket i PR for model choices

2024-01-05 21:51 UTC, Snorre98 approved these changes
Hvis ting løser seg når den andre PRen kommer inn blir det sikkert bra :)

2024-01-06 14:25 UTC, magsyg commented on backend/samfundet/models/recruitment.py
> +            self.recruiter_status = 3
Done

2024-01-06 14:25 UTC, magsyg commented on backend/samfundet/models/tests/test_recruitment.py
> +        assert fixture_recruitment_admission.recruiter_priority == 1
Done

2024-01-15 16:45 UTC, robines requested changes
Se kommentar

2024-01-15 17:27 UTC, magsyg commented on backend/samfundet/migrations/0005_recruitmentadmission_created_at_and_more.py
> +        ("samfundet", "0004_campus_user_campus"),
Done @robines

2024-01-25 14:24 UTC, robines approved these changes

2024-01-25 14:25 UTC, merged