Add Frontend for reservation Frontend viewer
Samfundet/Samfundet4 pull request #889
Opened 2023-12-25 20:46 UTC by magsyg

![bilde](https://github.com/Samfundet/Samfundet4/assets/56266980/985000b1-09ed-4a0c-b33a-43818b6e365f)

First draft, uses flex, maybe dumb

2023-12-25 21:38 UTC, magsyg commented
Ikke koblet opp mot backend, men vil gjøre det etter dette er gjennom

2023-12-25 21:39 UTC, magsyg commented
![bilde](https://github.com/Samfundet/Samfundet4/assets/56266980/25ef621d-a7a9-4179-8fa7-f698501cdeaa)

2023-12-25 23:22 UTC, emilte commented on frontend/src/PagesAdmin/SultenAdminPage/components/ReservationTableRow/ReservationTableRow.tsx
> +};
Kan flyttes til ./types.ts

2023-12-25 23:25 UTC, emilte commented on frontend/src/PagesAdmin/SultenAdminPage/components/Reservation/Reservation.module.scss
> +  display: none;
Muligens ikke uu kompatibelt. Passer invisible, hidden eller opacity bedre?

2023-12-25 23:26 UTC, emilte commented on frontend/src/PagesAdmin/SultenAdminPage/components/ReservationTableRow/ReservationTableRow.tsx
> +  }, []);
Trenger sannsynligvis forenklinger/forklaringer.

2023-12-25 23:28 UTC, emilte commented on frontend/src/PagesAdmin/SultenAdminPage/components/ReservationTableRow/ReservationTableRow.tsx
> +  }, []);
Ingen dependency?

2023-12-26 11:16 UTC, magsyg commented on frontend/src/PagesAdmin/SultenAdminPage/components/ReservationTableRow/ReservationTableRow.tsx
> +  }, []);
Ikke ennå, er bare testdata

2023-12-26 11:19 UTC, magsyg commented on frontend/src/PagesAdmin/SultenAdminPage/components/Reservation/Reservation.module.scss
> +  display: none;
hva mener du med dette? er det for at den ikke skal tabbe inn i den?
Er et tooltip typ skjønner ikke hvorfor den skal tabbes til. Hjelp jo og totalskjule den fra html

2023-12-27 12:29 UTC, emilte commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +    const tables = [
Kan flyttes til ./utils.ts no?

2023-12-27 12:29 UTC, emilte commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const dateIterator = (days: number) => {
Helst bruk `function`

2023-12-27 12:29 UTC, emilte commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const goToToday = () => {
.

2023-12-27 12:30 UTC, emilte commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +      Add text
t

2023-12-27 12:30 UTC, emilte commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTableRow/types.ts
> +export type columns = {
```suggestion
export type Column = {
```

2023-12-27 12:32 UTC, emilte reviewed
Begynner å bli en anelse stort, du får sannsynligvis ikke like kjapp review av andre som du får på de små

2024-01-05 21:56 UTC, Snorre98 approved these changes
Ser bra ut :) Fix for convo. resolve

2024-01-06 14:34 UTC, magsyg commented on frontend/src/PagesAdmin/SultenAdminPage/components/ReservationTableRow/ReservationTableRow.tsx
> +};
done

2024-01-06 14:35 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +    const tables = [
venter til kobling med backend

2024-01-06 14:38 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +    const tables = [
Vanskelig også med state?

2024-01-06 14:39 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const dateIterator = (days: number) => {
done

2024-01-06 14:39 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const goToToday = () => {
Done

2024-01-06 14:40 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +      Add text
er en todo

2024-01-06 14:41 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTableRow/types.ts
> +export type columns = {
Done

2024-02-01 22:04 UTC, robines commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const dateIterator = (days: number) => {
Resolver

2024-02-01 22:04 UTC, robines commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const goToToday = () => {
Resolver

2024-02-01 22:11 UTC, emilte commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +    const tables = [
Det er bare et statisk objekt. Den trenger ikke ta plass her, ligger fint i utils :)

2024-03-25 14:22 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +    <Button theme="success" rounded={true} onClick={() => navigate(ROUTES.frontend.admin_gangs_create)}>
Done

2024-03-25 14:23 UTC, magsyg commented on frontend/src/AppRoutes.tsx
> +        <Route
Done

2024-03-25 14:24 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const [dayInfo, setDayInfo] = useState<SultenDayDto>({} as SultenDayDto);
Tror det blir noe konst av det og ikke dynamisk

2024-03-25 14:24 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/Reservation/Reservation.tsx
> +      onClick={() => alert('add edit reservation')}
Blir vell lagt til når den er oppe

2024-03-25 14:27 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  function dateIterator(days: number) {
Skjønner ikke dette

2024-03-25 14:30 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/Reservation/Reservation.tsx
> +  // The event being edited
er bare rest som skal fjernes, fjernet

2024-03-25 14:32 UTC, magsyg commented on frontend/src/dto.ts
> +  venue?: number;
Partial setter vell alle feltene til optional?
Tror det kanskje ikke er lurt da

2024-03-25 14:33 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/utils.ts
Kan nok brukes, men dette funker like greit

2024-03-25 14:36 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.tsx
> +          {new Date().getDate() != sultenDay.date.getDate() && (
første enig, men andre uenig med, hvor siste er mer eller mindre det samme som den andre

2024-03-25 14:37 UTC, magsyg commented on frontend/src/dto.ts
> +export type SultenDayDto = {
Done

2024-03-25 14:37 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.tsx
> +  // The event being edited
Fjernet

2024-03-25 19:50 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const [dayInfo, setDayInfo] = useState<SultenDayDto>({} as SultenDayDto);
Ok, tenker du at det uansett skal et API kall inn her for å sette tilstanden?

2024-03-25 19:51 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/Reservation/Reservation.module.scss
> +
Jeg tror det er noe som kommer til å komme opp, men det er ikke så viktig akkurat nå. Så det kan være greit å ha et issue på det slik at vi har oversikt.

2024-03-25 20:15 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  function dateIterator(days: number) {
Forslaget, som oppdaterer dataIterator, er en tryggere måte å sette tilstand fordi tilstanden kun oppdateres hvis den  nyeste tilstande (currentDateInfo) er klar. Det kan være greit i tilfeller hvor tilstanden endrer seg enten veldig raskt, eller asynkront.

2024-03-25 20:27 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.tsx
> +          {new Date().getDate() != sultenDay.date.getDate() && (
Jeg tenker at man like gjerne kan gjøre begge til konstaner, hvis man gjør den ene til en konstant. Kan hende jeg misforstår hva du mener.

2024-03-25 20:50 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/Reservation/Reservation.module.scss
> +
Jeg syns bare det ble litt grått. 

Hva med å bruke $grey-4 for bakgrunn i .row i 
ReservationTableRow.module.scss og for bakgrunn i .timeHeader i ReservationTable.moduel.scss?

Kanskje legge til @include flex-column-center i .time i ReservationTable,module.scss for å senterer tabel header teksten.

2024-03-25 20:55 UTC, Snorre98 requested changes

2024-03-25 20:55 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTableRow/ReservationTableRow.module.scss
> +  background-color: $grey-3;
```suggestion
  background-color: $grey-4;
```

2024-03-25 20:55 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.module.scss
> +  background-color: $grey-3;
```suggestion
  background-color: $grey-4;
```

2024-03-25 20:55 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.module.scss
> +}
```suggestion
  @include flex-column-center
}
```

2024-03-25 20:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/Reservation/Reservation.module.scss
> +
Se nye kode-forslag

2024-03-25 21:28 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.module.scss
> +  background-color: $grey-3;
Hvorfor skal denne stylingen fixes?

2024-03-25 21:28 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTableRow/ReservationTableRow.module.scss
> +  background-color: $grey-3;
hvorfor skal denne stylingen fikses?

2024-03-25 21:29 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.module.scss
> +}
Tror styling kanskje ikke det viktigste nå, hovedsakelig å få det inn er viktigst, kan oppdatere styling senere

2024-03-25 21:30 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.tsx
> +          {new Date().getDate() != sultenDay.date.getDate() && (
today ble constant, siden den er grei, kan nok flyttes senere

2024-03-25 21:32 UTC, magsyg commented on frontend/src/dto.ts
> +  venue?: number;
Kan komme en PR på dette senere, vet ikke helt hvorfor det er satt her, for den poster ikke noe her

2024-03-25 21:34 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const [dayInfo, setDayInfo] = useState<SultenDayDto>({} as SultenDayDto);
hmm kan nok uansett settes til det, men usikker på om det kommer til å bli konstant, men tanken er vell at den også får tak i åpningstiden for den dagen også

2024-03-25 21:35 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/Reservation/Reservation.module.scss
> +
Kan endres en annen gang, ikke så viktig med styling for nå

2024-03-27 16:47 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.module.scss
> +}
Var bare forslag siden du ikke lagde issue på det. Hvis du er fornøyd med hvordan det er så er det good.

2024-03-27 17:00 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.module.scss
> +}
Kan lage issue på det!
Er shit på design, målet er bare å sette opp den generelle base som andre kan fikse oppi dersom de ikke liker det

2024-03-27 17:00 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/Reservation/Reservation.tsx
> +      onClick={() => alert('add edit reservation')}
Kan legge det til:)

2024-03-28 18:51 UTC, emilte commented on frontend/src/dto.ts
> +  venue?: number;
Morsomt å se at Mathias fortsatt følger med

2024-04-02 16:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const [dayInfo, setDayInfo] = useState<SultenDayDto>({} as SultenDayDto);
Hva blir det til? Mitt forslag setter bare initial state som et objekt med data. Siden det er en useState så vil den jo oppdatere seg når det kommer data fra API-kall, det blir ikke konstant verdi. Jeg foreslo dette fordi jeg syns det gjør det tydligere hva som skjer.

2024-04-02 17:01 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  const [dayInfo, setDayInfo] = useState<SultenDayDto>({} as SultenDayDto);
Er bare placeholder for nå, blir lagt til mer senere, skal være basert på dag og åpningstid, men PRen blir for stor dersom det blir lagt til her

2024-04-02 17:02 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTable/ReservationTable.tsx
> +          {new Date().getDate() != sultenDay.date.getDate() && (
lgtm

2024-04-09 18:40 UTC, Snorre98 approved these changes

2024-04-09 19:14 UTC, robines approved these changes

2024-04-09 19:14 UTC, robines commented
@magsyg Klar til å merges

2024-04-10 21:43 UTC, emilte commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  }, []);
deps

2024-04-10 21:46 UTC, emilte commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTableRow/ReservationTableRow.tsx
> +    setCols(colList);
Bør kanskje ha func og dokumentasjon

2024-04-10 21:46 UTC, emilte commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTableRow/ReservationTableRow.tsx
> +  }
kan flyttes ut

2024-04-11 11:50 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTableRow/ReservationTableRow.tsx
> +  }
Done

2024-04-11 12:01 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/components/ReservationTableRow/ReservationTableRow.tsx
> +    setCols(colList);
La til dokumentasjon

2024-04-11 12:02 UTC, magsyg commented on frontend/src/PagesAdmin/SultenReservationAdminPage/SultenReservationAdminPage.tsx
> +  }, []);
Er for test data, blir fikset senere

2024-04-11 12:07 UTC, merged