Feature/sultenmenuformadmin
Samfundet/Samfundet4 pull request #895
Opened 2023-12-26 14:43 UTC by magsyg

closes #893 

Depends on #892

2024-02-06 20:24 UTC, aTrueYety commented on backend/samfundet/serializers.py
> -class MenuItemSerializer(serializers.ModelSerializer):
Hvorfor delte du denne i read og write? 👉 👈

2024-02-06 20:48 UTC, aTrueYety reviewed
'Mat preferanser' i formet er en mutlti select i backend men en single select dropdown i frontend. 

'kattegori' og 'matpreferanse' feltene gjør ikke noe med dataen når du lager og oppdaterer retter. De laster heller ikke inn tidligere data fra backend når du skal endre på retter.

Jeg ser det er et order felt i backend men jeg ser ikke helt hva den blir brukt til.

2024-02-15 22:08 UTC, Snorre98 approved these changes

2024-02-15 22:32 UTC, emilte commented on backend/samfundet/views.py
> +    permission_classes = (DjangoModelPermissionsOrAnonReadOnly, )
enklere med liste men

2024-02-15 22:34 UTC, emilte commented on frontend/src/dto.ts
> +  food_category: FoodCategoryDto | number;
Vi burde egt splitte i read types dto som mottas fra api, og data dto som sendes til backend. De er ofte forskjellige. Ny oppgave som splitter disse hadde vært fint.

2024-02-15 22:37 UTC, emilte commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +      getFoodCategorys()
getFoodCategories*?

2024-02-15 22:37 UTC, emilte commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
bare legg til `t`

2024-02-15 22:38 UTC, emilte commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +  const title = (id ? t(KEY.common_edit) : t(KEY.common_create)) + ' ' + lowerCapitalize(`${t(KEY.sulten_dishes)}`);
Helst legg over effects

2024-02-15 22:38 UTC, emilte commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +  const submitText = id ? t(KEY.common_save) : t(KEY.common_create);
Gjerne øverst

2024-02-15 22:39 UTC, emilte commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +  }
Gjerne rett over siste markdown

2024-02-15 22:40 UTC, emilte commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +  // Loading.
Du kan legge dette rett under effects
```suggestion
  // Guards.
```

2024-03-25 12:29 UTC, magsyg commented
> 'Mat preferanser' i formet er en mutlti select i backend men en single select dropdown i frontend.
> 
> 'kattegori' og 'matpreferanse' feltene gjør ikke noe med dataen når du lager og oppdaterer retter. De laster heller ikke inn tidligere data fra backend når du skal endre på retter.
> 
> Jeg ser det er et order felt i backend men jeg ser ikke helt hva den blir brukt til.

Dette er noe som er en TODO på, ettersom vi ikke har noe fungerende multiselect

2024-03-25 12:31 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Vi har ignorert disse i alle andre PR til nå, skal det legges til nå? tror det kom enda fler feil pga dette, men husker ikke hva.

2024-03-25 12:31 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +  const title = (id ? t(KEY.common_edit) : t(KEY.common_create)) + ' ' + lowerCapitalize(`${t(KEY.sulten_dishes)}`);
Done

2024-03-25 12:32 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +  const submitText = id ? t(KEY.common_save) : t(KEY.common_create);
done

2024-03-25 14:10 UTC, magsyg commented
Fjernet validation fra custombaseserializer, etterom det ikke gjorde noe
Response ble gitt uansett
men det som ville skje var at den ville reagere på put requests og si at felt bommet på unique constraints på eget objekt

2024-03-25 14:11 UTC, magsyg commented on frontend/src/dto.ts
> +  food_category: FoodCategoryDto | number;
Lager egen PR for noe sånt senere

2024-03-25 15:39 UTC, emilte commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
det burde nok legges til

2024-03-25 15:40 UTC, emilte commented on backend/root/utils/mixins.py
> -        return attrs
fordi?

2024-03-25 15:56 UTC, Snorre98 requested changes

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuAdminPage/SultenMenuAdminPage.tsx
Fjern consol logging på linje 30, 35, og 44 hvis det ikke trengs lengre.

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuAdminPage/SultenMenuAdminPage.tsx
> +      menuItem.food_category ? dbT(menuItem.food_category as FoodCategoryDto, 'name') : '',
```suggestion
      menuItem.food_category ? dbT(menuItem.food_category as FoodCategoryDto, 'name') : 'Missing type!',
```
Hvis jeg forstår det rett

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuAdminPage/SultenMenuAdminPage.tsx
>        <Button theme="success" rounded={true} onClick={() => alert('TODO create menu')}>
Sjekk om det finnes et issue på "create menu" funksjonalitet. Lag issue på "create sulten menu for admin" hvis det ikke finnes issue og hvis du ikke jobber på det.

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +    food_preferences: [], // TODO add on multiselect
Vi har en multiselector.

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +          console.error(error);
Fjern hvis de ikke trengs

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +          console.error(error);
fjern hvis den ikke trengs

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +          console.error(data);
Fjern hvis den ikke trengs

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +          console.error(error);
Fjern hvis den ikke trengs

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +          console.error(error);
Fjern hvis den ikke trengs

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +            navigate(ROUTES.frontend.admin_recruitment);
Skjønner ikke hva som skjer her, hvorfor blir man sendt til recruitment siden om denne får 404 i response? 
Det trigges jo en toast response. Så brukeren får vite at noe gikk galt i det minste.

Fjern kommentaren på l95 hvis toast løser dette

2024-03-25 15:56 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +      data.food_preferences = []; // TODO Ignore until multiselect is added
Vi har multiselect: 
https://github.com/Samfundet/Samfundet4/blob/65bb3d31c6dfb68998d5fbf1e66d7a069bbc7c3e/frontend/src/Components/MultiSelect

2024-03-25 15:57 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuAdminPage/SultenMenuAdminPage.tsx
Innså dette ikke er endringer som ble med i denne PR-en, men nice om du gjør det uansett.

2024-03-25 15:59 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +  // Loading.
Done

2024-03-25 15:59 UTC, magsyg commented on backend/root/utils/mixins.py
> -        return attrs
Den ikke gjør noe, raisesene blir gitt uansett.
Men dette gjør at put gir unique error på samme verdi

2024-03-25 16:03 UTC, magsyg commented on backend/samfundet/serializers.py
> +    food_preferences = FoodPreferenceSerializer(many=True, read_only=True)  # Todo make this work with post
Done

2024-03-25 16:04 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuAdminPage/SultenMenuAdminPage.tsx
Done

2024-03-25 16:05 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuAdminPage/SultenMenuAdminPage.tsx
> +      menuItem.food_category ? dbT(menuItem.food_category as FoodCategoryDto, 'name') : '',
Er bare error for nå, må fikses i større PR med relation post

2024-03-25 16:05 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuAdminPage/SultenMenuAdminPage.tsx
>        <Button theme="success" rounded={true} onClick={() => alert('TODO create menu')}>
Dette er create menu item, litt feil navn bare

2024-03-25 16:06 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +    food_preferences: [], // TODO add on multiselect
Funker ikke ennå

2024-03-25 16:06 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +          console.error(error);
Done

2024-03-25 16:07 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +          console.error(error);
Done

2024-03-25 16:07 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +          console.error(error);
Done

2024-03-25 16:07 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +          console.error(error);
Done

2024-03-25 16:07 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +            navigate(ROUTES.frontend.admin_recruitment);
fikset

2024-03-25 16:08 UTC, magsyg commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +      data.food_preferences = []; // TODO Ignore until multiselect is added
Funker ikke

2024-03-27 17:57 UTC, emilte commented on backend/root/utils/mixins.py
> -        return attrs
Vi har hatt samme problem på jobb.
Bruk dette
<img width="891" alt="image" src="https://github.com/Samfundet/Samfundet4/assets/22004178/7f4b56ac-cd5b-4df2-a0db-26f9598d6f29">

2024-04-02 17:29 UTC, Snorre98 commented on frontend/src/PagesAdmin/SultenMenuAdminPage/SultenMenuAdminPage.tsx
>        <Button theme="success" rounded={true} onClick={() => alert('TODO create menu')}>
lgtm

2024-04-09 19:48 UTC, Snorre98 approved these changes

2024-04-10 21:49 UTC, emilte commented on frontend/src/PagesAdmin/SultenMenuAdminPage/SultenMenuAdminPage.tsx
> +  const navigate = useNavigate();
usecustomnavigate

2024-04-11 14:47 UTC, robines commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +          console.error(error);
@Snorre98 Ser ut til å ha blitt fjernet, resolver

2024-04-11 14:57 UTC, robines commented on frontend/src/PagesAdmin/SultenMenuItemFormAdminPage/SultenMenuItemFormAdminPage.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
@magsyg @emilte Burde legges til ja, og det kjører helt fint uten feil for meg. Har lagt det til.

2024-04-11 15:00 UTC, robines commented on frontend/src/PagesAdmin/SultenMenuAdminPage/SultenMenuAdminPage.tsx
> +  const navigate = useNavigate();
@emilte Gjort

2024-04-11 15:01 UTC, robines commented on backend/root/utils/mixins.py
> -        return attrs
@magsyg Tanker?

2024-04-11 17:20 UTC, magsyg commented on backend/root/utils/mixins.py
> -        return attrs
Lager issue på dette

2024-04-16 20:32 UTC, emilte commented on backend/root/utils/mixins.py
> -        return attrs
Prøv som regel å lenke til issues som opprettes i tråder, så ser man at det er gjort.

2024-06-16 16:44 UTC, merged