add phone number field for frontend
Samfundet/Samfundet4 pull request #896
Opened 2023-12-26 15:36 UTC by magsyg

2024-01-05 22:15 UTC, Snorre98 approved these changes
Se kommentar. Ellers good :)

2024-01-05 22:15 UTC, Snorre98 commented on frontend/src/Components/PhoneNumberField/PhoneNumberField.tsx
> +      placeholder={placeholder}
burde noe av dette egentlig "hardkodes" (+ translation), f.eks. placeholder og label? Hvis det ikke er vanlig, bare resolve :)

2024-02-01 21:11 UTC, robines requested changes

2024-02-01 21:11 UTC, robines commented on frontend/src/constants/constants.ts
> +export const PHONENUMBER_REGEX = new RegExp('^(\\+?\\(?\\d{3}\\)?[-\\s\\.]?)?\\d{3}[-\\s\\.]?\\d{4,6}$');
Regexen burde være mye enklere. Gjerne bare kopier slik det ble gjort på samf3

https://github.com/Samfundet/Samfundet/blob/master/app/models/applicant.rb#L31

2024-02-02 17:27 UTC, magsyg commented on frontend/src/constants/constants.ts
> +export const PHONENUMBER_REGEX = new RegExp('^(\\+?\\(?\\d{3}\\)?[-\\s\\.]?)?\\d{3}[-\\s\\.]?\\d{4,6}$');
Den er vell litt for enkel, og denne er knyttet opp mot den som er i backend, dersom begge skal endres tenker jeg det gjennomføres i en annen PR

2024-02-02 17:28 UTC, magsyg commented on frontend/src/Components/PhoneNumberField/PhoneNumberField.tsx
> +import { InputField, InputFieldProps } from '../InputField';
Done

2024-02-02 17:53 UTC, robines commented on frontend/src/constants/constants.ts
> +export const PHONENUMBER_REGEX = new RegExp('^(\\+?\\(?\\d{3}\\)?[-\\s\\.]?)?\\d{3}[-\\s\\.]?\\d{4,6}$');
Vi har hatt flere diskusjoner på det tidligere, og jeg står fortsatt for at det er **mye** bedre å ha en enkel regex som ikke er for streng når det gjelder telefonnummer. Ulempene med å ha en for streng regex er mye verre enn ulempene med å akseptere potensielt ugyldige telefonnummer.

Men siden det allerede er definert i backend er jeg enig, jeg lager en ny issue på det.

2024-02-02 17:58 UTC, robines requested changes

2024-02-02 17:58 UTC, robines commented on frontend/src/Components/PhoneNumberField/PhoneNumberField.tsx
> +      error={isCorrectFormat ? 'Not a valid phonenumber' : error}
Trenger translation. Og phone number er to ord

2024-02-02 20:01 UTC, magsyg commented on frontend/src/Components/PhoneNumberField/PhoneNumberField.tsx
> +      error={isCorrectFormat ? 'Not a valid phonenumber' : error}
Done didely done

2024-02-02 20:17 UTC, robines approved these changes

2024-02-02 20:21 UTC, merged