Feature/recruitmentstatsmodel
Samfundet/Samfundet4 pull request #898
Opened 2023-12-28 13:38 UTC by magsyg

Added own model for aggregated stats
Will reduce needed computations for each display
Will be kept after anonymization(?)

Only added the 2 most basic fields of total applicants and admissions.
Are activated by signals so latency of updating stats should not be visible from frontend

2023-12-29 13:10 UTC, emilte commented on backend/samfundet/models/recruitment.py
> +            self.statistics.save()
get_or_create?

2023-12-29 14:39 UTC, magsyg commented on backend/samfundet/models/recruitment.py
> +            self.statistics.save()
Poenget er å lagre for å oppdatere statistikken

2023-12-29 14:48 UTC, magsyg commented on backend/samfundet/signals.py
> +        RecruitmentStatistics.objects.get_or_create(recruitment=instance)[0]
Done

2023-12-29 14:48 UTC, magsyg commented on backend/samfundet/models/recruitment.py
> +            self.statistics.save()
oppdaterte uansett til get or create, ble litt cleanere

2024-01-01 03:42 UTC, emilte commented on backend/samfundet/conftest.py
> +    # Extra user if neeed
```suggestion
    # Extra user if needed.
```

2024-01-01 03:44 UTC, emilte commented on backend/samfundet/signals.py
> +    """Ensures stats are createed when an recruitment is created"""
```suggestion
    """Ensures that stats are created when a recruitment is created."""
```

2024-01-01 03:45 UTC, emilte commented on backend/samfundet/signals.py
Kan ikke disse enkelt gjøres i save metodene?

2024-02-15 22:22 UTC, Snorre98 approved these changes
Fix typos?

2024-03-25 12:18 UTC, magsyg commented on backend/samfundet/conftest.py
> +    # Extra user if neeed
Done

2024-03-25 14:17 UTC, Snorre98 commented on backend/samfundet/conftest.py
> +    # Extra user if neeed
Er det letter å få med seg hvis man legger på en @, @magsyg ?

2024-04-01 13:02 UTC, tiniuspre requested changes

2024-04-01 13:02 UTC, tiniuspre commented on backend/samfundet/signals.py
> +def create_recruitment_statistics(sender: Recruitment, instance: Recruitment, created: bool, **kwargs: Any) -> None:  # noqa FBT001
```suggestion
def create_recruitment_statistics(sender: Recruitment, instance: Recruitment, *, created: bool, **kwargs: Any) -> None: 
```

2024-04-01 13:02 UTC, tiniuspre commented on backend/samfundet/signals.py
> +def admission_created(sender: RecruitmentAdmission, instance: RecruitmentAdmission, created: bool, **kwargs: Any) -> None:  # noqa FBT001
```suggestion
def admission_created(sender: RecruitmentAdmission, instance: RecruitmentAdmission, *, created: bool, **kwargs: Any) -> None:
```

2024-04-01 14:55 UTC, emilte commented on backend/samfundet/conftest.py
> +    # Extra user if neeed
Jeg får mails, det går fint. Har bare ikke sett gjennom dem. Hvis jeg ikke svarer er det helt greit for meg å mase, da får jeg nye timestamps

2024-04-01 14:57 UTC, emilte commented on backend/samfundet/signals.py
> +def create_recruitment_statistics(sender: Recruitment, instance: Recruitment, created: bool, **kwargs: Any) -> None:  # noqa FBT001
Dette er signaturen til signals, usikker på om man kan tvinge kildekode inn i named args

2024-04-02 17:10 UTC, magsyg commented on backend/samfundet/models/recruitment.py
> +    def save(self, *args: tuple, **kwargs: dict) -> None:  # noqa: C901
Dette er ignorert overalt, er ikke noe man kan overskride, dritt ruff regel

2024-04-02 17:10 UTC, magsyg commented on backend/samfundet/models/recruitment.py
> +        # TODO make uneditable/unsavable after being anonymized
Done

2024-04-02 17:12 UTC, magsyg commented on backend/samfundet/signals.py
> +def admission_created(sender: RecruitmentAdmission, instance: RecruitmentAdmission, created: bool, **kwargs: Any) -> None:  # noqa FBT001
Hva gjør de *?

2024-04-09 19:54 UTC, Snorre98 commented on backend/samfundet/signals.py
> +def admission_created(sender: RecruitmentAdmission, instance: RecruitmentAdmission, created: bool, **kwargs: Any) -> None:  # noqa FBT001
@tiniuspre

2024-04-09 19:56 UTC, Snorre98 commented on backend/samfundet/models/recruitment.py
> +        # TODO make uneditable/unsavable after being anonymized
@magsyg

2024-04-09 19:56 UTC, Snorre98 commented on backend/samfundet/models/recruitment.py
> +    def save(self, *args: tuple, **kwargs: dict) -> None:  # noqa: C901
@magsyg

2024-04-09 23:21 UTC, tiniuspre commented on backend/samfundet/signals.py
> +def admission_created(sender: RecruitmentAdmission, instance: RecruitmentAdmission, created: bool, **kwargs: Any) -> None:  # noqa FBT001
https://docs.astral.sh/ruff/rules/boolean-type-hint-positional-argument/

2024-04-09 23:24 UTC, tiniuspre commented on backend/samfundet/models/recruitment.py
> +    def save(self, *args: tuple, **kwargs: dict) -> None:  # noqa: C901
Neida, sørger bare for at funksjoner mer leselig. Grunnen til at det ignoreres ganske mange steder er fordi det er vrient å fikse på det i senere tid, altså når vi introduserte ruff.

Personlig så foretrekker jeg å heller ha flere funksjoner.

2024-04-11 15:03 UTC, robines commented on backend/samfundet/signals.py
> +def create_recruitment_statistics(sender: Recruitment, instance: Recruitment, created: bool, **kwargs: Any) -> None:  # noqa FBT001
@tiniuspre Tanker?

2024-04-11 15:19 UTC, tiniuspre commented on backend/samfundet/signals.py
> +def create_recruitment_statistics(sender: Recruitment, instance: Recruitment, created: bool, **kwargs: Any) -> None:  # noqa FBT001
Mener det ikke vil ødelegge noenting, ganske sikker på at det ikke vil bli error. Er bare nice med minst mulig ignorering av linter så ikke så mega farlig om det blir sånn jeg foreslo

2024-04-30 19:05 UTC, tiniuspre approved these changes

2024-04-30 19:06 UTC, merged