add register tests
Samfundet/Samfundet4 pull request #906
Opened 2024-01-09 13:19 UTC by magsyg

Added tests for register

2024-01-09 13:53 UTC, magsyg commented
@emilte hva er denne pipeline erroren? Python ikke eksiterer?

2024-01-09 16:36 UTC, emilte commented
> @emilte hva er denne pipeline erroren? Python ikke eksiterer?

Github har hatt performance issues i dag. Kanskje bare prøv på nytt

2024-02-15 23:03 UTC, Snorre98 commented
@magsyg se kommentarer

2024-02-15 23:15 UTC, emilte commented on backend/samfundet/serializers.py
@magsyg Du må begynne å publisere PR i #review og mase på folk før vi åpner flere PR. Kjør sammen med folk og forklar så går det fortere. Det er overload av kode for tiden.

2024-02-15 23:17 UTC, emilte commented on backend/samfundet/serializers.py
> +            raise serializers.ValidationError(errors)
Sjekkes ikke dette uansett med db constraints?

2024-03-25 15:44 UTC, magsyg commented on backend/samfundet/serializers.py
> +            raise serializers.ValidationError(errors)
Den kaster Integrity error som det ser ikke ut som pytest takler, for den erroren krasjer bare hele systemet.
Som kommer av User er litt spesiell klasse, og da vanskligere å cleane

2024-03-27 14:49 UTC, tiniuspre requested changes

2024-03-27 14:49 UTC, tiniuspre commented on backend/samfundet/tests/test_views.py
> +        }
post_data er veldig duplicat

Bedre:

```
class EnKlasse:
   post_data = {}

   def noe():
      post_data[key]
      ...
```

2024-03-27 16:07 UTC, magsyg commented on backend/samfundet/tests/test_views.py
> +        }
Done

2024-03-27 16:11 UTC, tiniuspre approved these changes

2024-04-11 15:05 UTC, robines commented on backend/samfundet/tests/test_views.py
> +        }
Ser ut til å være gjort, resolver.

2024-04-11 15:06 UTC, robines approved these changes
LGTM

2024-04-11 15:20 UTC, merged