797 assign interviewees to interview
Samfundet/Samfundet4 pull request #928
Opened 2024-01-18 18:43 UTC by amaliejvik

Implement functionality for adding interviewers for each interview
Pair programmed with @hei98 

Closes #797

2024-01-22 09:54 UTC, aTrueYety approved these changes

2024-01-22 16:30 UTC, aTrueYety approved these changes

2024-02-20 19:08 UTC, Snorre98 commented on backend/samfundet/serializers.py
> +    interviewers = InterviewerSerializer(many=True, read_only=True)
@tiniusp gjør "read_only=True" her at man ikke får lagt til dataen og videre ikke kan bruke den i create og update lengre nede? Kan hende jeg surrer her.

2024-04-01 16:17 UTC, tiniuspre requested changes

2024-04-01 16:17 UTC, tiniuspre commented on backend/samfundet/migrations/0012_alter_notification_options_and_more.py
Kan så sammen migrations

2024-04-01 16:17 UTC, tiniuspre commented on backend/samfundet/serializers.py
> +    interviewers = InterviewerSerializer(many=True, read_only=True)
Ja, er det meningen @amaliejvik

2024-04-04 16:43 UTC, amaliejvik commented on backend/samfundet/migrations/0012_alter_notification_options_and_more.py
hvordan gjør man det? 🤭

2024-04-16 17:28 UTC, tiniuspre commented on backend/samfundet/migrations/0012_alter_notification_options_and_more.py
https://coderbook.com/@marcus/how-to-squash-and-merge-django-migrations/

2024-04-16 17:29 UTC, tiniuspre commented on backend/samfundet/serializers.py
> +    interviewers = InterviewerSerializer(many=True)
@hei98

2024-04-16 17:30 UTC, tiniuspre commented on backend/samfundet/serializers.py
> +    interviewers = InterviewerSerializer(many=True, read_only=True)
Eller se hvorfor pipeline feiler og se hva django anbefaler

2024-04-16 17:30 UTC, tiniuspre commented on backend/samfundet/migrations/0012_alter_notification_options_and_more.py
Eller se hvorfor pipeline feiler og se hva django anbefaler

2024-04-16 19:55 UTC, robines commented
@amaliejvik @hei98 Ser ut til at det er migration konflikt med master, her er det bare å slette migrationene og kjøre makemigrations på nytt

2024-04-16 21:17 UTC, hei98 commented
> @amaliejvik @hei98 Ser ut til at det er migration konflikt med master, her er det bare å slette migrationene og kjøre makemigrations på nytt

Slette alle migrations filene også kjøre makemigrations eller bare de som har like tall?

2024-04-16 21:22 UTC, amaliejvik commented
Kun de 2 som kom i konflikt !👍🏻
Sendt fra min iPhone

16. apr. 2024 kl. 23:18 skrev hei98 ***@***.***>:

﻿

@amaliejvik<https://github.com/amaliejvik> @hei98<https://github.com/hei98> Ser ut til at det er migration konflikt med master, her er det bare å slette migrationene og kjøre makemigrations på nytt

Slette alle migrations filene også kjøre makemigrations eller bare de som har like tall?

—
Reply to this email directly, view it on GitHub<https://github.com/Samfundet/Samfundet4/pull/928#issuecomment-2059937420>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A53HMDHGLFORTNS5V4BE5ZDY5WIQ5AVCNFSM6AAAAABCAYIHKCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANJZHEZTONBSGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-04-16 21:54 UTC, hei98 commented on backend/samfundet/migrations/0012_alter_notification_options_and_more.py
Fixed

2024-04-18 19:47 UTC, tiniuspre approved these changes

2024-04-25 19:01 UTC, merged