Availability dialog redesign
Samfundet/Samfundet4 pull request #944
Opened 2024-02-01 23:41 UTC by robines

2024-04-04 21:04 UTC, emilte commented on backend/samfundet/views.py
> +                        timezone=datetime.UTC,
Tror ikke vi vil ha utc?

2024-04-04 21:07 UTC, emilte commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +};
./types

2024-04-04 21:07 UTC, emilte commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +];
./utils

2024-04-04 21:08 UTC, emilte commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +  const getMarker = (d: Date | null) => {
func

2024-04-04 21:08 UTC, emilte commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +  const dateValid = (d: Date) => {
func

2024-04-04 21:08 UTC, emilte commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +    const setup = () => {
func

2024-04-04 21:09 UTC, emilte commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +          );
Vurder sub-comp

2024-04-04 21:10 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  const save = () => {
func

2024-04-04 21:10 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  const markers = useMemo(() => {
func

2024-04-04 21:10 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  const toggleTimeslot = (d: Date, timeslot: string) => {
func

2024-04-04 21:11 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  };
Begynner å bli for stor comp. Noe bør forenkles og flyttes til ./utils

2024-04-04 21:12 UTC, emilte reviewed
Veldig stor PR, vurder å dele opp i mindre biter

2024-04-05 12:34 UTC, robines commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +};
Flyttet MiniCalendar til ny PR: #1056

2024-04-05 12:35 UTC, robines commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +          );
Syns det blir unødvendig for en så liten komponent

2024-04-05 12:35 UTC, robines commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +];
Gjort i #1056

2024-04-05 12:35 UTC, robines commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +  const getMarker = (d: Date | null) => {
Gjort i #1056

2024-04-05 12:35 UTC, robines commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +  const dateValid = (d: Date) => {
Gjort i #1056

2024-04-05 12:35 UTC, robines commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +    const setup = () => {
Gjort i #1056

2024-04-05 12:42 UTC, robines commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  const markers = useMemo(() => {
Ikke for useMemo nei

2024-04-05 12:46 UTC, robines commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  const save = () => {
Gjort

2024-04-05 12:46 UTC, robines commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  const toggleTimeslot = (d: Date, timeslot: string) => {
Gjort

2024-04-05 12:50 UTC, robines commented
@emilte Syns den skal være mer håndterbar nå.

2024-04-05 12:52 UTC, robines commented on backend/samfundet/views.py
> +                        timezone=datetime.UTC,
Å lagre dato/tid i UTC er absolutt noe vi vil gjøre.

2024-04-05 12:52 UTC, robines commented on backend/samfundet/views.py
> +                        timezone=datetime.UTC,
https://dba.stackexchange.com/a/324021

2024-04-06 13:50 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  const markers = useMemo(() => {
sant

2024-04-06 13:53 UTC, emilte commented on backend/samfundet/views.py
> +                        timezone=datetime.UTC,
Jeg er ikke så rutta på timezone, men jeg er ikke sikker på at det er en universell sannhet.
Vi prøver å finne ut når en bruker er tilgjengelig, trenger vi ikke riktig tz?

2024-04-06 13:59 UTC, emilte commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +];
Med ./<> refererer jeg til lokal mappe fyi

2024-04-06 14:01 UTC, emilte commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +          );
Kanskje en smule, er bare for oversikten sin skyld. Det blir også enda et fint eksempel i kodebasen som kan inspirere de andre.
De nye vet så vidt hva sub-comp er, så filene har en tendens til å bli veldig store.

2024-04-06 14:01 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  const markers = useMemo(() => {
sant

2024-04-06 14:03 UTC, robines commented on backend/samfundet/views.py
> +                        timezone=datetime.UTC,
Det er god praksis å lagre dato/tid i UTC, og så når man henter ut og skal vise til bruker kan man konvertere til lokal tid. Det gjør at i backenden/databasen blir datoer konsistent, og vi trenger ikke tenke på all tullet som skjer med tidssoner og slik. Så når en bruker sier at de er utilgjengelig f.eks. i dag kl. 16:00, sendes det til backend, og lagres i UTC som 14:00 (siden forskjellen nå er UTC+2). Når det hentes ut igjen vil det vises som 16:00 for brukeren. Jeg syns det er ryddig

2024-04-06 14:19 UTC, emilte commented on backend/samfundet/views.py
> +                        timezone=datetime.UTC,
Hvordan vet man at det er utc+2?

2024-04-11 19:28 UTC, tiniuspre requested changes
For backend

2024-04-11 19:28 UTC, tiniuspre commented on backend/samfundet/views.py
> +            return Response({'error': 'dates is required'}, status=status.HTTP_400_BAD_REQUEST)
Validering er enklest og best i en serializer

2024-04-11 19:28 UTC, tiniuspre commented on backend/samfundet/views.py
> +            for d in request.data['dates']:
Endre d til date, enklere å lese

2024-04-11 21:23 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }
Rene func kan flyttes ut til ./utils.ts

2024-04-11 21:24 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +                        }`}
bruk classNames

2024-04-11 21:51 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +              {selectedDate ? (
Er det lettere å snu om ternary?

2024-04-11 21:52 UTC, emilte commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +              {selectedDate ? (
Jeg ville nok vurdert sub comp for å redusere mental overload

2024-04-25 23:21 UTC, robines commented on backend/samfundet/views.py
> +            for d in request.data['dates']:
Gjort

2024-04-25 23:24 UTC, robines commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +  }
Gjort

2024-04-25 23:26 UTC, robines commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +                        }`}
Gjort

2024-04-26 00:26 UTC, robines commented on frontend/src/Components/OccupiedForm/OccupiedForm.tsx
> +              {selectedDate ? (
Har splittet opp til TimeslotContainer og TimeslotButton

2024-04-26 01:29 UTC, robines commented on frontend/src/Components/MiniCalendar/MiniCalendar.tsx
> +          );
Ikke relevant for denne PRen lenger, resolve?

2024-04-26 01:36 UTC, robines commented on backend/samfundet/models/recruitment.py
> +    timeslot_interval = models.PositiveSmallIntegerField(help_text='The time interval (in minutes) between each timeslot', default=30)
Dette er kun et problem for instanser knyttet til stillinger. Har fjernet unique-constrainten med `recruitment` og `position`, så man kan nå lage flere interview availability for samme stilling. Må legge til en sjekk når man lagrer at de ikke overlapper da.

Må også legge til en manuell sjekk nå for å forsikre om at det kun finnes maks én instans av interview availability som har recruitment satt og ingen position, da det er denne instansen som brukes for å fylle ut frontend-interfacet.

2024-05-07 21:14 UTC, tiniuspre commented on backend/samfundet/views.py
> +                        timezone=datetime.UTC,
https://docs.djangoproject.com/en/5.0/topics/i18n/timezones/

2024-05-07 21:38 UTC, emilte commented on backend/samfundet/views.py
> +                        timezone=datetime.UTC,
Synes dokumentasjonen er litt tung her. Hva skjer hvis man har USE_TZ og bruker make_aware med tz annen fra UTC?

2024-05-29 20:54 UTC, robines commented on backend/samfundet/views.py
> +                        timezone=datetime.UTC,
Poenget er bare at det er mye enklere å forholde seg til dato og tid som er lagret i UTC.
Men denne diskusjonen er uansett ikke relevant for denne PRen da jeg ikke har endret noe med det å gjøre. Lag heller issue så kan vi se på det videre der

2024-06-10 20:40 UTC, robines commented on backend/samfundet/views.py
> +            return Response({'error': 'dates is required'}, status=status.HTTP_400_BAD_REQUEST)
Syns det blir unødvendig abstraksjon her

2024-06-21 12:53 UTC, tiniuspre approved these changes

2024-06-23 00:58 UTC, Snorre98 approved these changes

2024-06-23 08:49 UTC, merged