688 add custom attachments to application 2
Samfundet/Samfundet4 pull request #992
Opened 2024-02-14 01:56 UTC by Snorre98

Samme som #976, men med mindre problemer(forhåpentligvis)

2024-02-14 22:33 UTC, emilte commented on backend/samfundet/models/recruitment.py
> +    file_upload = models.FileField(help_text='Applicant file', blank=True, upload_to=upload_file_recruitment_path, null=True, verbose_name='Applicant file')
Validere hva? Det er sikkert fint å gjøre det i samme slengen + et par tester. Hvis ikke er det sannsynlig at funksjonalitet bare blir liggende uten noen verifikasjon på at det fungerer.

2024-02-15 12:28 UTC, Snorre98 commented on backend/samfundet/models/recruitment.py
> +    file_upload = models.FileField(help_text='Applicant file', blank=True, upload_to=upload_file_recruitment_path, null=True, verbose_name='Applicant file')
Ok, kan fikse det i kveld. Tenkte at det måtte valideres at det faktisk lastes opp bilde filer. Var litt usikker på hvordan det gjøres, men tror jeg kontroll på det nå.

2024-02-15 15:36 UTC, emilte commented on backend/samfundet/models/recruitment.py
> +    file_upload = models.FileField(help_text='Applicant file', blank=True, upload_to=upload_file_recruitment_path, null=True, verbose_name='Applicant file')
Vi bør absolutt sikre oss mot dette.

2024-02-15 19:17 UTC, magsyg commented on backend/samfundet/models/utils/recruitment_filename.py
> +    folder_name = f'uploads/recruitment_admission_files/{username}_files/admission_ID_{recruitment_position_id}'
mappen her burde nok bare være opptaket kanskje? ikke ha eget folder med navn på søker, kan bli mer slit å slette

2024-03-07 20:33 UTC, Snorre98 commented on backend/samfundet/models/utils/recruitment_filename.py
> +    folder_name = f'uploads/recruitment_admission_files/{username}_files/admission_ID_{recruitment_position_id}'
@magsyg  Sånn som nå?

2024-03-07 20:48 UTC, tiniuspre requested changes

2024-03-07 20:48 UTC, tiniuspre commented on backend/samfundet/constants.py
> +ONE_MB = 1000000
Lag heller en funksjon for å konvertere.

2024-03-07 20:48 UTC, tiniuspre commented on backend/samfundet/models/recruitment.py
> +                                     on_delete=models.CASCADE)
_id blir litt feil føler jeg med tanke på at det blir også et annet felt som heter id.

Hadde heller brukt admission

2024-03-07 20:48 UTC, tiniuspre commented on backend/samfundet/views.py
> +    permission_classes = [AllowAny]
AllowAny her?

2024-03-07 20:48 UTC, tiniuspre commented on backend/samfundet/views.py
> +    queryset = AdmissionFileUpload.objects.all()
Alle bilder?

2024-03-07 20:48 UTC, tiniuspre commented on backend/samfundet/models/utils/video_validation.py
> +def is_video_valid(video: File) -> bool:
?
```suggestion
def is_video_valid(video: File) -> bool:
   # TODO FIX
   ...
```

2024-03-07 20:48 UTC, tiniuspre commented on backend/samfundet/models/utils/recruitment_filename.py
> +    unique_filename = f'{uuid.uuid4()}-{filename}'
uuid'en burde lages i modellen, evt ha ID'en på bilde objektet som en uuid du bruker her. Så kan vi enklere finne filnavnet manuelt om det er behov for det.

2024-03-07 20:48 UTC, tiniuspre commented on backend/samfundet/models/utils/image_validation.py
> +        return False
```suggestion
    return False
```

2024-03-07 20:48 UTC, tiniuspre commented on backend/samfundet/models/utils/image_validation.py
> +        return False
```suggestion
    if max_size < 5 * ONE_MB:
       return False
    try:
        img = Image.open(image)
        img = img.crop(upper, right, lower, left)
        return True
    except OSError:
        return False
    return False
```

2024-03-08 13:08 UTC, emilte commented on backend/samfundet/models/utils/image_validation.py
> +    Uses Pillow to verify that the image is an acctauly image.
acctauly

2025-02-12 15:07 UTC, closed without merging